env:
  CI: true
  COVERAGE: true

name: CI - CD
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - develop
      - master
jobs:
  security:
    name: Brakeman
    if: "${{ github.actor != 'dependabot[bot]' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Brakeman
        uses: reviewdog/action-brakeman@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        cache-version: 347

    - name: Run RuboCop
      run: bundle exec rubocop --parallel

  check-swagger:
    name: Check Swagger generation
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: siade
          POSTGRES_DB: siade_test
          POSTGRES_PASSWORD: wow*verysecret
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports: ["6379:6379"]
        options: --entrypoint redis-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 322

      - name: Run install.sh
        run: ./bin/install.sh

      - name: Check Swagger file is up-to-date
        run: ./bin/test_swagger.sh

  check-zeitwerk:
    name: Check Zeitwerk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 322

      - name: Check Zeitwerk
        run: |
          bundle exec rails runner 'Zeitwerk::Loader.eager_load_all'
        env:
          ZEITWERK_CHECK: true

  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: siade
          POSTGRES_DB: siade_test
          POSTGRES_PASSWORD: wow*verysecret
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports: ["6379:6379"]
        options: --entrypoint redis-server

    steps:
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 322

      - name: Update repository
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install libgpgme11-dev

      - name: Run install.sh
        run: ./bin/install.sh

      - name: set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Paris"

      - name: Run tests
        run: COVERAGE=true bundle exec rspec

      - uses: joshmfrankel/simplecov-check-action@main
        if: "${{ github.actor != 'dependabot[bot]' }}"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_suite_coverage: 95

  merge-with-master:
    name: Merge develop with master
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs:
      - security
      - lint
      - check-swagger
      - check-zeitwerk
      - tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Force push develop to master
        run: |
          git push --force origin develop:master

  continuous-deployment-staging:
    name: Continuous deployment on staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    timeout-minutes: 10
    needs:
      - security
      - lint
      - check-swagger
      - check-zeitwerk
      - tests
      - merge-with-master
    strategy:
      matrix:
        host: [watchdoge3, watchdoge4]
      fail-fast: false
    environment: staging
    env:
      DEPLOY_HTTPS_LOGIN: ${{ secrets.DEPLOY_HTTPS_LOGIN }}
      DEPLOY_HTTPS_PASSWORD: ${{ secrets.DEPLOY_HTTPS_PASSWORD }}
      DEPLOY_HTTPS_REQUEST_URL: ${{ vars.DEPLOY_HTTPS_REQUEST_URL }}
      DEPLOY_HTTPS_RESPONSE_URL: ${{ vars.DEPLOY_HTTPS_RESPONSE_URL }}
      DEPLOY_HOST: host_${{ matrix.host }}
      DEPLOY_APP: siade_staging
    steps:
      - name: Download and run deploy script
        shell: bash
        run: |
          git clone https://github.com/etalab/api-entreprise-integration
          cd api-entreprise-integration
          ./deploy-parteprise.sh

  continuous-deployment-production:
    name: Continuous deployment on production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    timeout-minutes: 20
    needs:
      - security
      - lint
      - check-swagger
      - check-zeitwerk
      - tests
      - merge-with-master
      - continuous-deployment-staging
    strategy:
      matrix:
        host: [watchdoge3, watchdoge4]
        deploy_env: [production]
      fail-fast: false
    environment: production
    env:
      DEPLOY_HTTPS_LOGIN: ${{ secrets.DEPLOY_HTTPS_LOGIN }}
      DEPLOY_HTTPS_PASSWORD: ${{ secrets.DEPLOY_HTTPS_PASSWORD }}
      DEPLOY_HTTPS_REQUEST_URL: ${{ vars.DEPLOY_HTTPS_REQUEST_URL }}
      DEPLOY_HTTPS_RESPONSE_URL: ${{ vars.DEPLOY_HTTPS_RESPONSE_URL }}
      DEPLOY_HOST: host_${{ matrix.host }}
      DEPLOY_APP: siade_${{ matrix.deploy_env }}
    steps:
      - name: Download and run deploy script
        shell: bash
        run: |
          git clone https://github.com/etalab/api-entreprise-integration
          cd api-entreprise-integration
          ./deploy-parteprise.sh
