name: Regenerate and commit Swagger

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to apply changes to'
        required: true
        type: number

jobs:
  regenerate-swagger-and-commit:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: siade
          POSTGRES_DB: siade_test
          POSTGRES_PASSWORD: wow*verysecret
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ["6379:6379"]
        options: --entrypoint redis-server

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 322

      - name: Run install.sh
        run: ./bin/install.sh

      - name: Regenerate Swagger
        run: ./bin/generate_swagger.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Regenerate Swagger (from Github Actions)"
