export { Client, type ClientOptions } from './client.js';
export { VERSION } from './version.js';
export {
  type AuthStrategy,
  BearerToken,
  ApiGouvError,
  AuthenticationError,
  AuthorizationError,
  ClientError,
  ConflictError,
  InvalidSirenError,
  InvalidSiretError,
  MissingParameterError,
  NotFoundError,
  ProviderError,
  ProviderUnavailableError,
  RateLimitError,
  ServerError,
  TransportError,
  ValidationError,
  type JsonApiError,
  Configuration,
  type ConfigurationOptions,
  type Environment,
  type Logger,
  type RetryConfig,
  RateLimit,
  Response,
} from './commons/index.js';
