acoss:
  attestation_sociale:
    title: "Attestation de vigilance"
    description: "Obtenir l'attestation validant que l'entreprise s'acquitte de ses obligations déclaratives et du paiement des cotisations et contributions sociales auprès de l'URSSAF Caisse nationale (anciennement ACOSS)."
    tags:
      - "Attestations sociales et fiscales"
    document_url_properties:
      title: "Lien vers l'attestation de vigilance URSSAF"
      description: "Ce document est automatiquement supprimé au bout de trois mois."
      example: "https://storage.entreprise.api.gouv.fr/siade/1569139162-b99824d9c764aae19a862a0af-attestation_vigilance_acoss.pdf"
