acoss:
  attestation_sociale:
    title: "Attestation de vigilance"
    description: "Attestation sociale délivrée à une entreprise acquittée de ses obligations de cotisations et contributions sociales auprès de l'URSSAF Caisse nationale."
    tags:
      - "Attestations sociales et fiscales"
    document_url_properties:
      title: "URL de téléchargement de l'attestation de vigilance"
      description: "Ce lien délivre l'attestation de vigilance de l'entreprise au format PDF. La date du document dépend de la situation de chaque entreprise, et de la dernière déclaration enregistrée dans le système. Elle est donc variable d'une entreprise à l'autre.
      \n
      \n
      Plus d'informations sur le site de l'URSSAF : https://www.urssaf.fr/portail/home/employeur/declarer-et-payer/obtenir-une-attestation/attestation-de-vigilance.html"
      example: "https://raw.githubusercontent.com/datagouv/apistration/refs/heads/develop/mocks/payloads/api_entreprise_v4_acoss_attestations_sociales/attestation_vigilance_test.pdf"
    document_url_expires_in:
      title: "Nombre de secondes avant expiration du lien URL"
