ademe:
  certificats_rge:
    title: "Certification RGE"
    description: "Certifications RGE (Reconnu Garant de l'Environnement) d'un établissement, délivrées par l'Ademe."
    tags:
      - "Certifications professionnelles"
    meta:
      total:
        title: "Total"
        description: "Nombre de résultats (certificats) totaux"
        type: "number"
        example: 8
    attributes:
      url:
        title: "URL Certificat"
        description: "URL de téléchargement du certificat"
        type: "string"
        example: "https://raw.githubusercontent.com/datagouv/apistration/refs/heads/develop/mocks/payloads/api_entreprise_v3_ademe_certificats_rge/exemple-ademe-rge-certificat_qualibat.pdf"
      nom_certificat:
        title: "Nom du certificat"
        description: "libéllé du certificat"
        type: "string"
        example: "Qualisol CESI"
      domaine:
        title: "Domaine de travaux"
        description: "Domaine des travaux sur lesquelles porte la qualification du certificat"
        type: "string"
        enum:
          - "Fenêtres, volets, portes extérieures 2020"
          - "Isolation du toit 2020"
          - "Isolation des murs et planchers bas 2020"
          - "Chaudière condensation ou micro-cogénération gaz ou fioul 2020"
          - "Equipements électriques hors ENR : chauffage, eau chaude, éclairage 2020"
          - "Isolation par l'intérieur des murs ou rampants de toitures  ou plafonds"
          - "Isolation des combles perdus"
          - "Pompe à chaleur : chauffage"
          - "Fenêtres, volets, portes donnant sur l'extérieur"
          - "Isolation des planchers bas"
          - "Chaudière condensation ou micro-cogénération gaz ou fioul"
          - "Ventilation 2020"
          - "Poêle ou insert bois"
          - "Isolation des murs par l'extérieur"
          - "Radiateurs électriques, dont régulation."
          - "Chauffe-Eau Thermodynamique"
          - "Isolation des toitures terrasses ou des toitures par l'extérieur"
          - "Fenêtres de toit"
          - "Chaudière bois"
          - "Pompe à chaleur et/ou Chauffe-eau thermodynamique 2020"
          - "Architecte"
          - "Chauffage et/ou eau chaude solaire"
          - "Panneaux solaires photovoltaïques"
          - "Ventilation mécanique"
          - "Chauffage et/ou eau chaude au bois 2020"
          - "Audit énergétique"
          - "Panneaux photovoltaïques 2020"
          - "Etude thermique reglementaire"
          - "Chauffage et/ou eau chaude solaire 2020"
          - "Projet complet de rénovation"
          - "Etude solaire photovoltaïque"
          - "Etude bois énergie"
          - "Etude forage géothermique"
          - "Etude solaire thermique"
          - "Etude système technique bâtiment"
          - "Etude eclairage"
          - "Forage géothermique"
          - "Etude ACV"
          - "Inconnu"
          - "Non renseigné"
          - "Etude enveloppe du bâtiment"
          - "Commisionnement"
      meta_domaine:
        title: "Méta domaine"
        description: "Le Méta domaine explicite le contexte de la qualification du certificat"
        type: "string"
        example: "anciens domaines avant 2021"
        enum:
          - "anciens domaines avant 2021"
          - "Travaux d'efficacité énergétique"
          - "Installations d'énergies renouvelables"
          - "Rénovation globale"
          - "Etudes énergétiques"
          - "Inconnu"
          - "Non renseigné"
      qualification:
        title: "Qualification"
        description: "Informations sur la qualification du présent certificat"
        type: "object"
        additionalProperties: false
        properties:
          code:
            title: "Code qualification"
            description: "Code de la qualification du présent certificat"
            type: "string"
            example: "32"
          nom:
            title: "Nom qualification"
            description: "Nom de la qualification du présent certificat"
            type: "string"
            example: "QualiPV Elec - Pose de générateur photovoltaïque raccordé au réseau (32)"
      organisme:
        title: "Organisme de certification"
        description: "Organisme ayant délivré le certificat"
        type: "string"
        example: "qualibat"
        enum:
          - "Non renseigné"
          - "qualibat"
          - "qualitenr"
          - "cnoa"
          - "opqibi"
          - "qualifelec"
          - "cequami"
          - "certibat"
          - "afnor"
          - "Inconnu"
      date_attribution:
        title: "Date d'attribution"
        description: "Date à laquelle a été attribué le certificat"
        type: "string"
        example: "2020-12-24"
      date_expiration:
        title: "Date d'expiration"
        description: "Date à laquelle le présent certificat expire"
        type: "string"
        example: "2025-08-01"
      meta:
        title: "Informations ADEME"
        description: "informations sur l'enregistrement de ce certificat dans la base ADEME"
        type: "object"
        additionalProperties: false
        properties:
          internal_id:
            title: "Identifiant interne"
            description: "Identifiant unique du certificat dans la base ADEME"
            type: "string"
            example: "Q112379-8611M12D10-2017-03-23"
          updated_at:
            title: "Date de mise à jour"
            description: "Date à laquelle cette information à été mise à jour dans la base ADEME"
            type: "string"
            example: "2021-02-25"
          archived:
            title: "Archivé"
            description: "Indique si le présent certificat est archivé dans la base ADEME et donc invalide. \"True\" signifie archivé donc invalide."
            type: "boolean"
            example: false
