cnav:
  commons:
    cache_duration: "La durée du cache est de 1 heure."
    cnav_identite_pivot: &cnav_identite_pivot
      nomUsage:
        type: "string"
        description: "Nom d'usage. Ne pas renseigner si présence de jeton FranceConnect."
        example: "DUPONT"
      nomNaissance:
        type: "string"
        description: "Nom de naissance. Ne pas renseigner si présence de jeton FranceConnect."
        example: "JEAN"
      prenoms:
        description: "Liste des prénoms. Ne pas renseigner si présence de jeton FranceConnect."
        type: "array"
        minItems: 1
        example: ['PIERRE', 'RICHARD']
      anneeDateDeNaissance:
        description: "Année de naissance. Ne pas la renseigner si celle-ci est inconnue ou en cas de présence de jeton FranceConnect."
        type: integer
        example: 1990
      moisDateDeNaissance:
        description: "Mois de naissance. Ne pas le renseigner si celui-ci est inconnu ou en cas de présence de jeton FranceConnect. Cette valeur est ignorée si anneeDateDeNaissance est vide."
        type: integer
        example: 1
      jourDateDeNaissance:
        description: "Jour de naissance. Ne pas le renseigner si celui-ci est inconnu ou en cas de présence de jeton FranceConnect. Cette valeur est ignorée si moisDateDeNaissance ou anneeDateDeNaissance est vide."
        type: integer
        example: 1
      codeInseeLieuDeNaissance:
        type: string
        minLength: 5
        maxLength: 5
        example: '08480'
        description: "Code Insee à 5 chiffres du lieu de naissance de la personne sur 5 chiffres. Ne pas remplir si la personne est née à l'étranger ou si présence de jeton FranceConnect. En l'absence de jeton FranceConnect et du triplet (nomCommuneNaissance, anneeDateDeNaissance, codeInseeDepartementNaissance), le champs est obligatoire si la personne est née en France"
      codePaysLieuDeNaissance:
        description: "Code Insee à 5 chiffres du pays de naissance (France = 99100). Obligatoire si absence de jeton FranceConnect."
        type: string
        minLength: 5
        maxLength: 5
        example: '99100'
      sexe:
        description: "Sexe de la personne, masculin ou féminin. Obligatoire si absence de jeton FranceConnect."
        type: string
        example: M
        enum:
          - M
          - F

  c2s:
    title: Statut complémentaire santé solidaire (C2S)
    description: |+
      "Savoir si un particulier est bénéficiaire de la complémentaire santé solidaire (C2S).
      \n\n
      Pour de plus amples informations sur cette api et y avoir accès en avant première, veuillez contacter l'équipe API Particulier.
      \n
      **Données disponibles en bac à sable :** [liste](https://github.com/etalab/siade_staging_data/blob/develop/payloads/complementaire_sante_solidaire)
      \n
      L'API peut être appellée avec les données identité pivot ou avec un jeton FranceConnect.
      "
    tags:
      - Complementaire Sante Solidaire
    parameters:
      <<: *cnav_identite_pivot
      nomCommuneNaissance:
        type: string
        minLength: 1
        example: 'Gennevilliers'
        description: "Nom de la commune de naissance. En l'absence de jeton FranceConnect et du codeInseeLieuDeNaissance, ce paramètre est obligatoire si la personne est née en France"
      codeInseeDepartementNaissance:
        type: string
        minLength: 2
        maxLength: 3
        example: '92'
        description: "Code INSEE du département de naissance. En l'absence de jeton FranceConnect et du codeInseeLieuDeNaissance, ce paramètre est obligatoire si la personne est née en France"
    attributes:
      status:
        title: "Statut bénéficiaire de la C2S"
        type: string
        description: |+
          "Indique si le particulier est bénéficiaire de la complémentaire de santé solidaire au moment de l'appel. Cet indicateur précise sous quelle forme la C2S est attribuée (avec ou sans participation financière).
          - Si le statut est 'beneficiaire_sans_participation_financiere', cela signifie que le particulier est bénéficiaire d'une C2S sans participation financière.
          - Si le statut est 'beneficiaire_avec_participation_financiere', cela signifie que le particulier est d'une bénéficiaire de C2S avec participation financière.
          - Si le statut est 'non_beneficiaire_css', cela signifie que le particulier n'est pas concerné par la C2S."
        enum:
          - "beneficiaire_sans_participation_financiere"
          - "beneficiaire_avec_participation_financiere"
          - "non_beneficiaire_css"
      dateDebut:
        title: "Date d'ouverture du droit à la C2S"
        type: string
        nullable: true
        description: |+
          "Date de début de droit à la complémentaire santé solidaire (C2S) si le particulier est bénéficiaire.
          Ce champs est null dans le cas où le particulier n'est pas bénéficiaire de la C2S."
        example: '1992-11-29'
      dateFin:
        title: "Date de fermeture du droit à la C2S"
        type: string
        nullable: true
        description: |+
          "Date de fin de droit à la complémentaire santé solidaire (C2S) du particulier bénéficiaire.
          Ce champs est calculé en ajoutant 12 mois à la date de début de droit à la C2S.
          Ce champs sera null dans le cas où le particulier n'est pas bénéficiaire de la C2S."
        example: '1993-11-29'
  quotient-familial-v2:
    title: Quotient familial MSA & CAF
    description: |+
      "Quotient familial et composition de la famille d'un allocataire du régime agricole (régime général à venir).
      \n
      Pour de plus amples informations sur cette api et y avoir accès en avant première, veuillez contacter l'équipe API Particulier.
      \n
      **Données disponibles en bac à sable :** [liste](https://github.com/etalab/siade_staging_data/blob/develop/payloads/api_particulier_v2_cnav_quotient_familial_v2)
      \n
      L'API peut être appellée avec les données identité pivot ou avec un jeton FranceConnect."
    cache_duration: "La durée du cache est de 24 heure."
    tags:
      - Quotient familial
    parameters:
      <<: *cnav_identite_pivot
      nomCommuneNaissance:
        type: string
        minLength: 1
        example: 'Gennevilliers'
        description: "Nom de la commune de naissance. En l'absence de jeton FranceConnect et du codeInseeLieuDeNaissance, ce paramètre est obligatoire si la personne est née en France"
      codeInseeDepartementNaissance:
        type: string
        minLength: 2
        maxLength: 3
        example: '92'
        description: "Code INSEE du département de naissance. En l'absence de jeton FranceConnect et du codeInseeLieuDeNaissance, ce paramètre est obligatoire si la personne est née en France"
      annee:
        description: "Année du quotient familial recherché. Si l'année n'est pas renseignée, le dernier QF est transmis. Remonte au maximum à 2 ans."
        type: integer
        example: 2023
      mois:
        description: "Mois pour le quotient, si non renseigné renvoie le dernier QF calculé"
        type: integer
        example: 12
    attributes:
      allocataires:
        title: "Informations sur les parents composant la famille"
        type: array
        minItems: 1
        items:
          type: object
          properties:
            nomNaissance:
              title: Nom
              type: string
              description: Nom de naissance de l'allocataire
              example: "JACQUES"
            nomUsuel:
              title: Nom d'usage
              type: string
              description: Nom d'usage de l'allocataire
              example: "JACQUES"
              nullable: true
            prenoms:
              title: Prénoms
              type: string
              description: Prénoms de l'allocataire
              example: "JEAN-PIERRE THOMAS"
            anneeDateDeNaissance:
              title: Année de naissance
              type: string
              example: '2000'
              description: "Année de la date de naissance de l'allocataire. Peut-être vide si inconnue."
              nullable: true
            moisDateDeNaissance:
              title: "Mois de naissance"
              type: string
              example: '01'
              description: "Mois de la date de naissance de l'allocataire. Peut-être vide si inconnue."
              nullable: true
            jourDateDeNaissance:
              title: "Jour de naissance"
              type: string
              example: '31'
              description: "Jour de la date de naissance de l'allocataire. Peut-être vide si inconnue."
              nullable: true
            sexe:
              title: "Sexe"
              type: string
              description: "Sexe de l'allocataire"
              example: "M"
              enum:
                - F
                - M
      enfants:
        type: array
        title: "Informations sur les enfants composant la famille"
        items:
          type: object
          properties:
            nomNaissance:
              title: "Nom de naissance"
              type: string
              description: Nom de naissance de l'enfant
              example: "JACQUES"
            nomUsuel:
              title: "Nom d'usage"
              type: string
              description: Nom d'usage de l'enfant
              example: "JACQUES"
              nullable: true
            prenoms:
              title: "Prénoms"
              type: string
              description: Prénoms de l'enfant
              example: "JEAN-PIERRE THOMAS"
            anneeDateDeNaissance:
              title: "Année de naissance"
              type: string
              example: '2000'
              description: "Année de la date de naissance de l'enfant. Peut-être vide si inconnue."
              nullable: true
            moisDateDeNaissance:
              title: "Mois de naissance"
              type: string
              example: '01'
              description: "Mois de la date de naissance de l'enfant. Peut-être vide si inconnue."
              nullable: true
            jourDateDeNaissance:
              title: "Jour de naissance"
              type: string
              example: '31'
              description: "Jour de la date de naissance de l'enfant. Peut-être vide si inconnue."
              nullable: true
            sexe:
              title: "Sexe"
              type: string
              description: "Sexe de l'enfant"
              example: "M"
              enum:
                - F
                - M
      adresse:
        title: "Adresse de la famille"
        type: object
        description: Adresse au format de la poste
        properties:
          identite:
            title: "Identité du destinataire"
            type: string
            example: "Monsieur JEAN JACQUES"
            description: "Identité du destinataire : Civilité, titre ou qualité + nom et
              prénom"
          complementInformation:
            title: "Complément d'information du destinataire ou point de remise"
            description: "Complément d'information du destinataire ou point de remise."
            type: string
            nullable: true
            example: null
          complementInformationGeographique:
            title: "Complément d'information du point géographique"
            type: string
            nullable: true
            example: null
            description: "Complément d'information du point géographique."
          numeroLibelleVoie:
            title: "Voie"
            type: string
            description: Numéro et libellé de la voie
            example: "1 RUE DE LA GARE"
            nullable: true
          lieuDit:
            title: "Lieu-dit"
            type: string
            nullable: true
            example: null
            description: "Lieu-dit ou service particulier de distribution : poste restante,
              boîte postale"
          codePostalVille:
            title: "Code postal"
            type: string
            description: Code postale et localité de destination
            example: '75002'
          pays:
            title: "Pays"
            type: string
            description: Pays
            example: 'FRANCE'
      regime:
        title: "Régime de l'allocataire"
        type: string
        description: Précise le régime de l'allocataire (CNAF ou MSA)
        example: MSA
        enum:
          - CNAF
          - MSA
      quotientFamilial:
        title: "Quotient familial CAF ou MSA"
        type: integer
        description: Valeur du quotient familial calculé par la CAF ou la MSA
        example: 1045
      annee:
        title: "Année du quotient familial"
        type: integer
        description: Année de calcul du quotient familial
        example: 2023
      mois:
        title: "Mois du quotient familial"
        type: integer
        description: Mois de calcul du quotient familial
        example: 6
      annee_calcul:
        title: "Année du calcul du quotient familial"
        type: integer
        description: Année à laquelle le quotient familial a été calculé
        example: 2023
      mois_calcul:
        title: "Mois du calcul du quotient familial"
        type: integer
        description: Mois auquel le quotient familial a été calculé
        example: 3

  rsa:
    title: Statut revenu de solidarité active (RSA)
    description: "Savoir si un particulier est bénéficiaire du revenu de solidarité active (RSA) et s'il bénéficie d'une majoration. Retourne également des informations sur les dates d'ouverture des droits.
      L'API peut être appellée avec les données identité pivot ou avec un jeton FranceConnect."
    tags:
      - RSA
      - Prochainement
    parameters: *cnav_identite_pivot
    attributes:
      status:
        title: "Statut bénéficiaire du RSA"
        type: string
        description: "Indique si le particulier est bénéficiaire du revenu de solidarité active au moment de l'appel."
        enum:
          - "beneficiaire"
          - "non_beneficiaire"
      majoration:
        title: "Statut bénéficiaire de la majoration du RSA"
        type: boolean
        nullable: true
        description: "Indique si le particulier est bénéficiaire du RSA majoré au moment de l'appel.
          Nécessite un scope spécifique pour être envoyé.
          Sera null si le particulier n'est pas bénéficiaire du RSA."
        example: false
      dateDebut:
        title: "Date d'ouverture du droit au RSA"
        type: string
        nullable: true
        description: |+
          "Date de début de droit au RSA si le particulier est bénéficiaire.
          Ce champs est null dans le cas où le particulier n'est pas bénéficiaire du RSA."
        example: '1992-11-29'
      dateFin:
        title: "Date de fermeture du droit au Revenu de solidarité active"
        type: string
        nullable: true
        description: |+
          "Date de fin de droit au Revenu de solidarité active du particulier bénéficiaire.
          Ce champs est calculé en ajoutant 3 mois à la date de début de droit du RSA.
          Ce champs sera null dans le cas où le particulier n'est pas bénéficiaire du RSA."
        example: '1993-02-20'

  aah:
    title: Statut allocation adulte handicapé (AAH)
    description: "Savoir si un particulier est bénéficiaire de l'allocation adulte handicapé (AAH). Retourne également des informations sur les dates d'ouverture des droits.
      L'API peut être appellée avec les données de l'identité pivot ou avec un jeton FranceConnect."
    tags:
      - AAH
      - Prochainement
    parameters: *cnav_identite_pivot
    attributes:
      status:
        title: "Statut bénéficiaire de l'AAH"
        type: string
        description: "Indique si le particulier est bénéficiaire de la complémentaire de santé solidaire au moment de l'appel."
        enum:
          - "beneficiaire"
          - "non_beneficiaire"
      dateDebut:
        title: "Date d'ouverture du droit à l'AAH"
        type: string
        nullable: true
        description: |+
          "Date de début de droit à l'AAH si le particulier est bénéficiaire.
          Ce champs est null dans le cas où le particulier n'est pas bénéficiaire de l'AAH."
        example: '1992-11-29'

  asf:
    title: Statut allocation de soutien familial (ASF)
    description: "Savoir si un particulier est bénéficiaire de l'allocation de soutien familial (ASF). Retourne également des informations sur les dates d'ouverture et de fermeture des droits.
      L'API peut être appellée avec les données identité pivot ou avec un jeton FranceConnect."
    tags:
      - ASF
      - Prochainement
    parameters: *cnav_identite_pivot
    attributes:
      status:
        title: "Statut bénéficiaire de l'ASF"
        type: string
        description: "Indique si le particulier est bénéficiaire de l'Allocation de Soutien Familial au moment de l'appel."
        enum:
          - "beneficiaire"
          - "non_beneficiaire"
      dateDebut:
        title: "Date d'ouverture du droit à l'ASF"
        type: string
        nullable: true
        description: |+
          "Date de début de droit à l'ASF si le particulier est bénéficiaire.
          Ce champs est null dans le cas où le particulier n'est pas bénéficiaire de l'ASF."
        example: '1992-11-29'
      dateFin:
        title: "Date de fermeture du droit à l'ASF"
        type: string
        nullable: true
        description: |+
          "Date de fin de droit à l'Allocation de Soutien Familial du particulier bénéficiaire.
          Ce champs est calculé en ajoutant 12 mois à la date de début de droit à l'ASF.
          Ce champs sera null dans le cas où le particulier n'est pas bénéficiaire de l'ASF."
        example: '1993-11-29'

  prime_activite:
    title: Statut prime d'activité (PA)
    description: "Savoir si un particulier est bénéficiaire de la prime d'activité (PA) et s'il bénéficie d'une majoration. Précise également si la PA est majorée ainsi que les dates d'ouverture et de fermeture des droits.
      L'API peut être appellée avec les données identité pivot ou avec un jeton FranceConnect."
    tags:
      - Prime d'activité
      - Prochainement
    parameters: *cnav_identite_pivot
    attributes:
      status:
        title: "Statut bénéficiaire de la prime d'activité"
        type: string
        description: "Indique si le particulier est bénéficiaire de la prime d'activité au moment de l'appel."
        enum:
          - "beneficiaire"
          - "non_beneficiaire"
      majoration:
        title: "Statut bénéficiaire de la majoration de la prime d'activité"
        type: boolean
        nullable: true
        description: "Indique si le particulier est bénéficiaire de la prime d'activité majorée au moment de l'appel.
          Nécessite un scope spécifique pour être envoyé.
          Sera null si le particulier n'est pas bénéficiaire de la prime d'activité."
        example: false
      dateDebut:
        title: "Date d'ouverture du droit à la prime d'activité"
        type: string
        nullable: true
        description: |+
          "Date de début de droit à la prime d'activité si le particulier est bénéficiaire.
          Ce champs est null dans le cas où le particulier n'est pas bénéficiaire de la prime d'activité."
        example: '1992-11-20'
      dateFin:
        title: "Date de fermeture du droit à la prime d'activité"
        type: string
        nullable: true
        description: |+
          "Date de fin de droit à la prime d'activité du particulier bénéficiaire.
          Ce champs est calculé en ajoutant 3 mois à la date de début de droit de la prime d'activité.
          Ce champs sera null dans le cas où le particulier n'est pas bénéficiaire de la prime d'activité."
        example: '1993-02-20'
