cnetp:
  attestation_cotisations_conges_payes_chomage_intemperies:
    title: "Attestation de cotisations congés payés & chômage-intempéries"
    description: "Obtenir l’attestation de cotisation des congés payés et chômage intempéries d’une entreprise, délivrée par la Caisse Nationale des Entrepreneurs de Travaux Publics (CNETP)."
    tags:
      - "Attestations sociales et fiscales"
    document_url_properties:
      title: "Lien vers l'attestation de cotisations"
      description: "Ce document est automatiquement supprimé au bout de 3 mois."
      example: "https://storage.entreprise.api.gouv.fr/siade/1569139162-b99824d9c764aae19a862a0af-certificat_cnetp.pdf"
