cnetp:
  attestation_cotisations_conges_payes_chomage_intemperies:
    title: "Certificat cotisations CNETP"
    description: "Certificat indiquant qu'une entreprise de travaux publics affiliée à la caisse CNETP est en règle de ses cotisations congés payés et chômage-intempéries."
    tags:
      - "Attestations sociales et fiscales"
    document_url_properties:
      title: "Lien vers le certificat CNETP"
      description: "Ce lien délivre l'attestation au format PDF. Ce document est automatiquement supprimé après 24h."
      example: "https://raw.githubusercontent.com/etalab/siade_staging_data/refs/heads/develop/payloads/api_entreprise_v3_cnetp_attestation_cotisations_conges_payes_chomage_intemperies/test_cnetp_certificat.pdf"
