cnetp:
  attestation_cotisations_conges_payes_chomage_intemperies:
    title: "Certificat cotisations CNETP"
    description: "Certificat indiquant qu'une entreprise du BTP affiliée à la caisse CNETP est en règle de ses cotisations congés payés et au chômage-intempéries."
    tags:
      - "Attestations sociales et fiscales"
    document_url_properties:
      title: "Lien vers l'attestation de cotisations"
      description: "Ce lien délivre l'attestation au format PDF. Ce document est automatiquement supprimé au bout de 24h."
      example: "https://storage.entreprise.api.gouv.fr/siade/1569139162-b99824d9c764aae19a862a0af-certificat_cnetp.pdf"
