data_subvention:
  subventions:
    title: Subventions des associations
    description: "Listes des subventions accordées et distribuées aux associations"
    tags:
      - Subventions des associations
    parameters:
      siren_or_siret_or_rna:
        type: string
        description: "Siren, Siret ou RNA de l'association dont vous souhaitez obtenir les subventions."
        example: "12345678901234"
        required: true
    attributes:
      demande_subvention:
        title: Liste des demandes de subventions de l'association et leur informations.
        type: object
        nullable: true
        properties:
          fournisseur:
            title: Fournisseur distribuant la donnée à Data Subvention
            description: Origine de la donnée transmise (OSIRIS, Chorus, etc.)
            type: string
            example: "OSIRIS"
          date_mise_a_jour_information:
            title: Date de dernière mise à jour
            description: Date de dernière mise à jour des informations. La fréquence d'actualisation des données varie selon le fournisseur, elle est décrite dans la fiche métier de l'API.
            type: string
            format: date-time
            example: "2019-01-01T00:00:00.000Z"
          annee_exercice_demande:
            title: Année de la demande de subvention
            description: Année durant laquelle la subvention a été demandée par l'association.
            type: number
            example: 2019
          identifiant_engagement_juridique:
            title: Numéro EJ
            description: Numéro d'engagement juridique (EJ) associé à la demande. Cet identifiant est présent pour toutes les demandes de subventions, sauf celles issues du FONJEP.
            type: string
            nullable: true
            example: "19/0003456"
          jointure_demandes_et_versements: 

            title: Identifiant de jointure entre demande et versement
            description: "Identifiant créé par DataSubvention pour faire le lien entre une demande figurant dans cette liste et un paiement figurant dans la liste suivante. Pour toutes les demandes de subventions, sauf celle issues du FONJEP, cet identifiant est identique au numéro EJ. Pour les demandes issues du FONJEP, ce numéro correspond au code poste."
            type: string
            nullable: true
            example: "19/0003456"
          subvention_demandee:
            title: Informations sur la subvention demandée
            type: object
            properties:
              dispositif:
                title: Nom du dispositif
                type: string
                example: "ANS - Projets Sportifs Territoriaux"
              sous_dispositif:
                title: Nom du sous-dispositif
                type: string
                example: "Aides territoriales (hors emploi)"
              montant_demande:
                title: Montant de subvention demandé
                description: Montant en euros de subvention demandé par l'association.
                type: number
                example: 2000
          description_des_projets:
            title: Éléments déclaratifs des projets
            description: Description détaillée par l'association des projets qui visent à être financés par l'association.
            type: object
            properties:
              estimation_cout_total:
                title: Estimation du coût total du projet
                description: Lorsqu'il est renseigné, ce montant indique le coût global du ou des projets évalué par le déclarant afin d'informer l'instructeur de l'ampleur du projet. 
                type: number
                example: 8500
              projet:
                title: Liste des projets et actions proposés
                type: array
                items:
                  title: Détails d'un projet ou action proposée
                  type: object
                  properties:
                    rang:
                      title: Rang du projet
                      description: Numéro d'ordre du projet par rapport aux autres projets.
                      type: number
                      example: 1
                    intitule:
                      title: Titre du projet
                      type: string
                      example: "Développement du football féminin"
                    objectifs:
                      title: Objectif du projet
                      description: Description de l'objectif du projet
                      type: string
                      example: Notre objectif est de  continuer à faire connaitre [...]
                    objectifs_operationnels:
                      title: Objectifs opérationnels
                      type: string
                      example: "Développement de la pratique"
                    description:
                      title: Description détaillée du projet
                      type: string
                      example: Depuis plusieurs années nous intervenons auprès [...]
                    aide:
                      title: Description de l'aide
                      description: TODO
                      type: object
                      properties:
                        nature:
                          title: Type d'aide
                          type: string
                          example: "Projets sportifs territoriaux"
                        modalite:
                          title: Modalité d'aide
                          type: string
                          example: "Aide au projet"
                    modalite_ou_dispositif:
                      title: Modalité ou dispositif
                      type: string
                      example: "Développer la pratique féminine"
                    indicateurs:
                      title: Indicateurs de performance
                      type: string
                      nullable: true
                    cofinanceurs:
                      title: Co-financeurs
                      description: Co-financeurs séparés par ';'
                      type: string
                      example: "Conseil départemental du Nord;Ville de Lille;Fédération française d'aviron - Hauts-de-France"
          instruction:
            title: Informations et résultats de l'instruction de la demande
            type: object
            properties:
              service_instructeur:
                title: Code du service instructeur
                description: TODO
                type: string
                example: "DD59"
              date_commission:
                title: Date de commission
                description: Date à laquelle la commission d'instruction a eu lieu.
                type: string
                format: date-time
                nullable: true
                example: "2019-06-15T00:00:00.000Z"
              statut_demande:
                title: Statut de la demande
                description: Statut de la demande accordé par le service instructeur.
                type: string
                enum: ["Accordé", "En instruction", "Refusé", "En attente"]
                example: "Accordé"
              montant_accorde:
                title: Montant accordé à l'association
                description: Montant en euros de la subvention accordée à l'association.
                type: number
                example: 1800
      paiements:
        title: Liste des paiements effectués
        type: array
        items:
          title: Informations du paiement effectué
          type: object
          properties:
            fournisseur:
              title: Fournisseur distribuant la donnée à Data Subvention
              description: Origine de la donnée transmise, il s'agit toujours de Chorus. 
              type: string
              example: "Chorus"
            date_mise_a_jour_information:
              title: Date de dernière mise à jour
              description: Date de dernière mise à jour des informations. Les données de Chorus sont mises à jour tous les lundis.
              type: string
              format: date-time
              example: "2021-03-15T00:00:00.000Z"
            jointure_demandes_et_versements: 
              title: Identifiant de jointure entre demande et versement
              description: "Identifiant créé par DataSubvention pour faire le lien entre un paiement figurant dans cette liste et une demande figurant dans la liste précédente."
              type: string
              nullable: true
              example: "19/0003456"
            montant_verse:
              title: Montant versé
              description: Montant en euros qui a été versé à l'association.
              type: number
              example: 1250
            date_versement:
              title: Date de versement
              description: Date du versement à l'association.
              type: string
              format: date-time
              example: "2021-03-15T00:00:00.000Z"
            centre_financier:
              title: Nom du centre financier
              description: Centre ayant effectué le versement de la subvention. Il ne s'agit pas forcément de celui qui donne la subvention.
              type: string
              example: "UO Region BFC-FC"
            domaine_fonctionnel:
              title: Domaine fonctionnel
              type: string
              example: "sport handicap"
            activitee:
              title: Type d'activité
              type: string
              example: "handisport"
            numero_bop:
              title: Numéro BOP
              type: string
              example: "219"
            programme:
              title: Informations sur le programme budgétaire
              description: Informations sur le programme budgétaire auquel est rattaché le versement. Ces informations ne proviennent pas de Chorus.
              type: object
              properties:
                numero:
                  title: Numéro de programme
                  type: string
                  example: "219"
                libelle:
                  title: Nom du programme
                  type: string
                  example: "Sport"
                fournisseur:
                  title: Fournisseur distribuant la donnée à Data Subvention
                  description: Origine de la donnée transmise (OSIRIS, Chorus, etc.)
                  type: string
                  example: "OSIRIS"
                date_mise_a_jour_information:
                  title: Date de dernière mise à jour
                  description: Date de dernière mise à jour des informations. La fréquence d'actualisation des données varie selon le fournisseur, elle est décrite dans la fiche métier de l'API.
                  type: string
                  format: date-time
                  example: "2019-01-01T00:00:00.000Z"
