dgddi:
  eori:
    title: "Immatriculation EORI"
    description: |
      État du numéro EORI d'une entreprise indiquant si celle-ci est immatriculée auprès des douanes dans le cadre de l’import/export en Union Européenne.
    tags:
      - "Informations générales"
    attributes:
      id:
        title: "Identifiant EORI"
        description: "Numéro EORI (Economic Operator Registration and Identification) de l'entité: un numéro unique communautaire permettant d’identifier chaque opérateur économique dans ses relations avec les autorités douanières."
        type: "string"
        example: "FR16002307300010"
      actif:
        title: "Actif"
        type: "boolean"
        description: "Indique si ce numéro est encore actif (true) ou non (false)"
        example: true
      code_pays:
        title: "Code Pays"
        type: "string"
        example: "FR"
      code_postal:
        title: "Code Postal"
        type: "string"
        example: "95520"
      libelle:
        title: "Libellé de l'entité"
        type: "string"
        description: "Libellé de l'entreprise tel que connu par les douanes, équivalent à la Raison Sociale pour une entreprise Française."
        example: "CENTRE INFORMATIQUE DOUANIER"
      pays:
        title: "Pays"
        type: "string"
        description: "Pays de résidence de l'établissement telle que connue par les douanes"
        example: "FRANCE"
      rue:
        title: "Rue"
        type: "string"
        description: "Rue de l'établissement telle que connue par les douanes"
        example: "27 R DES BEAUX SOLEILS"
      ville:
        title: "Ville"
        type: "string"
        description: "Ville de l'établissement telle que connue par les douanes"
        example: "OSNY"
