dgfip:
  attestations_fiscales:
    title: "Attestation fiscale"
    description: "Obtenir l’attestation fiscale, délivrée par la Direction générale des finances publiques, indiquant que l’entreprise est à jour de ses obligations fiscales."
    tags:
      - "Attestations sociales et fiscales"
    document_url_properties:
      title: "URL de téléchargement de l'attestation fiscale (.pdf)"
      description: "Ce lien donne accès à l'attestation fiscale, au format PDF. L'attestation, toujours datée du 31/12 de l’année précédente, atteste que l'entreprise est à jour de ses obligations fiscales jusqu'à cette date. 
      \n
      \n
      Par exemple, vous appelez l'API en mars 2022, l’attestation fiscale renvoyée indique que l’entreprise est à jour de ses obligations fiscales lui incombant au 31/12/2021.
      \n
      \n
      L’attestation fiscale est valide un an sur une année civile (jusqu’au 31/12/AAAA)."
      example: "https://storage.entreprise.api.gouv.fr/siade/1569139162-b99824d9c764aae19a862a0af-attestation_fiscale_dgfip.pdf"

  liasses_fiscales:
    declarations:
      title: "Liasses fiscales"
      description: "Obtenir les informations renseignées dans les liasses fiscales, issues des déclarations de résultat d’une entreprise auprès de la Direction générale des finances publiques (DGFIP)."
      tags:
        - "Informations financières"
      attributes: {}

  chiffres_affaires:
    title: "Chiffre d'affaires"
    description: "Obtenir les déclarations de chiffre d’affaires faites auprès de la Direction générale des finances publiques (DGFIP), et renseignées dans la liasse fiscale."
    tags:
      - "Informations financières"
    items:
      properties:
        chiffre_affaires:
          type: "number"
          example: 900_001
          description: "Chiffre d'affaires en euros de l'établissement sur la période"
        date_fin_exercice:
          type: "string"
          example: "2015-12-01"
          description: "Date de fin de l'exercice"
