dsnj:
  service_national:
    title: 'API Service National'
    tags:
      - "Statut Service National"
    description: Statut de conformité au service national des jeunes entre 16 et 25 ans
    attributes:
      statut_service_national:
        title: Statut service national
        type: string
        description: Indique si la personne est en règle de ses obligations de service national. "en_regle" si la personne est en règle, "pas_en_regle" si la personne n'est pas en règle, "indetermine" si l'information n'est pas connue, "non_concerne" si la personne n'est pas concernée par les obligations de service national.
        example: en_regle
        enum:
          - en_regle
          - pas_en_regle
          - indetermine
          - non_concerne
      commentaires:
        title: Commentaires
        type: string
        description: Commentaires sur la situation de la personne
        example: Commentaire sur la situation
        nullable: true
