fabrique_numerique_ministeres_sociaux:
  conventions_collectives:
    title: "Conventions collectives"
    description: "Identifiants des conventions collectives d’un établissement et lien vers les textes en vigueur."
    tags:
      - "Informations générales"
    attributes:
      type:
        title: 'Convention collective'
        type: 'string'
        example: 'convention_collective'
        enum:
          - 'convention_collective'
      titre:
        type: 'string'
        description: "Titre historique de la convention collective"
        example: "Convention collective nationale des bureaux d'études techniques, des cabinets d'ingénieurs-conseils et des sociétés de conseils du 15 décembre 1987."
      titre_court:
        type: 'string'
        description: "Titre abrégé / d'usage"
        example: "Bureaux d'études techniques, cabinets d'ingénieurs-conseils et sociétés de conseils"
      numero_idcc:
        type: 'number'
        description: "Numéro IDCC"
        example: 1486
      active:
        type: 'boolean'
        description: "Détermine si la convention est toujours active"
        example: true
      etat:
        type: 'string'
        enum:
          - 'vigueur'
          - 'vigueur_etendue'
        description: "État de la convention. Si celle-ci est en vigueur elle est seulement obligatoire pour les signataires. Si celle-ci est en vigueur étendue, elle est obligatoire pour tous les employeurs de la branche."
        example: 'vigueur_etendue'
      synonymes:
        type: 'array'
        description: "Liste de synonymes connus de la convention"
        items:
          type: 'string'
        example:
          - 'syntec'
      url:
        type: 'string'
        description: "Lien vers le texte en vigueur de la convention collective sur Legifrance"
        example: 'https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635173'
      date_publication:
        type: 'string'
        description: 'Date de la dernière mise à jour de la convention'
        example: '1988-01-01'
    meta:
      internal_id:
        type: 'string'
        description: "Identifiant interne (DILA) de la convention"
        example: 'KALICONT000005635173'
