fntp:
  carte_professionnelle_travaux_publics:
    title: "Carte professionnelle de travaux publics"
    description: "Récupérer la carte professionnelle d’entrepreneur de travaux publics, délivrée à une entreprise de travaux publics en règle de ses obligations sociales, administratives et juridiques."
    tags:
      - "Attestations sociales et fiscales"
    document_url_properties:
      title: "Lien vers la carte professionnelle"
      description: "Ce document est automatiquement supprimé au bout de 3 mois."
      example: "https://storage.entreprise.api.gouv.fr/siade/1569139162-b99824d9c764aae19a862a0af-carte_professionnelle_fntp.pdf"
