france_travail:
  commons:
    parameters:
      identifiant:
        required: true
        description: Identifiant France Travail choisi par le particulier lors de la création de son espace personnel en ligne.
        type: string
        example: 'jean.dupont33'


  statut:
    title: Statut demandeur d'emploi
    description: |
        Statut demandeur d'emploi, données relatives à l'inscription FranceTravail, ainsi que données d'identité de contact.
        **Paramètres d'appel :** Nom d’utilisateur France Travail choisi par le particulier lors de la création de son espace personnel en ligne
        **Données disponibles en bac à sable :** [liste](https://github.com/datagouv/apistration/blob/develop/mocks/payloads/api_particulier_v2_pole_emploi_statut)

    tags:
      - Statut demandeurs d'emploi
    attributes:
      identifiant:
        title: Identifiant France Travail
        type: string
        description: |
          Identifiant du compte utilisateur France Travail, tel qu'il a été renseigné
          en paramètre d'appel. Cet identifiant est le nom d'utilisateur
          tel que choisi par le particulier lors de la création de son
          espace personnel en ligne.
        example: martin.jacques
      identite:
        title: Données d'identité de l'utilisateur France Travail
        description : "Les informations d'identité retournées ici sont issues de l'espace FranceTravail où l'utilisateur les a saisies. Elles sont vérifiées par un agent, à l'aide de la pièce d'identité fournie, et corrigées le cas échéant. Les justificatifs d'identité qui servent à la vérification des données sont listés ici : https://www.service-public.fr/particuliers/vosdroits/F24465"
        type: object
        properties:
          civilite:
            title: Civilité
            description: Civilité, Madame ou Monsieur.
            type: string
            example: M.
            enum:
            - MME
            - M.
          nom_naissance:
            title: Nom de naissance
            type: string
            description: Nom de naissance.
            example: MARTIN
          nom_usage:
            title: Nom d'usage
            type: string
            description: Nom d'usage.
            nullable: true
            example:
          prenom:
            title: Prénom
            type: string
            example: JACQUES
            description: Prénom, limité à 13 caractères.
          sexe:
            title: Sexe
            type: string
            description: Sexe.
            example: Masculin
          date_naissance:
            title: Date de naissance
            format: date
            type: string
            description: Date de naissance au format YYYY-MM-DD.
            example: 1995-02-02
      contact:
        title: Données de contact
        description: Données de contact de l'utilisateur France Travail
        type: object
        properties: 
          telephone:
            title: Téléphone principal
            type: string
            description: Numéro de téléphone principal.
            example: '0636676767'
          telephone2:
            title: Téléphone secondaire
            type: string
            description: Numéro de téléphone secondaire.
            nullable: true
            example: '1122334455'
          email:
            title: E-mail
            type: string
            nullable: true
            description: Adresse e-mail.
            example: martin.jacques@france.fr
      adresse:
        title: Adresse
        type: object
        description: Adresse déclarée par le particulier lors de son inscription à France Travail ou suite à une déclaration de changement d’adresse.
        properties:
          code_postal:
            type: string
            title: Code postal
            example: '75001'
          code_cog_insee_commune:
            title: COG de la commune
            description: "Code officiel géographique (COG) de la commune"
            type: string
            example: '75101'
          localite:
            title: Localité (Code postal et nom de la commune)
            type: string
            example: 75001 Paris
          ligne_voie:
            title: Voie
            type: string
            example: 21 RUE DES MARMOTS
          ligne_complement_destinataire:
            title: Complément destinataire
            type: string
            nullable: true
            example: Appartement 42
          ligne_complement_adresse:
            title: Complément d'adresse
            type: string
            nullable: true
            example:
          ligne_complement_distribution:
            title: Complément distribution
            type: string
            nullable: true
          ligne_nom:
            title: Nom du destinataire
            type: string
            example: MARTIN
      inscription:
        title: Inscription FranceTravail
        description: Données relatives à l'inscription de l'utilisateur à France Travail.
        type: object
        properties:
          date_debut:
            title: Date d'inscription
            format: date
            type: string
            description: Date d'inscription à France Travail au format YYYY-MM-DD.
            example: 2021-01-07
          date_fin:
            title: Date de cessation d'inscription
            description: Date de cessation d'inscription à France Travail au format YYYY-MM-DD.
            type: string
            format: date
            nullable: true
            example: 2023-03-12
          categorie:
            title: Catégorie d'inscription
            description: |+
              Catégorie de l'inscription de l'utilisateur à France Travail. La liste des catégories possibles est la suivante : 
                - 1 : PERSONNE SANS EMPLOI DISPONIBLE DUREE INDETERMINEE PLEIN TPS
                - 2 : PERSONNE SANS EMPLOI DISPONIBLE DUREE INDETERMINEE PARTIEL
                - 3 : PERSONNE SANS EMPLOI DISPONIBLE DUREE DETERMINEE OU SAISON
                - 4 : PERSONNE SANS EMPLOI NON DISPONIBLE IMMEDIATEMENT
                - 5 : PERSONNE POURVUE D'UN EMPLOI A LA RECHERCHE D'UN AUTRE
            type: object
            properties:
              code:
                title: Code
                description: |
                  Code de la catégorie d'inscription du particulier à France Travail.
                type: integer
                example: 1
                enum:
                - 1
                - 2
                - 3
                - 4
                - 5
              libelle:
                title: Libellé
                description: Libellé de la catégorie d'inscription du particulier à France Travail.
                type: string
                example: PERSONNE SANS EMPLOI DISPONIBLE DUREE INDETERMINEE PLEIN
                  TPS
                enum:
                - PERSONNE SANS EMPLOI DISPONIBLE DUREE INDETERMINEE PLEIN TPS
                - PERSONNE SANS EMPLOI DISPONIBLE DUREE INDETERMINEE PARTIEL
                - PERSONNE SANS EMPLOI DISPONIBLE DUREE DETERMINEE OU SAISON
                - PERSONNE SANS EMPLOI NON DISPONIBLE IMMEDIATEMENT
                - PERSONNE POURVUE D'UN EMPLOI A LA RECHERCHE D'UN AUTRE
          code_certification_cnav:
            title: Code du statut de certification d'identité CNAV
            type: string
            description: |
              France Travail dépend d'un flux de certification d'identité émis par la CNAV, un particulier peut avoir été
              certifié ou non. La signification des codes est la suivante :
                - VC IDENTITE CERTIFIEE
                - IC : IDENTITE ASSIMILEE CERTIFIEE
                - PC : IDENTITE CERTIFIEE PARTIELLEMENT
              Sont considérés comme non-certifiés :
                - AC : ATTENTE TRAITEMENT RETOUR CNAV
                - DC : DEMANDE CERTIF. ENVOYEE
                - EC : ECHEC DE CERTIFICATION CNAV
                - RC : REFUS PROPOSITION DE CERTIFICATION
                - null : IDENTITE NON CERTIFIEE
            example: VC
            enum:
            - VC
            - IC
            - PC
            - AC
            - DC
            - RC
            - null

  indemnites:
    title: "Paiements versés par France Travail"
    description: "Ensemble des paiements versés par France Travail au particulier"
    tags:
      - Paiements versés par France Travail
    parameters:
      identifiant:
        required: true
        description: Identifiant France Travail choisi par le particulier lors de la création de son espace personnel en ligne.
        type: string
        example: 'jean.dupont33'
    attributes:
      identifiant:
        title: Nom d'utilisateur France Travail
        type: string
        description: Identifiant du compte utilisateur France Travail, tel qu'il a été renseigné en paramètre d'appel. Cet identifiant est le nom d'utilisateur
          tel que choisi par le particulier lors de la création de son
          espace personnel en ligne.
        example: 'jean.dupont33'
      paiements:
        title: "Liste des paiements versés"
        description: "Liste des paiements versés par FranceTravail au particulier."
        type: array
        minItems: 1
        items:
          title: "Paiement"
          type: object
          properties:
            date_versement:
              title: Date du paiement
              type: string
              example: '2021-01-01'
            montant_total:
              title: Montant total versé
              description: Montant total du paiement. Il s'agit de la somme des allocations, aides et autres paiements, moins le prélèvement de l'impôt à la source.
              type: number
              example: 123.4
            montant_allocations:
              title: Montant d'allocations
              description: Montant du paiement, avant prélèvement de l'impôt à la source, correspondant aux allocations (allocation d'aide au retour à l'emploi, allocation de sécurisation professionnelle, allocation de solidarité spécifique, allocation pour les travailleurs indépendants, Rémunération de formation France Travail, Rémunération de fin de formation, allocation de fin de droit, allocation d'accompagnement personnalisé, allocation de professionnalisation et de solidarité, allocation décès, allocation contrat engagement jeune).
              type: number
              example: 45.1
            montant_aides:
              title: Montant d'aides
              description: Montant du paiement, avant prélèvement de l'impôt à la source, correspondant aux aides (aide à la reprise et à la création d’entreprise, aide à la mobilité, aide à la garde d'enfant pour parent isolé, aide fin de droit, aide aux congés non payés, aide à la valorisation des acquis par l'expérience, aide du fond de sécurisation du secteur automobile, aide ponctuelle jeune, aide régionale, aide aux demandeurs d'emploi longue durée, aide exceptionnelle de solidarité, Prime de reclassement).
              type: number
              example: 12.21
            montant_autres:
              title: Montant des autres paiements
              description: Montant du paiement, avant prélèvement de l'impôt à la source, correspondant aux autres paiements (prime de Noël, indemnité différentielle de reclassement, acompte, avance, reversement).
              type: number
              example: 2.34

