gip_mds:
  effectifs_annuels_entreprise:
    title: "Effectifs annuels d'une unité légale"
    tags:
      - "Informations générales"
    description: "Effectifs annuels des régimes général et agricole d'une unité légale, issus du répertoire commun des déclarants (RCD), dont l'effectif moyen (EMA) ou les effectifs liés à l'obligation travailleurs handicapés (EMA BOETH, EMA OETH, EMA ECAP)."
    parameters:
      nature_effectif:
        description: "Indique la nature de l'effectif transmis. Si ce paramètre n'est pas complété en appel, l'effectif moyen annuel (EMA) sera renvoyé par défaut. L'API permet d'accéder à 4 natures d'effectif :
           \n
           - Effectif moyen annuel (EMA), c'est-à-dire le nombre de salariés en contrat "actif"  hors exclusions. Ces exclusions sont décrites dans la documentation.
           \n
           - Effectif BOETH annuel (EMA BOTEH), c'est-à-dire le nombre de salariés de l'entreprise (salariés, stagiaires et PMSMP) qui sont bénéficiaires de l'obligation d’emploi des travailleurs handicapés (BOETH). Ce statut recouvre plusieurs situations décrites dans la documentation.
           \n
           - Effectif ECAP annuel (EMA ECAP), c'est-à-dire le nombre de salariés de l'entreprise occupant un emploi qui, de par ses exigences en matière d'aptitude, rend difficile un recrutement de travailleurs handicapés. Cet effectif « emplois exigeant des conditions d’aptitudes particulières » (ECAP) est utilisé par l'URSSAF pour calculer une réduction de la contribution employeur si l'entreprise n'emploie pas assez de travailleurs handicapés.
           \n
           - Effectif d'assujettissement OETH annuel (EMA OETH), c'est-à-dire le nombre de salariés en contrat "actif", hors exclusions, différentes de celles de l'effectif moyen mensuel (EMM). Cet effectif est utilisé par l'URSSAF pour calculer le niveau d'obligation d'emploi de travailleurs handicapés de l'entreprise."
        schema:
          type: 'string'
          default: 'moyen'
          enum:
            - 'moyen'
            - 'boeth'
            - 'ecap'
            - 'assujettissement_oeth'
    attributes:
      siren:
        title: "Siren de l'unité légale"
        type: "string"
        example: "130025265"
      annee:
        title: "Année de référence"
        type: "string"
        example: "2017"
      effectifs_annuel:
        title: "Effectif annuel de l'établissement"
        type: "array"
        items:
          type: 'object'
          additionalProperties: false
          required:
            - regime
            - nature
            - value
            - date_derniere_mise_a_jour
          properties:
            regime:
              title: "Type de régime"
              type: "string"
              example: "regime_general"
              enum:
                - 'regime_general'
                - 'regime_agricole'
            value:
              title: "Valeur de l'effectif"
              description: "Valeur de l'effectif annuel. Cette valeur est à null s'il n'y a pas d'effectif dans le régime."
              type: "number"
              example: 12.34
              nullable: true
            nature:
              title: "Nature de l'effectif"
              description: "Indique la nature de l'effectif transmis. Quatre natures d'effectif sont renvoyées par l'API :
           \n
           - Effectif moyen annuel (EMA), c'est-à-dire le nombre de salariés en contrat "actif"  hors exclusions. Ces exclusions sont décrites dans la documentation.
           \n
           - Effectif BOETH annuel (EMA BOTEH), c'est-à-dire le nombre de salariés de l'entreprise (salariés, stagiaires et PMSMP) qui sont bénéficiaires de l'obligation d’emploi des travailleurs handicapés (BOETH). Ce statut recouvre plusieurs situations décrites dans la documentation.
           \n
           - Effectif ECAP annuel (EMA ECAP), c'est-à-dire le nombre de salariés de l'entreprise occupant un emploi qui, de par ses exigences en matière d'aptitude, rend difficile un recrutement de travailleurs handicapés. Cet effectif « emplois exigeant des conditions d’aptitudes particulières » (ECAP) est utilisé par l'URSSAF pour calculer une réduction de la contribution employeur si l'entreprise n'emploie pas assez de travailleurs handicapés.
           \n
           - Effectif d'assujettissement OETH annuel (EMA OETH), c'est-à-dire le nombre de salariés en contrat "actif", hors exclusions, différentes de celles de l'effectif moyen mensuel (EMM). Cet effectif est utilisé par l'URSSAF pour calculer le niveau d'obligation d'emploi de travailleurs handicapés de l'entreprise."
              type: "string"
              enum:
                - 'effectif_moyen_annuel'
                - 'effectif_boeth_annuel'
                - 'effectif_ecap_annuel'
                - 'effectif_assujettissement_oeth_annuel'
            date_derniere_mise_a_jour:
              title: "Date de la dernière mise à jour de la donnée"
              type: "string"
              example: "2018-01-01"
              nullable: true
  effectifs_mensuels_etablissement:
    title: "Effectifs mensuels d'un établissement"
    tags:
      - "Informations générales"
    description: "Effectifs mensuels des régimes général et agricole d'un établissement, issus du répertoire commun des déclarants (RCD), dont l'effectif moyen (EMM) ou les effectifs liés à l'obligation travailleurs handicapés (EMM BOETH, EMM OETH, EMM ECAP)."
    parameters:
      profondeur:
        description: "Nombre de mois à remonter dans le temps. Par défaut cette valeur est à 0, ce renvoi le mois en cours. Il n'est pas possible de remonter à plus de 13 mois."
        schema:
          type: 'integer'
          default: 0
          minimum: 0
          maximum: 12
      nature_effectif:
        description: "Indique la nature de l'effectif transmis. Si ce paramètre n'est pas complété en appel, l'effectif moyen mensuel (EMM) sera renvoyé par défaut. L'API permet d'accéder à 4 natures d'effectif :
           \n
           - Effectif moyen mensuel (EMM), c'est-à-dire le nombre de salariés en contrat "actif"  hors exclusions. Ces exclusions sont décrites dans la documentation.
           \n
           - Effectif BOETH mensuel (EMM BOTEH), c'est-à-dire le nombre de salariés de l'entreprise (salariés, stagiaires et PMSMP) qui sont bénéficiaires de l'obligation d’emploi des travailleurs handicapés (BOETH). Ce statut recouvre plusieurs situations décrites dans la documentation.
           \n
           - Effectif ECAP mensuel (EMM ECAP), c'est-à-dire le nombre de salariés de l'entreprise occupant un emploi qui, de par ses exigences en matière d'aptitude, rend difficile un recrutement de travailleurs handicapés. Cet effectif « emplois exigeant des conditions d’aptitudes particulières » (ECAP) est utilisé par l'URSSAF pour calculer une réduction de la contribution employeur si l'entreprise n'emploie pas assez de travailleurs handicapés.
           \n
           - Effectif d'assujettissement OETH mensuel (EMM OETH), c'est-à-dire le nombre de salariés en contrat "actif", hors exclusions, différentes de celles de l'effectif moyen mensuel (EMM). Cet effectif est utilisé par l'URSSAF pour calculer le niveau d'obligation d'emploi de travailleurs handicapés de l'entreprise."
        schema:
          type: 'string'
          default: 'moyen'
          enum:
            - 'moyen'
            - 'boeth'
            - 'ecap'
            - 'assujettissement_oeth'
    attributes:
      siret:
        title: "Siret de l'établissement"
        type: "string"
        example: "13002526500013"
      effectifs_mensuels:
        title: "Effectif mensuels de l'établissement"
        type: "array"
        items:
          type: 'object'
          additionalProperties: false
          required:
            - regime
            - annee
            - nature
            - mois
            - value
            - date_derniere_mise_a_jour
          properties:
            regime:
              title: "Type de régime"
              type: "string"
              example: "regime_general"
              enum:
                - 'regime_general'
                - 'regime_agricole'
            value:
              title: "Valeur de l'effectif"
              description: "Valeur de l'effectif mensuel. Cette valeur est à null s'il n'y a pas d'effectif dans le régime."
              type: "number"
              example: 12.34
              nullable: true
            nature:
              title: "Nature de l'effectif"
              description: "Indique la nature de l'effectif transmis. Quatre natures d'effectif sont renvoyées par l'API : 
                 \n
                 - Effectif moyen mensuel (EMM), c'est-à-dire le nombre de salariés en contrat "actif"  hors exclusions. Ces exclusions sont décrites dans la documentation.
                 \n
                 - Effectif BOETH mensuel (EMM BOTEH), c'est-à-dire le nombre de salariés de l'entreprise (salariés, stagiaires et PMSMP) qui sont bénéficiaires de l'obligation d’emploi des travailleurs handicapés (BOETH). Ce statut recouvre plusieurs situations décrites dans la documentation.
                 \n
                 - Effectif ECAP mensuel (EMM ECAP), c'est-à-dire le nombre de salariés de l'entreprise occupant un emploi qui, de par ses exigences en matière d'aptitude, rend difficile un recrutement de travailleurs handicapés. Cet effectif « emplois exigeant des conditions d’aptitudes particulières » (ECAP)  est utilisé par l'URSSAF pour calculer une réduction de la contribution employeur si l'entreprise n'emploie pas assez de travailleurs handicapés.
                 \n
                 - Effectif d'assujettissement OETH mensuel (EMM OETH), c'est-à-dire le nombre de salariés en contrat "actif", hors exclusions, différentes de celles de l'effectif moyen mensuel (EMM). Cet effectif est utilisé par l'URSSAF pour calculer le niveau d'obligation d'emploi de travailleurs handicapés de l'entreprise."
              type: "string"
              enum:
                - 'effectif_moyen_mensuel'
                - 'effectif_boeth_mensuel'
                - 'effectif_ecap_mensuel'
                - 'effectif_assujettissement_oeth_mensuel'
            annee:
              title: "Année de l'effectif"
              type: "string"
              maxLength: 4
              minLength: 4
              example: "2021"
            mois:
              title: "Mois de l'effectif"
              type: "string"
              example: "01"
              maxLength: 2
              minLength: 2
              enum:
                - '01'
                - '02'
                - '03'
                - '04'
                - '05'
                - '06'
                - '07'
                - '08'
                - '09'
                - '10'
                - '11'
                - '12'
            date_derniere_mise_a_jour:
              title: "Date de la dernière mise à jour de la donnée"
              type: "string"
              example: "2018-01-01"
              nullable: true
