infogreffe:
  mandataires_sociaux:
    title: "Mandataires sociaux"
    description: "Liste des mandataires sociaux d'une société inscrites au RCS."
    tags:
      - "Informations générales"
    type: "array"
    example:
      data:
        - id: GAUQUELIN-ARNAUD-1969-08-24
          type: personne_physique
          attributes:
            id: GAUQUELIN-ARNAUD-1969-08-24
            fonction: PRESIDENT
            nom: GAUQUELIN
            prenom: ARNAUD
            date_naissance: '1969-08-24'
            date_naissance_timestamp: -11235600
            lieu_naissance: FLERS
            pays_naissance: FRANCE
            code_pays_naissance: FR
            nationalite: FRANCAISE
            code_nationalite: FR
        - id: '784824153'
          type: personne_morale
          attributes:
            id: '784824153'
            fonction: COMMISSAIRE AUX COMPTES TITULAIRE
            raison_sociale: MAZARS - SOCIETE ANONYME A DIRECTOIRE ET CONSEIL DE SURVEILLANCE
            code_greffe: '9201'
            libelle_greffe: NANTERRE
      meta:
        personnes_physiques_count: 3
        personnes_morales_count: 2
        count: 5
    items:
      properties:
        id:
          title: "Numéro d'identification"
          type: "string"
          example: "HENRI-MARTIN-1965-01-27"
        type:
          title: "Type de mandataire social"
          description: "Ce champ permet de faire la distinction entre les personnes physiques et morales"
          type: "string"
          example: "personne_morale"
          enum:
            - "personne_morale"
            - "personne_physique"
        attributes:
          type: "object"
          required: ["fonction"]
          additionalProperties: false
          properties:
            fonction:
              title: "Fonction au sein de l'entreprise"
              description: 'Information disponible pour les personnes morales et physiques'
              type: 'string'
              example: 'COMMISSAIRE AUX COMPTES SUPPLEANT'
            nom:
              title: 'Nom'
              description: 'Information disponible uniquement pour une personne physique'
              type: 'string'
              example: 'Henri'
              nullable: true
            prenom:
              title: 'Prénom'
              description: 'Information disponible uniquement pour une personne physique'
              type: 'string'
              example: 'Martin'
              nullable: true
            date_naissance:
              title: 'Date de naissance'
              description: 'Information disponible uniquement pour une personne physique'
              type: 'string'
              example: '1965-01-27'
              nullable: true
            date_naissance_timestamp:
              title: "Date de naissance (timestamp)"
              description: 'Information disponible uniquement pour une personne physique'
              type: "integer"
              example: -155_523_600
              nullable: true
            lieu_naissance:
              title: 'Lieu de naissance'
              description: 'Information disponible uniquement pour une personne physique'
              type: 'string'
              example: 'ROUBAIX'
              nullable: true
            pays_naissance:
              title: 'Pays de naissance'
              description: 'Information disponible uniquement pour une personne physique'
              type: 'string'
              example: 'FRANCE'
              nullable: true
            code_pays_naissance:
              title: "Code pays ISO 3166 Alpha 2"
              description: 'Information disponible uniquement pour une personne physique'
              type: "string"
              example: "FR"
              nullable: true
            nationalite:
              title: 'Nationalité de la personne physique'
              description: 'Information disponible uniquement pour une personne physique'
              type: 'string'
              example: 'FRANCAISE'
              nullable: true
            code_nationalite:
              title: "Code pays ISO 3166 Alpha 2"
              description: 'Information disponible uniquement pour une personne physique'
              type: "string"
              example: "FR"
              nullable: true
            raison_sociale:
              title: "Raison sociale"
              description: 'Information disponible uniquement pour une personne morale'
              type: "string"
              example: "BCRH & ASSOCIES - SOCIETE A RESPONSABILITE LIMITEE A ASSOCIE UNIQUE"
              nullable: true
            code_greffe:
              title: "Code du greffe de l'entreprise"
              description: 'Information disponible uniquement pour une personne morale. Tous les code greffe sont disponibles ici : https://opendata.datainfogreffe.fr/explore/dataset/liste-des-greffes/table/'
              type: "string"
              example: "9201"
              nullable: true
            libelle_greffe:
              title: "Libellé du greffe de l'entreprise (uniquement personne morales)"
              description: 'Information disponible uniquement pour une personne morale. Tous les libellés sont disponibles ici : https://opendata.datainfogreffe.fr/explore/dataset/liste-des-greffes/table/'
              type: "string"
              example: "NANTERRE"
              nullable: true
    meta:
      personnes_physiques_count:
        title: "Nombre de personnes physiques"
        description: "Nombre de personnes physiques parmis les mandataires sociaux"
        type: "integer"
        example: 10
      personnes_morales_count:
        title: "Nombre de personnes morales"
        description: "Nombre de personnes morales parmis les mandataires sociaux"
        type: "integer"
        example: 2
      count:
        title: "Nombre de mandataires sociaux"
        description: "Somme des personnes morales et physiques"
        type: "integer"
        example: 12
