infogreffe:
  mandataires_sociaux:
    title: "Mandataires sociaux"
    description: "Liste des mandataires sociaux d'une société inscrite au RCS, délivrée par Infogreffe."
    tags:
      - "Informations générales"
    type: "array"
    example:
      data:
        - id: GAUQUELIN-ARNAUD-1969-08-24
          type: personne_physique
          attributes:
            fonction: PRESIDENT
            nom: GAUQUELIN
            prenom: ARNAUD
            date_naissance: '1969-08-24'
            date_naissance_timestamp: -11235600
            lieu_naissance: FLERS
            pays_naissance: FRANCE
            code_pays_naissance: FR
            nationalite: FRANCAISE
            code_nationalite: FR
        - id: '784824153'
          type: personne_morale
          attributes:
            fonction: COMMISSAIRE AUX COMPTES TITULAIRE
            raison_sociale: MAZARS - SOCIETE ANONYME A DIRECTOIRE ET CONSEIL DE SURVEILLANCE
            code_greffe: '9201'
            libelle_greffe: NANTERRE
      meta:
        personnes_physiques_count: 1
        personnes_morales_count: 1
        count: 2
    items:
      required: ["fonction"]
      properties:
        id:
          title: "Numéro d'identification"
          type: "string"
          example: "HENRI-MARTIN-1965-01-27"
        type:
          title: "Type de mandataire social"
          description: "Ce champ permet de faire la distinction entre les personnes physiques et morales."
          type: "string"
          example: "personne_morale"
          enum:
            - "personne_morale"
            - "personne_physique"
        fonction:
          title: "Fonction au sein de l'entreprise"
          description: "Ce champ décrit la fonction du mandataire social au sein de l'entreprise. Cette information est disponible pour les personnes morales et physiques."
          type: 'string'
          example: 'COMMISSAIRE AUX COMPTES SUPPLEANT'
        nom:
          title: 'Nom'
          description: 'Nom du mandataire social. Ce champ est disponible uniquement pour une personne physique.'
          type: 'string'
          example: 'Henri'
          nullable: true
        prenom:
          title: 'Prénom'
          description: 'Prénom du mandataire social. Ce champ est disponible uniquement pour une personne physique.'
          type: 'string'
          example: 'Martin'
          nullable: true
        date_naissance:
          title: 'Date de naissance'
          description: 'Date de naissance du mandataire social. Ce champ est disponible uniquement pour une personne physique.'
          type: 'string'
          example: '1965-01-27'
          nullable: true
        date_naissance_timestamp:
          title: "Date de naissance (timestamp)"
          description: 'Date de naissance délivrée au format timestamp. Ce champ est disponible uniquement pour une personne physique.'
          type: "integer"
          example: -155_523_600
          nullable: true
        lieu_naissance:
          title: 'Lieu de naissance'
          description: 'Lieu de naissance du mandataire social. Ce champ est disponible uniquement pour une personne physique.'
          type: 'string'
          example: 'ROUBAIX'
          nullable: true
        pays_naissance:
          title: 'Pays de naissance'
          description: 'Pays de naissance du mandataire social. Ce champ est disponible uniquement pour une personne physique.'
          type: 'string'
          example: 'FRANCE'
          nullable: true
        code_pays_naissance:
          title: "Code pays ISO 3166 Alpha 2 du pays de naissance"
          description: 'Code à deux lettres indiquant le pays de naissance du mandataire social, suivant la norme ISO 3166 Alpha 2. Ce champ est disponible uniquement pour une personne physique.'
          type: "string"
          example: "FR"
          nullable: true
        nationalite:
          title: 'Nationalité de la personne physique'
          description: 'Nationalité du mandataire social. Ce champ est disponible uniquement pour une personne physique.'
          type: 'string'
          example: 'FRANCAISE'
          nullable: true
        code_nationalite:
          title: "Code pays ISO 3166 Alpha 2"
          description: 'Code à deux lettres indiquant le pays de nationalité du mandataire social, suivant la norme ISO 3166 Alpha 2. Ce champ est disponible uniquement pour une personne physique.'
          type: "string"
          example: "FR"
          nullable: true
        raison_sociale:
          title: "Raison sociale"
          description: 'Raison sociale de la personne morale mandataire social. Ce champ est disponible uniquement pour une personne morale.'
          type: "string"
          example: "BCRH & ASSOCIES - SOCIETE A RESPONSABILITE LIMITEE A ASSOCIE UNIQUE"
          nullable: true
        code_greffe:
          title: "Code du greffe de l'entreprise"
          description: 'Code du greffe auquel la personne morale mandataire social est rattachée. Ce champ est disponible uniquement pour une personne morale. Tous les codes greffe sont disponibles ici : https://opendata.datainfogreffe.fr/explore/dataset/liste-des-greffes/table/'
          type: "string"
          example: "9201"
          nullable: true
        libelle_greffe:
          title: "Libellé du greffe de l'entreprise"
          description: 'Nom du greffe auquel la personne morale mandataire social est rattachée. Ce champ est disponible uniquement pour une personne morale. Tous les libellés sont disponibles ici : https://opendata.datainfogreffe.fr/explore/dataset/liste-des-greffes/table/'
          type: "string"
          example: "NANTERRE"
          nullable: true
    meta:
      personnes_physiques_count:
        title: "Nombre de personnes physiques"
        description: "Nombre de personnes physiques parmi les mandataires sociaux."
        type: "integer"
        example: 10
      personnes_morales_count:
        title: "Nombre de personnes morales"
        description: "Nombre de personnes morales parmi les mandataires sociaux."
        type: "integer"
        example: 2
      count:
        title: "Nombre total de mandataires sociaux"
        description: "Somme des personnes morales et physiques"
        type: "integer"
        example: 12
