infogreffe:
  mandataires_sociaux:
    title: "Mandataires sociaux"
    description: "Liste des mandataires sociaux d'une société inscrite au RCS, délivrée par Infogreffe."
    tags:
      - "Informations générales"
    type: "array"
    example:
      data:
        - type: personne_physique
          fonction: PRESIDENT
          nom: GAUQUELIN
          prenom: ARNAUD
          date_naissance: '1969-08-24'
          date_naissance_timestamp: -11235600
          lieu_naissance: FLERS
          pays_naissance: FRANCE
          code_pays_naissance: FR
          nationalite: FRANCAISE
          code_nationalite: FR
        - numero_identification: '784824153'
          type: personne_morale
          fonction: COMMISSAIRE AUX COMPTES TITULAIRE
          raison_sociale: MAZARS - SOCIETE ANONYME A DIRECTOIRE ET CONSEIL DE SURVEILLANCE
          code_greffe: '9201'
          libelle_greffe: NANTERRE
      meta:
        personnes_physiques_count: 1
        personnes_morales_count: 1
        count: 2
    items:
      required: ["fonction"]
      properties:
        numero_identification:
          title: "Numéro d'identification"
          description: "Ce champ est uniquement disponible pour une personne morale."
          type: "string"
          example: "784824153"
        type:
          title: "Type de mandataire social"
          description: "Ce champ permet de faire la distinction entre les personnes physiques et morales."
          type: "string"
          example: "personne_morale"
          enum:
            - "personne_morale"
            - "personne_physique"
        fonction:
          title: "Fonction au sein de l'entreprise"
          description: "Ce champ décrit la fonction du mandataire social au sein de l'entreprise. Cette information est disponible pour les personnes morales et physiques."
          type: 'string'
          example: 'COMMISSAIRE AUX COMPTES SUPPLEANT'
        nom:
          title: 'Nom'
          description: 'Nom du mandataire social. Ce champ est disponible uniquement pour une personne physique.'
          type: 'string'
          example: 'Henri'
          nullable: true
        prenom:
          title: 'Prénom'
          description: 'Prénom du mandataire social. Ce champ est disponible uniquement pour une personne physique.'
          type: 'string'
          example: 'Martin'
          nullable: true
        date_naissance:
          title: 'Date de naissance'
          description: 'Date de naissance (Année et mois uniquement) du mandataire social. Ce champ est disponible uniquement pour une personne physique.'
          type: 'string'
          example: '1965-01'
          nullable: true
        raison_sociale:
          title: "Raison sociale"
          description: 'Raison sociale de la personne morale mandataire social. Ce champ est disponible uniquement pour une personne morale.'
          type: "string"
          example: "BCRH & ASSOCIES - SOCIETE A RESPONSABILITE LIMITEE A ASSOCIE UNIQUE"
          nullable: true
        code_greffe:
          title: "Code du greffe de l'entreprise"
          description: 'Code du greffe auquel la personne morale mandataire social est rattachée. Ce champ est disponible uniquement pour une personne morale. Tous les codes greffe sont disponibles ici : https://opendata.datainfogreffe.fr/explore/dataset/liste-des-greffes/table/'
          type: "string"
          example: "9201"
          nullable: true
        libelle_greffe:
          title: "Libellé du greffe de l'entreprise"
          description: 'Nom du greffe auquel la personne morale mandataire social est rattachée. Ce champ est disponible uniquement pour une personne morale. Tous les libellés sont disponibles ici : https://opendata.datainfogreffe.fr/explore/dataset/liste-des-greffes/table/'
          type: "string"
          example: "NANTERRE"
          nullable: true
    meta:
      personnes_physiques_count:
        title: "Nombre de personnes physiques"
        description: "Nombre de personnes physiques parmi les mandataires sociaux."
        type: "integer"
        example: 10
      personnes_morales_count:
        title: "Nombre de personnes morales"
        description: "Nombre de personnes morales parmi les mandataires sociaux."
        type: "integer"
        example: 2
      count:
        title: "Nombre total de mandataires sociaux"
        description: "Somme des personnes morales et physiques."
        type: "integer"
        example: 12
  extraits_rcs:
    title: "Extrait RCS"
    description: "Obtenir un extrait des données présentes dans le RCS, registre du commerce et des sociétés ; dont les observations qui permettent de savoir si une entreprise est en redressement judiciaire."
    tags:
      - "Informations générales"
    attributes:
      date_extrait:
        type: 'string'
        title: "Date d'extrait"
        example: '1999-06-11'
      date_immatriculation:
        type: 'string'
        title: "Date d'immatriculation au RCS"
        description: "À compter de cette date, les sociétés jouissent de la personnalité morale. Cette date d'immatriculation n'est pas la même que celle délivrée par l'INSEE. Elle ne correspond pas non plus à la date du début d'activité."
        example: '1998-07-12'
      observations:
        type: array
        title: "Ensemble des observations du greffier"
        items:
          type: object
          required:
            - numero
            - libelle
            - date
          properties:
            numero:
              type: 'string'
              title: "Numéro de l'observation"
              example: '123456'
            libelle:
              type: 'string'
              title: "Libellé de l'observation"
              example: "LA SOCIETE NE CONSERVE AUCUNE ACTIVITE A SON ANCIEN SIEGE"
            date:
              type: 'string'
              title: "Date de l'observation"
              example: "2000-01-01"

