inpi:
  brevets:
    title: "Brevets déposés"
    description: |
      Nombre de brevets déposés par l'entreprise (lorsque le SIREN a été spécifié) et informations sur les brevets les plus récents.
    tags:
      - "Propriété intellectuelle"
    attributes:
      numero_publication:
        title: "Numéro de publication"
        description: "Numéro de publication du brevet, constitué du code zone + numéro du brevet + catégorie de publication"
        type: "string"
        example: "FR3110115A1"
      type:
        title: "Type de la ressource"
        type: "string"
        example: "brevet"
        enum:
          - 'brevet'
      titre:
        title: "Titre"
        description: "Titre du brevet"
        type: "string"
        example: "DETERMINATION DE PARAMETRES D&apos;UN MODELE DYNAMIQUE POUR UNE CELLULE ELECTROCHIMIQUE DE BATTERIE"
      date_publication:
        title: "Date de publication"
        description: "Date de publication du brevet"
        type: "string"
        format: "date"
        example: "2017-06-16"
      date_depot:
        title: "Date de dépot"
        description: "Date de dépot du brevet"
        type: "string"
        format: "date"
        example: "2015-12-14"
      code_zone:
        description: |
          Code de deux lettres représentant la zone géographique où le brevet a été déposé, en fonction
          de l'organisation qui a enregistré le brevet.
        type: "string"
        example: "FR"
        enum: <%= YAML.load_file(Rails.root.join('config/data/inpi/codes_zones.yml')).keys.concat([nil]).to_json %>
      numero_brevet:
        title: "Numéro du brevet"
        description: |
          Numéro du brevet dans l'organisation ou il a été déposé (déterminée par le code de zone)
        type: "string"
        example: "3110115"
      categorie_publication:
        title: "Catégorie"
        description: "Code représentant la catégorie du brevet (ex: A1 pour une demande de brevet,"
        type: "string"
        example: "A1"
    meta:
      count:
        title: "Nombre de brevets"
        description: "Nombre total des dépots de brevets effectués par l'entreprise."
        type: "number"
        example: 13161
  marques:
    title: "Marques déposées"
    description: |
      Nombre de marques déposées par l'entreprise (lorsque le SIREN a été spécifié) et informations sur les marques les plus récentes.
    tags:
      - "Propriété intellectuelle"
    attributes:
      numero_application:
        title: "Numéro d'identification"
        type: "string"
        example: "4313464"
      type:
        title: "Type de la ressource"
        type: "string"
        example: "marque"
        enum:
          - 'marque'
      nom:
        title: "Nom"
        type: "string"
        example: "DISTRIGO PARTS DISTRIBUTION"
        nullable: true
      status:
        title: "Statut"
        type: "string"
        example: "Marque enregistrée"
        enum:
          - "Demande déposée"
          - "Demande publiée"
          - "Demande non publiée"
          - "Demande irrecevable après publication"
          - "Marque enregistrée"
          - "Renouvellement demandé"
          - "Marque renouvelée"
          - "Demande totalement rejetée"
          - "Marque ayant fait l'objet d'une renonciation totale"
          - "Marque ayant fait l'objet d'un retrait total"
          - "Marque annulée"
          - "Marque expirée"
      depositaire:
        title: "Dépositaire"
        description: "Nom de déposant ou titulaire"
        type: "string"
        example: "PEUGEOT CITROËN AUTOMOBILES SA, Société anonyme"
      clef:
        title: "Clef"
        type: "string"
        example: "FMARK|4313464"
    links:
      notice:
        type: "string"
        example: "https://opendata-pi.inpi.fr/inpi/marques/notice/FR4313464"
        description: "Lien vers la notice concernant ce dépôt de marque, au format XML."
    meta:
      count:
        title: "Nombre de marques"
        description: "Nombre total des dépots de marques effectués par l'entreprise."
        type: "number"
        example: 13161
  modeles:
    title: "Modèles déposés"
    description: |
      Nombre de modèles déposés par l'entreprise (lorsque le SIREN a été spécifié) et informations sur les modèles les plus récents.
    tags:
      - "Propriété intellectuelle"
    attributes:
      document_id:
        title: 'Identifiant'
        description: "Identifiant du modèle dans la base de l'INPI, constitué du code de l'office de dépôt (ex: FR), du numéro national de dépôt (ex: 20203928) et du numéro de référence (ex: 001) "
        type: 'string'
        example: 'FR20203928-001'
      type:
        title: "Type de la ressource"
        type: "string"
        example: "modele"
        enum:
          - 'modele'
      numero_depot:
        title: "Numéro national de dépôt"
        description: "Numéro national sous lequel le modèle est enregistré."
        type: "string"
        example: "20203928"
      titre:
        title: "Titre"
        description: "Titre du modèle."
        type: "string"
        example: "Véhicule automobile, vues de détails"
      total_representations:
        title: "Représentations totales"
        description: "Nombre de représentations (vues) du modèle"
        type: "number"
        example: 7
      deposant:
        title: "Déposant"
        description: "Nom de l'entité ayant déposé le modèle."
        type: "string"
        example: "PSA AUTOMOBILES, SA"
      date_depot:
        title: "Date de dépôt"
        description: "Date à laquelle le modèle a été déposé pour publication"
        type: "string"
        example: "2015-12-14"
      date_publication:
        title: "Date de publication"
        description: "Date de publication du modèle"
        type: "string"
        example: "2015-12-14"
      classe:
        title: "Code de classification"
        description: "Code de classification du modèle, sur 4 chiffres"
        type: "string"
        example: "2606"
      reference:
        title: "Numéro de réference"
        description: "Numéro de référence du modèle par entité, sur trois chiffres. Le premier modèle d'une entité est numéroté 001, le second 002, etc."
        type: "string"
        example: "001"
    links:
      notice:
        type: "string"
        example: "https://opendata-pi.inpi.fr/inpi/modeles/notice/FR20203928?ref=006"
        description: "Lien vers la notice concernant ce dépôt de modèle, au format XML"
    meta:
      count:
        title: "Nombre de modèles"
        description: "Nombre total des dépots de marques effectués par l'entreprise."
        type: "number"
        example: 13161
