inpi_rne:
  beneficiaires_effectifs:
    title: "Bénéficiaires effectifs"
    description: "Liste des bénéficiaires effectifs d'une unité légale inscrite au répertoire national des entreprises (RNE)."
    tags:
      - "Informations générales"
    attributes:
      nom:
        title: "Nom du bénéficiaire effectif"
        type: "string"
        example: 'MARTIN'
      nom_usage:
        title: "Nom d'usage du bénéficiaire effectif"
        type: "string"
        example: 'DUBOIS'
        nullable: true
      prenoms:
        title: "Liste des prénoms du bénéficiaire effectif"
        type: 'array'
        example:
          - 'JEAN'
          - 'JACQUES'
        items:
          type: 'string'
      date_naissance:
        type: 'object'
        title: "Date de naissance du bénéficiaire effectif"
        additionalProperties: false
        properties:
          annee:
            title: "Année de la date de naissance"
            type: 'string'
            example: '1990'
          mois:
            title: "Mois de la date de naissance"
            type: 'string'
            example: '01'
            enum:
              - '01'
              - '02'
              - '03'
              - '04'
              - '05'
              - '06'
              - '07'
              - '08'
              - '09'
              - '10'
              - '11'
              - '12'
      modalites:
        title: "Liste des modalités et propriétées affectées au bénéficiaire effectif"
        type: 'object'
        additionalProperties: false
        properties:
          detention_parts_directes:
            title: "Indique si le bénéficiaire détient des parts directes"
            description: "Détermine si le bénéficiaire possède du capital direct (parts sociales ou actions) de l'unité légale appelée. Par opposition à une détention indirecte du capital, via une personne morale."
            type: 'boolean'
            example: true
          # detention_parts_directes_rdd:
          #   title: "FIXME Detention part directe rdd"
          #   type: 'number'
          #   example: 51.0
          parts_directes_pleine_propriete:
            title: "Répartition des parts directes de pleine propriété"
            description: &description_differents_droits "Plus d'infos sur les différents des droits sur un bien sur le lien suivant: <a href=\"https://www.service-public.fr/particuliers/vosdroits/F33076\">Usufruit, nue-propriété, pleine propriété : quelles différences ?</a>"
            type: 'number'
            example: 42.0
          parts_directes_nue_propriete:
            title: "Répartition des parts directes en nue-propriété"
            description: *description_differents_droits
            type: 'number'
            example: 9.0
          detention_parts_indirectes:
            title: "Indique si le bénéficiaire détient des parts indirectes"
            description: "Détermine si le bénéficiaire possède du capital (parts sociales ou actions) de manière indirecte sur l'unité légale, c'est-à-dire via une personne morale."
            type: 'boolean'
            example: false
          # detention_parts_indirectes_rdd:
          #   title: "FIXME Detention part indirecte rdd"
          #   type: 'number'
          #   example: 0.0
          parts_indirectes_indivision:
            title: "Répartition des parts indirectes en indivision"
            description: &description_indivision "Après un décès, le patrimoine du défunt est en indivision, s’il y a plusieurs héritiers. Cela signifie que les biens de la succession appartiennent indistinctement à tous les héritiers sans que leurs parts respectives ne soient matériellement individualisées. Plus d'infos sur le lien suivant: <a href=\"https://www.economie.gouv.fr/particuliers/heritage-succession-indivision\">Succession : qu'est-ce que l'indivision ?</a>"
            type: 'number'
            example: 0.0
          parts_indirectes_indivision_pleine_propriete:
            title: "Répartition des parts indirectes en indivision de pleine propriété"
            description: *description_indivision
            type: 'number'
            example: 0.0
          parts_indirectes_indivision_nue_propriete:
            title: "Répartition des parts indirectes en indivision en nue-propriété"
            description: *description_indivision
            type: 'number'
            example: 0.0
          parts_indirectes_personnes_morales:
            title: "Répartition des parts indirectes via des personnes morales"
            type: 'number'
            example: 0.0
          parts_indirectes_personnes_morales_pleine_propriete:
            title: "Répartition des parts indirectes via des personnes morales, de pleine propriété"
            type: 'number'
            example: 0.0
          parts_indirectes_personnes_morales_nue_propriete:
            title: "Répartition des parts indirectes via des personnes morales en nue-propriété"
            type: 'number'
            example: 0.0
          detention_parts_totale:
            title: "Répartition totale des parts"
            description: "Somme des parts en direct et indirect associée au bénéficiaire effectif"
            type: 'number'
            example: 51.0
          detention_vote_directe:
            title: "Détention de droits de vote directe"
            description: "Les droits de vote directs sont en pleine et nue propriété"
            type: 'boolean'
            example: true
          # detention_vote_directe_rdd:
          #   title: "FIXME Detention vote directe rdd"
          #   type: 'number'
          #   example: 51.0
          vote_directe_pleine_propriete:
            title: "Répartition des droits de vote directes de pleine propriété"
            description: *description_differents_droits
            type: 'number'
            example: 51.0
          vote_directe_nue_propriete:
            title: "Répartition des droits de vote directes en nue-propriété"
            description: *description_differents_droits
            type: 'number'
            example: 0.0
          vote_directe_usufruit:
            title: "Répartition des droits de vote directes en usufruit"
            description: *description_differents_droits
            type: 'number'
            example: 0.0
          detention_vote_indirecte:
            title: "Détention de droits de vote indirectes"
            description: "Ces droits sont via des personnes morales"
            type: 'boolean'
            example: false
          # detention_vote_indirecte_rdd:
          #   title: "FIXME Detention vote indirecte rdd"
          #   type: 'number'
          #   example: 0.0
          vote_indirecte_indivision:
            title: "Répartition des droits de vote indirectes via indivision"
            description: *description_indivision
            type: 'number'
            example: 0.0
          vote_indirecte_indivision_pleine_propriete:
            title: "Répartition des droits de vote indirectes via indivision de pleine propriété"
            description: *description_differents_droits
            type: 'number'
            example: 0.0
          vote_indirecte_indivision_nue_propriete:
            title: "Répartition des droits de vote indirectes via indivision en nue-propriété"
            description: *description_differents_droits
            type: 'number'
            example: 0.0
          vote_indirecte_indivision_usufruit:
            title: "Répartition des droits de vote indirectes via indivision en usufruit"
            description: *description_differents_droits
            type: 'number'
            example: 0.0
          vote_indirecte_personnes_morales:
            title: "Répartition des droits de vote indirectes via des personnes morales"
            type: 'number'
            example: 0.0
          vote_indirecte_personnes_morales_pleine_propriete:
            title: "Répartition des droits de vote indirectes via des personnes morales de pleine propriété"
            type: 'number'
            example: 0.0
          vote_indirecte_personnes_morales_nue_propriete:
            title: "Répartition des droits de vote indirectes via des personnes morales en nue-propriété"
            type: 'number'
            example: 0.0
          vote_indirecte_personnes_morales_usufruit:
            title: "Répartition des droits de vote indirectes via des personnes morales en usufruit"
            type: 'number'
            example: 0.0
          # vocation_titulaire_directe_pleine_propriete_rdd:
          #   title: "Vocation par l'effet d’un acte juridique à devenir titulaire directe pleine propriété rdd"
          #   type: 'boolean'
          #   example: false
          vocation_titulaire_directe_pleine_propriete:
            title: "Vocation par l'effet d’un acte juridique à devenir titulaire de parts directes en pleine propriété"
            type: 'number'
            example: 0.0
          vocation_titulaire_directe_nue_propriete:
            title: "Vocation par l'effet d’un acte juridique à devenir titulaire de parts directes en nue-propriété"
            type: 'number'
            example: 0.0
          vocation_titulaire_indirecte_indivision:
            title: "Vocation par l'effet d’un acte juridique à devenir titulaire de parts indirectes en indivision"
            type: 'number'
            example: 0.0
          # vocation_titulaire_indirecte_pleine_propriete_rdd:
          #   title: "Vocation par l'effet d’un acte juridique à devenir titulaire indirecte pleine propriété rdd"
          #   type: 'boolean'
          #   example: false
          vocation_titulaire_indirecte_pleine_propriete:
            title: "Vocation par l'effet d’un acte juridique à devenir titulaire de parts indirectes en pleine propriété"
            type: 'number'
            example: 0.0
          vocation_titulaire_indirecte_nue_propriete:
            title: "Vocation par l'effet d’un acte juridique à devenir titulaire de parts indirectes nue-propriété"
            type: 'number'
            example: 0.0
          vocation_titulaire_indirecte_personnes_morales:
            title: "Vocation par l'effet d’un acte juridique à devenir titulaire de parts indirectes via des personnes morales"
            type: 'number'
            example: 0.0
          vocation_titulaire_indirecte_personnes_morales_pleine_propriete:
            title: "Vocation par l'effet d’un acte juridique à devenir titulaire de parts indirectes via des personnes morales en pleine propriété"
            type: 'number'
            example: 0.0
          vocation_titulaire_indirecte_personnes_morales_nue_propriete:
            title: "Vocation par l'effet d’un acte juridique à devenir titulaire de parts indirectes via des personnes morales en nue-propriété"
            type: 'number'
            example: 0.0
          detention_vote_total:
            title: "Détention de droits de  vote total"
            type: 'number'
            example: 0.0
          detention_pouvoir_decision_ag:
            title: "Indique si le bénéficiaire détient du pouvoir de décision en Assemblée Générale"
            type: 'boolean'
            example: false
          detention_pouvoir_nommage_membres_conseil_admin:
            title: "Indique si le bénéficiaire détient du pouvoir de nommage des membres du conseil d'administration"
            type: 'boolean'
            example: false
          detention_autres_moyens_controle:
            title: "Indique si le bénéficiaire détient d'autres moyens de contrôle"
            type: 'boolean'
            example: false
          representant_legal:
            title: "Indique si le bénéficiaire est représentant légal"
            type: 'boolean'
            example: false
          representant_legal_placement_sans_gestion_delegue:
            title: "Indique si le bénéficiaire est représentant légal en placement sans gestion délégué"
            type: 'boolean'
            example: false
    meta:
      count:
        title: "Nombre de bénéficiaires"
        type: 'integer'
        example: 1
