men:
  scolarite:
    title: "Statut élève scolarisé et boursier"
    description: "Statut scolarisé et statut boursier d'un élève du primaire, collège ou lycée."
    tags:
      - Scolarité étudiant
    parameters:
      nom:
        title: "Nom"
        description: "Nom de l'élève"
        type: string
        example: "Martin"
        required: true
      prenom:
        title: "Prénom"
        description: "Prénom de l'élève"
        type: string
        example: "Justine"
        required: true
      sexe:
        title: "Sexe"
        description: "Sexe de l'élève, masculin ou féminin"
        type: string
        enum:
          - "m"
          - "f"
        required: true
      date_naissance:
        title: "Date de naissance"
        description: "Date de naissance de l'élève au format AAAA-MM-JJ"
        type: string
        example: "2000-01-20"
        required: true
      code_etablissement: &code_etablissement
        title: "Code UAI de l'établissement"
        description: |+
          Code d'unité administrative immatriculée (code UAI) de l'établissement où est scolarisé l'élève. Ce code unique inscrit au répertoire national des établissements est composé de 7 chiffres et d'une lettre ; les trois premiers chiffres correspondent au numéro de département de l'établissement.

          Pour retrouver facilement le code UAI d'un établissement à partir d' informations plus facilement connues des usagers (commune, code postal, etc.), vous pouvez utiliser l'[API \"Annuaire de l'éducation nationale\" ](https://api.gouv.fr/les-api/api-annuaire-education).

          ⚠️ L'établissement 0861288H (CNED Direction générale) n'existe pas dans l'API annuaire de l'éducation nationale, il faudra donc compléter la liste des établissements avec une ligne CNED à laquelle sera associée le code UAI qui sera en passé en entrée.
        type: string
        pattern: '^\d{7}\w$'
        example: "0890003V"
      annee_scolaire:
        title: "Année scolaire"
        description: "Format AAAA-AAAA ou AAAA"
        type: string
        pattern: '^(\d{4}$|^\d{4}-\d{4})$'
        examples:
          court:
            summary: "format court"
            value: "2022"
          long:
            summary: "format long"
            value: "2022-2023"
        required: true

    attributes:
      eleve:
        title: "Informations sur l'élève"
        description: "Les informations retournées ici sont celles transmises en paramètre d'appel. S'il y a eu des erreurs de frappe à la saisie, elles seront renvoyées."
        type: object
        properties:
          nom:
            title: "Nom"
            description: "Nom de l'élève"
            type: string
            example: "Martin"
          prenom:
            title: "Prénom"
            description: "Prénom de l'élève"
            type: string
            example: "Justine"
          sexe:
            title: "Sexe"
            description: "Sexe de l'élève, masculin ou féminin"
            type: string
            example: "F"
            enum:
              - "M"
              - "F"
          date_naissance:
            title: "Date de naissance"
            description: "Date de naissance de l'élève au format AAAA-MM-JJ"
            type: string
            example: "2000-01-20"
      code_etablissement: *code_etablissement
      annee_scolaire:
        title: "Année scolaire"
        description: "Année scolaire de l'élève au format AAAA-AAAA"
        type: string
        pattern: '^\d{4}$|^\d{4}-\d{4}$'
        example: "2022-2023"
      est_scolarise:
        description: "Indique si l'élève est scolarisé dans l'établissement."
        type: boolean
        example: true
      est_boursier:
        description: |+
          Indique si l'élève est boursier dans l'établissement. Les bourses concernent uniquement les élèves des collèges et lycées.
          \n
          ⚠️ Si le statut boursier est à \"false\" avant mi-octobre, cela ne signifie pas forcément que l'élève n'est pas boursier. Il peut s'agir d'un faux négatif lié à une absence de l'information en base. Pour en savoir plus consulter la fiche métier : https://particulier.api.gouv.fr/catalogue/education_nationale/statut_eleve_scolarise#faq_entry_answer_1_api_particulier_endpoint_education_nationale_statut_eleve_scolarise.
        type: boolean
        example: true
      niveau_bourse:
        description: "Indique l'échelon de la bourse de l'élève. Est nul quand est_boursier est false. Les bourses concernent uniquement les élèves des collèges et lycées."
        type: integer
        example: 1
        nullable: true
        enum:
          - null
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
      status_eleve:
        title: "Statut de l'élève"
        description: |+
          Indique le statut sous lequel l'élève est scolarisé dans l'établissement. Les valeurs possibles sont&nbsp;:&nbsp;(non exhaustif)
          - ST : Scolaire, il s'agit du statut de base renvoyé pour près de 95% des élèves. Ce statut concerne également les élèves qui suivent le CNED (Centre national d'éducation à distance). Ceux-ci peuvent être distingués par l'établissement car ils sont tous affectés au même : `0861288H (CNED DIRECTION GENERALE)`.
          - AP : Apprenti
          - CQ : Contrat de qualification
          - FC : Formation continue
        type: object
        properties:
          code:
            title: "Code statut de l'élève"
            description: "Code du statut sous lequel l'élève est scolarisé dans l'établissement."
            type: string
            example: 'ST'
          libelle:
            title: "Libellé du statut de l'élève"
            description: "Libellé du statut sous lequel l'élève est scolarisé dans l'établissement."
            type: string
            example: 'SCOLAIRE'
