mi:
  association:
    title: "Données du RNA d'une association"
    description: "Informations issues du répertoire national des associations (RNA), telles que la date de création, l’adresse du siège et les dirigeants."
    tags:
      - "Informations générales"
    attributes:
      rna_id:
        type: "string"
        title: "Identifiant RNA"
      titre:
        type: "string"
        example: "LA PRÉVENTION ROUTIERE"
      objet:
        type: "string"
        example: "Accroitre la sécurité des usagers en encourageant toutes mesures ou initiatives propres à réduire les accidents"
        description: "Il s'agit d'une description courte mais exhaustive des activités de l'organisme."
      siret:
        type: "string"
        nullable: true
        example:
      siret_siege_social:
        type: "string"
        example: "77571979202650"
      date_creation:
        type: "string"
        example: "1955-01-01"
        description: "Il s'agit du jour de dépôt du dossier de
          création de l'association à la Préfecture."
      date_declaration:
        type: "string"
        example: "1955-01-01"
        description: "Jour de la dernière déclaration faîte par
          l'association."
      date_publication:
        type: "string"
        nullable: true
        example:
        description: "Jour de la publication au journal officiel
          de l'avis de création de l'association. Toutes les assoiations
          ne sont pas forcément 'déclarées'. La publication au
          Journal Officiel permet à l'association de devenir une
          personne morale, a contrario des 'associations de fait',
          non déclarées au JO."
      date_dissolution:
        type: "string"
        nullable: true
        example:
        description: "Si l'association est dissolue, ce champ indique
          la date de dissolution, autrement, il est indiqué 'null'."
      adresse_siege:
        type: "object"
        properties:
          complement:
            type: "string"
            example: "  "
          numero_voie:
            type: "string"
            example: "33"
          type_voie:
            type: "string"
            example: "rue"
          libelle_voie:
            type: "string"
            example: "de Modagor"
          distribution:
            type: "string"
            nullable: true
            example:
          code_insee:
            type: "string"
            example: "75108"
          code_postal:
            type: "string"
            example: "75009"
          commune:
            type: "string"
            example: "Paris"
      etat:
        type: "string"
        example: "true"
      groupement:
        type: "string"
        nullable: true
        example:
        description: "Trois modalités possibles : si l'association
          n'est pas un groupement, il est indiqué 'Simple'
          ; si l'association est un groupement, la valeur est
          'Union' ou 'Fédération'. La valeur peut aussi être
          manquante (null)"
      mise_a_jour:
        type: "string"
        example: "1955-01-01"

  document_association:
    title: "Divers documents d'une association"
    description: "Divers documents administratifs en PDF tels que les statuts, le récépissé de déclaration de création, la liste des dirigeants..."
    tags:
      - "Informations générales"
    type: "array"
    items:
      type: "object"
      properties:
        id:
          type: "string"
        timestamp:
          example: "1631182730"
          description: "Date du dépot du document au format timestamp UNIX"
          type: "string"
        type:
          example: "Statuts"
          description: "Ce sont les différents types de documents, et de fait, pour chaque URL, celui-ci est indiqué. Voici une liste non-exhaustive des options possibles : 'Liste des dirigeants', 'Statuts', 'Procès verbal', 'Récépissé de dissolution', 'Récépissé de modification'..."
          type: "string"
        url:
          example: "https://storage.entreprise.api.gouv.fr/siade/1635505765-5cd08405e4163c9f7713447829aeef7284c3283d-document_asso.pdf"
          description: "L'URL du fichier"
          type: "string"
        expires_in:
          title: "Nombre de secondes avant expiration du lien URL"
          type: "integer"
        errors:
          title: "Détail de l'erreur survenue au traitement du fichier (URL fourni par le fournisseur de données invalide, fichier corrompu, ...)"
          type: "array"
          items:
            type: "string"
    meta:
      nombre_documents:
        example: 1
        description: "Le nombre total de documents disponibles"
        type: "integer"
      nombre_documents_deficients:
        example: 0
        description: "Le nombre de documents ignorés car déficients (indisponibles, PDF invalide etc...)"
        type: "integer"
