qualibat:
  certifications_batiment:
    title: "Certification Qualibat"
    description: "Certificat délivré par l'association Qualibat, attestant de la **qualification d’une entreprise dans le bâtiment**."
    tags:
      - "Certifications professionnelles"
    document_url_properties:
      title: "Lien vers la certification batiment Qualibat"
      description: "Ce document est automatiquement supprimé au bout de 3 mois."
      example: "https://storage.entreprise.api.gouv.fr/siade/1635521735-1a675fc210d09e04604aabe5e93b452fb56865f5-certificat_qualibat.pdf"

