qualibat:
  certifications_batiment:
    title:
      v3: "Certification Qualibat (PDF seulement)"
      v4: "Certification Qualibat (PDF + meta-données)"
    description: "Certification délivrée par l'association Qualibat, attestant de la qualification d’une entreprise dans le bâtiment."
    tags:
      - "Certifications professionnelles"
    document_url_properties:
      title: "Lien vers la certification batiment Qualibat"
      description: "Cette URL permet de télécharger la certification Qualibat au format PDF."
      example: "https://storage.entreprise.api.gouv.fr/siade/1635521735-1a675fc210d09e04604aabe5e93b452fb56865f5-certificat_qualibat.pdf"

    properties:
      document_url:
        title: "Lien vers la certification batiment Qualibat"
        type: "string"
        description: "Cette URL permet de télécharger la certification Qualibat au format PDF."
        example: "https://storage.entreprise.api.gouv.fr/siade/1635521735-1a675fc210d09e04604aabe5e93b452fb56865f5-certificat_qualibat.pdf"
      document_url_expires_in:
        title: "Nombre de secondes avant expiration du document référencé dans 'document_url'"
        description: "Il s'agit d'une expiration technique: cette valeur n'a aucun lien avec les dates de fin de validité ou d'émission."
        type: 'integer'
        example: 86400
      date_emission:
        title: "Date d'émission du document"
        type: "date"
        nullable: true
        example: "2023-01-01"
      date_fin_validite:
        title: "Date de fin de validité du document"
        type: "date"
        nullable: true
        example: "2024-02-02"
      entity:
        type: "object"
        title: "Information sur l'entité référencée dans le document"
        properties:
          assurance_responsabilite_travaux:
            title: "Informations relatives à l'assurance responsabilité travaux"
            type: "object"
            properties: &assurance_properties
              nom:
                title: "Nom de l'assurance"
                example: "GROUPAMA"
                type: "string"
                nullable: true
              identifiant:
                title: "Numéro d'identification de l'entité enregistrée auprès de l'assurance"
                example: "1234567890"
                type: "string"
                nullable: true
          assurance_responsabilite_civile:
            title: "Informations relatives à l'assurance responsabilité civile"
            type: "object"
            properties: *assurance_properties
          certifications:
            type: "array"
            title: "Tableau des certifications associées à l'entité"
            items:
              type: "object"
              title: "Certification"
              nullable: true
              properties:
                code:
                  type: "string"
                  title: "Code associé à la certification"
                  example: "4322"
                libelle:
                  title: "Fabrication et pose de menuiserie intérieure en bois"
                  type: "string"
                  example: "Fabrication et pose de menuiserie intérieure en bois"
                rge:
                  title: "Est-ce une certification RGE ?"
                  type: "boolean"
                  example: false
                  enum:
                    - true
                    - false
                date_attribution:
                  title: "Date d'attribution"
                  type: "date"
                  example: "2022-03-03"




