rnm:
  entreprise_artisanale:
    title: "Données du RNM d'une entreprise artisanale"
    description: "Informations de référence d'une entreprise artisanale enregistrée au répertoire national des métiers (RNM)."
    tags:
      - "Informations générales"
    attributes:
      modalite_exercice:
        type: "string"
        example: "P"
        description:
          "Détermine si l'entreprise a une activité permanente ou saisonnière.
          \n
          L'activité est dite saisonnière si chaque année, l'entreprise cesse totalement ses activités pendant plus de 3 mois consécutifs.
          \n
          \n
          Les valeurs possibles sont:
          \n
          - P => Permanent
          \n
          - S => Saisonnière
          \n
          - NR => Non renseignée"
        enum:
          - "P"
          - "S"
          - "NR"
      non_sedentaire:
        type: "string"
        example: "0"
        description: "Indique si l'entreprise a une activité ambulante.
          \n
          \n
          Les valeurs possibles sont:
          \n
          - 0 => sédentaire
          \n
          - 1 => non-sédentaire"
        enum:
          - "0"
          - "1"
