european_commission:
  vies:
    title: "Récupération du numéro de TVA"
    description: "Récupération du numéro du TVA à partir d'un numéro de siren."
    tags:
      - "Informations générales"
    attributes:
      tva_number:
        title: "Numéro de TVA intracommunautaire"
        description: "Ce numéro de TVA est extrait du numéro de siren à l'aide de la règle de calcul du numéro de TVA, et validé auprès du service VIES. Ce numéro de TVA est forcément un numéro de TVA français."
        example: "FR48672039971"
