module JwtHelper
  class << self
    def jwt(type = :valid)
      samples = {
        valid: 'eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiJmNWQ1Y2IwMi0xODVhLTQyNmYtYjNmNC05OWEyNWNlNmNkZjQiLCJqdGkiOiIzZDQ3MDZjNC03ZjVlLTQ0NDItYTczNC0wMGQ2YzY3NWYzYzkiLCJzY29wZXMiOlsiYXR0ZXN0YXRpb25zX2FnZWZpcGgiLCJhdHRlc3RhdGlvbnNfZmlzY2FsZXMiLCJhdHRlc3RhdGlvbnNfc29jaWFsZXMiLCJjZXJ0aWZpY2F0X2NuZXRwIiwiYXNzb2NpYXRpb25zIiwiY2VydGlmaWNhdF9vcHFpYmkiLCJkb2N1bWVudHNfYXNzb2NpYXRpb24iLCJldGFibGlzc2VtZW50cyIsImVudHJlcHJpc2VzIiwiZW50cmVwcmlzZXNfYXJ0aXNhbmFsZXMiLCJleHRyYWl0X2NvdXJ0X2lucGkiLCJleHRyYWl0c19yY3MiLCJleGVyY2ljZXMiLCJsaWFzc2VfZmlzY2FsZSIsImZudHBfY2FydGVfcHJvIiwicXVhbGliYXQiLCJwcm9idHAiLCJtc2FfY290aXNhdGlvbnMiLCJiaWxhbnNfZW50cmVwcmlzZV9iZGYiLCJjZXJ0aWZpY2F0X3JnZV9hZGVtZSIsImNlcnRpZmljYXRfYWdlbmNlX2JpbyIsImFjdGVzX2lucGkiLCJiaWxhbnNfaW5waSIsImNvbnZlbnRpb25zX2NvbGxlY3RpdmVzIiwiZW9yaV9kb3VhbmVzIl0sInN1YiI6InRlc3Qgc2lhZGUiLCJpYXQiOjE1OTY3OTE2NTksInZlcnNpb24iOiIxLjAifQ.B1cadJNT3yao-yfOI7Lqi9c0mo8R-j5RSp29MQ-T5W4',
        with_roles_not_scopes: 'eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiJiYTI2MWY5OC1mMjA0LTQ0ZmYtOGQwYS04MmEzNWEzYjFlYWEiLCJqdGkiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJyb2xlcyI6WyJkb2N1bWVudHNfYXNzb2NpYXRpb24iLCJhc3NvY2lhdGlvbnMiLCJmbnRwX2NhcnRlX3BybyIsImVudHJlcHJpc2VfYXJ0aXNhbmFsZSIsInVwdGltZSIsInByb2J0cCIsImFpZGVzX2NvdmlkX2VmZmVjdGlmcyIsImV0YWJsaXNzZW1lbnRzIiwiY2VydGlmaWNhdF9jbmV0cCIsImJpbGFuc19lbnRyZXByaXNlX2JkZiIsImNlcnRpZmljYXRfcmdlX2FkZW1lIiwiZXh0cmFpdF9jb3VydF9pbnBpIiwiY2VydGlmaWNhdF9vcHFpYmkiLCJjb252ZW50aW9uc19jb2xsZWN0aXZlcyIsInByaXZpbGVnZXMiLCJhY3Rlc19pbnBpIiwiYmlsYW5zX2lucGkiLCJhdHRlc3RhdGlvbnNfc29jaWFsZXMiLCJtc2FfY290aXNhdGlvbnMiLCJxdWFsaWJhdCIsImF0dGVzdGF0aW9uc19hZ2VmaXBoIiwiZW50cmVwcmlzZXMiLCJleHRyYWl0c19yY3MiLCJlb3JpX2RvdWFuZXMiLCJjZXJ0aWZpY2F0X2FnZW5jZV9iaW8iLCJleHRyYWl0X3JjcyIsImVudHJlcHJpc2UiLCJldGFibGlzc2VtZW50IiwibGlhc3NlX2Zpc2NhbGUiLCJhdHRlc3RhdGlvbnNfZmlzY2FsZXMiLCJleGVyY2ljZXMiLCJlbnRyZXByaXNlc19hcnRpc2FuYWxlcyJdLCJzdWIiOiJ0ZXN0IGRldmVsb3BtZW50IiwiaWF0IjoxNjU1NzIzODk2LCJ2ZXJzaW9uIjoiMS4wIn0.LKGEDovDXyrR5vw4v6OLO4BAgoNFn0959b-iyX8KGlk',
        unsigned: 'eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiJmNWQ1Y2IwMi0xODVhLTQyNmYtYjNmNC05OWEyNWNlNmNkZjQiLCJqdGkiOiIzZDQ3MDZjNC03ZjVlLTQ0NDItYTczNC0wMGQ2YzY3NWYzYzkiLCJzY29wZXMiOlsiYXR0ZXN0YXRpb25zX2FnZWZpcGgiLCJhdHRlc3RhdGlvbnNfZmlzY2FsZXMiLCJhdHRlc3RhdGlvbnNfc29jaWFsZXMiLCJjZXJ0aWZpY2F0X2NuZXRwIiwiYXNzb2NpYXRpb25zIiwiY2VydGlmaWNhdF9vcHFpYmkiLCJkb2N1bWVudHNfYXNzb2NpYXRpb24iLCJldGFibGlzc2VtZW50cyIsImVudHJlcHJpc2VzIiwiZW50cmVwcmlzZXNfYXJ0aXNhbmFsZXMiLCJleHRyYWl0X2NvdXJ0X2lucGkiLCJleHRyYWl0c19yY3MiLCJleGVyY2ljZXMiLCJsaWFzc2VfZmlzY2FsZSIsImZudHBfY2FydGVfcHJvIiwicXVhbGliYXQiLCJwcm9idHAiLCJtc2FfY290aXNhdGlvbnMiLCJiaWxhbnNfZW50cmVwcmlzZV9iZGYiLCJjZXJ0aWZpY2F0X3JnZV9hZGVtZSIsImFjdGVzX2lucGkiLCJiaWxhbnNfaW5waSIsImNvbnZlbnRpb25zX2NvbGxlY3RpdmVzIiwiZW9yaV9kb3VhbmVzIl0sInN1YiI6InRlc3Qgc2lhZGUiLCJpYXQiOjE1OTY3OTE2NTksImV4cCI6MTU5Njc5MTY1OSwidmVyc2lvbiI6IjEuMCJ9.',
        forged: 'eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiI0YzYzYzlkOS0xOGRjLTRhNjMtYTU1NS1kZTg3ZjY0M2YyYzAiLCJzY29wZXMiOlsic2NvcGVfMyIsInNjb3BlXzQiXX0.GHc2-BSDXn91ihVz1bmW8ZYr5w1Nrbf7ypdaMU0JsEs',
        corrupted: 'eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiI0YzYzYzlkOS0xOGRjLTRhNjMtYTU1NSgdfgd1kZTg3ZjY0M2YyYzAiLCJyb2xlcyI6WyJyb2wzIiwicm9sNCJdfQ.28Zo8dOMOxd4G5-nR-sfmNlbqRnSvbRbVkVto6i50gI',
        no_scopes: 'eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiJmNWQ1Y2IwMi0xODVhLTQyNmYtYjNmNC05OWEyNWNlNmNkZjQiLCJqdGkiOiJiMTU3OGRhMC01MmZlLTRiY2EtYmZhYy1iNWUxODNlOWU3MWMiLCJzY29wZXMiOltdLCJzdWIiOiJOTyBKV1QiLCJpYXQiOjE1ODAzMDMxMjAsInZlcnNpb24iOiIxLjAifQ.i5b8oXRKwy4G-HZNWNo0BNxWr9xuNLfS7O5V-0VCfek',
        without_uuid_as_jti: 'eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiJmNWQ1Y2IwMi0xODVhLTQyNmYtYjNmNC05OWEyNWNlNmNkZjQiLCJqdGkiOiJpbnZhbGlkIiwic2NvcGVzIjpbIndoYXRldmVyIl0sInN1YiI6InRlc3Qgc2lhZGUiLCJpYXQiOjE1OTY3OTE2NTksInZlcnNpb24iOiIxLjAifQ.XAtg7eWZm7IskGMTqCf8SUaTrIL1wLzLzIOxobMBxpU',
        without_uuid_as_uid: 'eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiJpbnZhbGlkIiwianRpIjoiM2Q0NzA2YzQtN2Y1ZS00NDQyLWE3MzQtMDBkNmM2NzVmM2M5Iiwic2NvcGVzIjpbIndoYXRldmVyIl0sInN1YiI6InRlc3Qgc2lhZGUiLCJpYXQiOjE1OTY3OTE2NTksInZlcnNpb24iOiIxLjAifQ.rsynq22LVKVHf38emKev5CeMnz20brJduajBvKxauP0'
      }

      samples[type]
    end
  end
end

def yes_jwt
  @yes_jwt ||= TokenFactory.new(Scope.all).valid
end

def expired_jwt
  @expired_jwt ||= TokenFactory.new(Scope.all).expired
end

def yes_jwt_id
  Seeds.new.yes_jwt_id
end

def unsigned_jwt
  JwtHelper.jwt(:unsigned)
end

def forged_jwt
  JwtHelper.jwt(:forged)
end

def yes_jwt_user
  JwtTokenService.instance.extract_user(yes_jwt)
end

def expired_jwt_user
  JwtTokenService.instance.extract_user(expired_jwt)
end

def corrupted_jwt
  JwtHelper.jwt(:corrupted)
end

def nope_jwt
  JwtHelper.jwt(:no_scopes)
end
