---
shared:
  - 'ABEILLE IARD & SANTE'
  - 'ABEILLE'
  - 'ACTE IARD'
  - 'ACM-IARD SA'
  - 'AIG'
  - 'ALLIANZ IARD'
  - 'APRIL'
  - 'AUXILIAIRE'
  - 'AVIVA'
  - 'AREAS'
  - 'AXAASSURANCES'
  - 'AXA FRANCE IARD'
  - 'AXA CSA'
  - 'AXERIA IARD'
  - 'AXELLIANCE'
  - 'BPCE ASSURANCES'
  - 'BPCE IARD'
  - 'CAMBTP'
  - 'CHUBB'
  - 'ENTORIA'
  - 'ERGO'
  - 'EUROMAF'
  - 'GAN'
  - 'GENERALI IARD'
  - 'GOTHAER VERSICHERUNGBANK'
  - 'GROUPAMA'
  - 'LA BRESSE'
  - 'LIBERTY MUTUAL INSURANCE'
  - 'HDI GLOBAL'
  - 'MAAF'
  - 'MMA IARD'
  - 'MIC ASSURANCE'
  - 'MIC INSURANCE'
  - 'MONCEAU GENERALE ASSURANCES'
  - 'MUTUELLE BRESSE BUGEY'
  - 'MUTUELLE VAL DE SAÔNE BEAUJOLAIS'
  - 'MUTUELLE DE POITIERS ASSURANCES'
  - 'UNIRE'
  - 'QBE'
  - 'SAM BTP'
  - 'SMA COURTAGE'
  - 'SMA SA'
  - 'SMABTP'
  - 'SMA'
  - 'SWISSLIFE'
  - 'VHV'
  - 'THELEMASSURANCES'
  - 'XL INSURANCE'
  - 'ZURICH INSURANCE'
