---
shared:
  - 'ABEILLE IARD & SANTE'
  - 'ACTE IARD'
  - 'AIG'
  - 'ALLIANZ IARD'
  - 'AUXILIAIRE'
  - 'AVIVA'
  - 'AXAASSURANCES'
  - 'AXA FRANCE IARD'
  - 'CAMBTP'
  - 'ERGO'
  - 'EUROMAF'
  - 'GAN'
  - 'GENERALI IARD'
  - 'GROUPAMA'
  - 'LIBERTY MUTUAL INSURANCE'
  - 'HDI GLOBAL'
  - 'MAAF'
  - 'MMA IARD'
  - 'MONCEAU GENERALE ASSURANCES'
  - 'MUTUELLE VAL DE SAÔNE BEAUJOLAIS'
  - 'SMA COURTAGE'
  - 'SMA SA'
  - 'SMABTP'
  - 'THELEMASSURANCES'
  - 'XL INSURANCE'
