- uid: api-entreprise
  name: API Entreprise
  description: Accédez aux informations et aux documents administratifs des entreprises
  use_case: null
  prefilled?: false
  data:
    - cadre_juridique_nature
    - cadre_juridique_url
    - scopes

- uid: api-entreprise-marches-publics
  name: Marchés publics
  description: Simplifier le dépôt des candidatures et récupérer les justificatifs administratifs des entreprises/associations.
  use_case: marches_publics
  prefilled?: true
  data:
    cadre_juridique_nature: R2143-13 Code de la commande publique
    cadre_juridique_url: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000037730589
    scopes:
      - unites_legales_etablissements_insee
      - associations_djepva
      - data_subvention_subventions
      - chiffre_affaires_dgfip
      - attestation_fiscale_dgfip
      - attestation_sociale_urssaf
      - cotisations_msa
