shared: &shared
  0811ZA: "Extraction de pierres ornementales et de construction et d'ardoise"
  1320ZA: "Tissage de l'industrie cotonnière"
  1320ZB: "Tissage de l'industrie lainière"
  1320ZC: "Tissage de soieries"
  1320ZD: "Tissage d'autres textiles"
  1330ZZ: "Ennoblissement textile"
  1392ZA: "Fabrication de linge de maison et d'articles d'ameublement"
  1392ZB: "Fabrication de tapisserie à la main"
  1392ZC: "Fabrication de coussins et petits articles textiles divers"
  1393ZZ: "Fabrication de tapis et moquettes"
  1396ZZ: "Fabrication de textiles techniques et industriels"
  1399ZA: "Fabrication de feutres"
  1399ZB: "Fabrication de tulles, lacets et autres textiles n.c.a."
  1411ZZ: "Fabrication de vêtements en cuir"
  1413ZA: "Modéliste-styliste"
  1413ZB: "Fabrication de vêtements féminins sur mesure"
  1413ZC: "Fabrication de vêtements masculins sur mesure"
  1413ZD: "Chemiserie sur mesure"
  1413ZE: "Fabrication de gaines, corsets et autres vêtements sur mesure"
  1413ZF: "Fabrication de vêtements de dessus pour hommes et garçonnets"
  1413ZG: "Fabrication de vêtements de dessus pour femmes et fillettes"
  1414ZZ: "Fabrication de vêtements de dessous"
  1419ZB: "Fabrication de chapellerie"
  1419ZC: "Modiste"
  1419ZE: "Fabrication d'autres vêtements et accessoires"
  1419ZF: "Fabrication d'accessoires en cuir"
  1420ZZ: "Fabrication d'articles en fourrure"
  1511ZZ: "Apprêt et tannage des cuirs; préparation et teinture des fourrures"
  1512ZA: "Fabrication d'articles de maroquinerie"
  1512ZB: "Gainerie"
  1512ZC: "Sellerie"
  1512ZD: "Bourrellerie"
  1520ZC: "Fabrication de chaussures et de bottes sur mesure"
  1610AR: "Fabrication de parquets, moulures et baguettes"
  1622ZZ: "Fabrication de parquets assemblés"
  1623ZZ: "Fabrication de charpentes et d'autres menuiseries"
  1629ZA: "Fabrication d'objets divers en bois"
  1629ZB: "Vannerie, sparterie, travail de la paille"
  1712ZZ: "Fabrication de papier et de carton"
  1721BZ: "Fabrication de cartonnages"
  1723ZZ: "Fabrication d'articles de papeterie"
  1724ZZ: "Fabrication de papiers peints"
  1729ZZ: "Fabrication d'autres articles en papier ou en carton"
  1812ZA: "Imprimerie de labeur"
  1812ZB: "Sérigraphie de type imprimerie"
  1813ZA: "Travaux de préparation d'impression"
  1813ZB: "Graphisme-décoration"
  1813ZC: "Activités graphiques n.c.a."
  1814ZZ: "Reliure et activités connexes"
  2312ZZ: "Façonnage et transformation du verre plat"
  2313ZA: "Fabrication de verre creux ou autres verres"
  2313ZB: "Soufflage de verre"
  2313ZC: "Façonnage de verre et de cristal"
  2319ZA: "Fabrication de vitraux"
  2319ZB: "Fabrication d'articles techniques en verre"
  2331ZZ: "Fabrication de carreaux en céramique"
  2332ZA: "Fabrication de briques"
  2332ZB: "Fabrication de tuiles"
  2341ZZ: "Fabrication d'articles céramiques à usage domestique ou ornemental"
  2349ZZ: "Fabrication d'autres produits céramiques"
  2369ZA: "Fabrication de cheminée décoratives"
  2369ZB: "Fabrication d'éléments décoratifs en béton ou en plâtre"
  2370ZZ: "Taille, façonnage et finissage de pierres"
  2410ZZ: "Sidérurgie"
  2441ZZ: "Production de métaux précieux"
  2445ZZ: "Métallurgie des autres métaux non ferreux"
  2454ZZ: "Fonderie d'autres métaux non ferreux"
  2511ZZ: "Fabrication de structures métalliques et de parties de structures"
  2512ZZ: "Fabrication de portes et fenêtres en métal"
  2540ZZ: "Fabrication d'armes et de munitions"
  2550AZ: "Forge, estampage, matriçage ; métallurgie des poudres"
  2561ZB: "Traitement et revêtement des métaux"
  2571ZZ: "Fabrication de coutellerie"
  2572ZZ: "Fabrication de serrures et de ferrures"
  2573AZ: "Fabrication de moules et modèles"
  2573BA: "Fabrication d'outillage à main"
  2573BB: "Fabrication d'outillage mécanique"
  2599AA: "Dinanderie"
  2599BC: "Fabrication d'autres articles métalliques n.c.a."
  2652ZZ: "Horlogerie"
  2740ZB: "Fabrication de luminaires"
  2740ZC: "Fabrication d'abat-jour"
  2899BZ: "Fabrication d'autres machines spécialisées"
  2932ZZ: "Fabrication d'autres équipements automobiles"
  3011ZA: "Construction de navires"
  3011ZB: "Transformation et équipement des navires"
  3012ZZ: "Construction de bateau de plaisance"
  3099ZZ: "Fabrication d'autres équipements de transport n.c.a."
  3101ZZ: "Fabrication de meubles de bureau et de magasin"
  3102ZZ: "Fabrication de meubles de cuisine"
  3109AZ: "Fabrication de sièges d'ameublement d'intérieur"
  3109BA: "Fabrication et finissage de meubles divers"
  3109BC: "Fabrication de meubles en rotin"
  3211ZZ: "Frappe de monnaie"
  3212ZZ: "Fabrication d'articles de joaillerie et de bijouterie"
  3213ZZ: "Fabrication d'articles de bijouterie fantaisie et articles similaires"
  3220ZA: "Lutherie"
  3220ZB: "Facteur d'orgues"
  3220ZC: "Fabrication d'autres instruments de musique"
  3240ZZ: "Fabrication de jeux et jouets"
  3250BP: "Fabrication de lunettes de protection"
  3291ZZ: "Fabrication d'articles de brosserie"
  3299ZA: "Fabrication de bougies"
  3299ZB: "Fabrication d'accessoires du vêtements"
  3299ZC: "Fabrication d'articles de Paris, d'arts ou religieux"
  3299ZD: "Fabrication d'articles de fumeurs"
  3299ZE: "Taxidermie"
  3299ZG: "Fabrication de produits manufacturés non classés ailleurs"
  3311ZZ: "Réparation d'ouvrages en métaux"
  3315ZZ: "Réparation et maintenance navale"
  3316ZZ: "Réparation et maintenance d'aéronefs et d'engins spatiaux"
  3317ZZ: "Réparation et maintenance d'autres équipements de transport"
  3319ZZ: "Réparation d'autres équipements"
  3320DZ: "Installation d'équipements électriques, de matériels électroniques et optiques ou d'autres matériels"
  4331ZA: "Travaux de plâtrerie d'extérieur"
  4331ZB: "Travaux de plâtrerie d'intérieur"
  4332AA: "Menuiserie bois"
  4332BA: "Installation de serres et de vérandas"
  4332BB: "Métallerie, serrurerie"
  4333ZZ: "Travaux de revêtement des sols et des murs"
  4334ZC: "Travaux de peinture intérieure et peinture plâtrerie"
  4334ZD: "Travaux de peinture en lettres sur bâtiments"
  4339ZZ: "Autres travaux de finition (comprend ferronnerie décorative)"
  4391AZ: "Travaux de charpente"
  4391BZ: "Travaux de couverture par éléments"
  4399CZ: "Travaux de maçonnerie générale et gros œuvre de bâtiment"
  4399DB: "Construction de cheminées et de fours industriels"
  4399DC: "Autres travaux spécialisés de construction"
  4520AA: "Réparation automobile de véhicules automobiles légers : entretien courant"
  4520AB: "Réparation automobile de véhicules automobiles légers : mécanique"
  4520AC: "Réparation automobile de véhicules automobiles légers: carrosserie"
  4520BA: "Réparation automobile d'autres véhicules automobiles : entretien courant"
  4520BB: "Réparation automobile d'autres véhicules : mécanique"
  4520BD: "Réparation automobile d'autres véhicules automobiles: carrosserie"
  4540ZP: "Réparation de motocycles"
  7420ZQ: "Studio de photographie"
  7420ZR: "Portrait, reportage"
  9001ZP: "Spectacles de marionnettes"
  9003AP: "Restauration d'objets d'art"
  9524ZZ: "Réparation de meubles et d'équipements du foyer"
  9525ZZ: "Réparation d'articles d'horlogerie et de bijouterie"
  9529ZE: "Accordeurs de piano et restauration d'autres instruments de musique"
  9529ZF: "Réparation non classées ailleurs"

development:
  <<: *shared

test:
  <<: *shared

production:
  <<: *shared
