default: &default
  adapter: postgresql
  encoding: unicode
  username: siade
  password: wow*verysecret
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>

development:
  <<: *default
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  database: <%= ENV.fetch("DATABASE_NAME_DEVELOPMENT") { 'siade_development' } %>

test: &test
  <<: *default
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  database: <%= ENV.fetch("DATABASE_NAME_TEST") { 'siade_test' } %>

production: *test
