# API Entreprise v3+

- name: 'URSSAF Attestations de vigilance'
  api: 'entreprise'
  path: '/v3/urssaf/unites_legales/418166096/attestation_vigilance'

- name: 'URSSAF Attestations de vigilance'
  api: 'entreprise'
  path: '/v4/urssaf/unites_legales/418166096/attestation_vigilance'

- name: "DGFIP Attestation fiscale"
  api: 'entreprise'
  path: '/v3/dgfip/unites_legales/532010576/attestation_fiscale'

- name: "DGFIP Attestation fiscale"
  path: '/v4/dgfip/unites_legales/532010576/attestation_fiscale'
  api: 'entreprise'

- name: 'DGFIP Liasses fiscales'
  api: 'entreprise'
  path: '/v3/dgfip/unites_legales/301028346/liasses_fiscales/2016'

- name: 'DGFIP Liens capitalistiques'
  api: 'entreprise'
  path: '/v3/dgfip/unites_legales/487579690/liens_capitalistiques/2019'

- name: "DGFIP Chiffre d'affaires"
  api: 'entreprise'
  path: '/v3/dgfip/etablissements/82152473300028/chiffres_affaires'

- name: 'ADEME Certification RGE'
  api: 'entreprise'
  path: '/v3/ademe/etablissements/50530961700023/certification_rge'

- name: 'Douanes Immatriculations EORI'
  api: 'entreprise'
  path: '/v3/douanes/etablissements/FR16002307300010/immatriculations_eori'

- name: 'Infogreffe Mandataires Sociaux'
  api: 'entreprise'
  path: '/v3/infogreffe/rcs/unites_legales/418166096/mandataires_sociaux'

- name: 'Infogreffe Extrait KBIS'
  api: 'entreprise'
  path: '/v3/infogreffe/rcs/unites_legales/831386297/extrait_kbis'

- name: 'INPI Brevets'
  api: 'entreprise'
  path: '/v3/inpi/unites_legales/542065479/brevets'

- name: 'INPI Marques'
  api: 'entreprise'
  path: '/v3/inpi/unites_legales/542065479/marques'

- name: 'INPI Modeles'
  api: 'entreprise'
  path: '/v3/inpi/unites_legales/542065479/modeles'

- name: 'INSEE Etablissements'
  api: 'entreprise'
  path: '/v3/insee/sirene/etablissements/30613890002979'

- name: 'INSEE Etablissements V4'
  api: 'entreprise'
  path: '/v4/insee/sirene/etablissements/30613890002979'

- name: 'INSEE Etablissements Adresse'
  api: 'entreprise'
  path: '/v3/insee/sirene/etablissements/30613890002979/adresse'

- name: 'INSEE Unites Legales'
  api: 'entreprise'
  path: '/v3/insee/sirene/unites_legales/306138900'

- name: 'INSEE Unites Legales V4'
  api: 'entreprise'
  path: '/v4/insee/sirene/unites_legales/306138900'

- name: 'INSEE Unites Legales diffusibles'
  api: 'entreprise'
  path: '/v3/insee/sirene/unites_legales/diffusibles/306138900'

- name: 'INSEE Unites Legales Siege social'
  api: 'entreprise'
  path: '/v3/insee/sirene/unites_legales/306138900/siege_social'

- name: 'INSEE Unites Legales Siege social diffusibles'
  api: 'entreprise'
  path: '/v3/insee/sirene/unites_legales/diffusibles/306138900/siege_social'

- name: 'INSEE Successions'
  api: 'entreprise'
  path: '/v3/insee/sirene/etablissements/41054521400034/successions'

- name: "Ministère de l'Intérieur associations"
  api: 'entreprise'
  path: '/v3/ministere_interieur/rna/associations/77571979202650'

- name: "Ministère de l'Intérieur documents associations"
  api: 'entreprise'
  path: '/v3/ministere_interieur/rna/associations/77571979202650/documents'

- name: 'OPQIBI Certifications Ingénierie'
  api: 'entreprise'
  path: '/v3/opqibi/unites_legales/309103877/certification_ingenierie'

- name: 'ProBTP Attestations cotisations retraite'
  api: 'entreprise'
  path: '/v3/probtp/etablissements/45309127400036/attestation_cotisations_retraite'

- name: 'ProBTP Conformité cotisations retraite'
  api: 'entreprise'
  path: '/v3/probtp/etablissements/45309127400036/conformite_cotisations_retraite'

- name: 'FNMS Conventions collectives'
  api: 'entreprise'
  path: '/v3/fabrique_numerique_ministeres_sociaux/etablissements/89337342300019/conventions_collectives'

- name: 'RNM Entreprises'
  api: 'entreprise'
  path: '/v3/cma_france/rnm/unites_legales/301123626'

- name: 'QUALIBAT Certifications batiment'
  api: 'entreprise'
  path: '/v3/qualibat/etablissements/78824266700020/certification_batiment'

- name: '[v4] QUALIBAT Certifications batiment'
  api: 'entreprise'
  path: '/v4/qualibat/etablissements/78824266700020/certification_batiment'

- name: 'Commission Européenne numéro de TVA'
  api: 'entreprise'
  path: '/v3/european_commission/unites_legales/552032534/numero_tva'

- name: 'Banque de France Bilans'
  api: 'entreprise'
  path: '/v3/banque_de_france/unites_legales/418166096/bilans'

- name: 'CNETP Attestations cotisations conges payes chomages intemperies'
  api: 'entreprise'
  path: '/v3/cnetp/unites_legales/811214428/attestation_cotisations_conges_payes_chomage_intemperies'

- name: 'Douanes Immatriculations EORI'
  api: 'entreprise'
  path: '/v3/douanes/etablissements/FR16002307300010/immatriculations_eori'

- name: 'DGFIP liasses_fiscales'
  api: 'entreprise'
  path: '/v3/dgfip/unites_legales/418166096/liasses_fiscales/2016'

- name: 'FNTP Carte professionnelle travaux publics'
  api: 'entreprise'
  path: '/v3/fntp/unites_legales/385407184/carte_professionnelle_travaux_publics'

- name: 'INSEE Etablissements diffusibles Adresse'
  api: 'entreprise'
  path: '/v3/insee/sirene/etablissements/diffusibles/41816609600069/adresse'

- name: 'MSA Conformité cotisations'
  api: 'entreprise'
  path: '/v3/msa/etablissements/95086311800010/conformite_cotisations'

- name: "DJEPVA associations"
  api: 'entreprise'
  path: '/v4/djepva/api-association/associations/775719792'

- name: "DJEPVA associations open data"
  api: 'entreprise'
  path: '/v4/djepva/api-association/associations/open_data/775719792'

- name: "Datasubvention subventions"
  api: 'entreprise'
  path: '/v3/data_subvention/associations/789510732/subventions'

- name: "GIP-MDS effectifs annuel unité légale"
  api: 'entreprise'
  path: '/v3/gip_mds/unites_legales/552032534/effectifs_annuels/2020'

- name: "GIP-MDS effectifs mensuels établissement"
  api: 'entreprise'
  path: '/v3/gip_mds/etablissements/84503885000010/effectifs_mensuels/12/annee/2022'

- name: "Qualifelec certificats"
  api: 'entreprise'
  path: '/v3/qualifelec/etablissements/42054064300376/certificats'

- name: "Qualiopi certificats"
  api: 'entreprise'
  path: '/v3/carif_oref/etablissements/78824266700020/certifications_qualiopi_france_competences/'

- name: "RNE INPI bénéficiaires effectifs Open Data (deprecated)"
  api: 'entreprise'
  path: '/v3/inpi/rne/unites_legales/open_data/900225095/beneficiaires_effectifs'

- name: "RNE INPI bénéficiaires effectifs"
  api: 'entreprise'
  path: '/v3/inpi/rne/unites_legales/900225095/beneficiaires_effectifs'

- name: "RNE INPI Extrait RNE"
  api: 'entreprise'
  path: '/v3/inpi/rne/unites_legales/900225095/extrait_rne'

- name: "RNE INPI Actes Bilans"
  api: 'entreprise'
  path: '/v3/inpi/rne/unites_legales/open_data/542065479/actes_bilans'

- name: "CIBTP Attestations Cotisations Chomage Intemperies"
  api: 'entreprise'
  path: '/v3/cibtp/etablissements/81125785600021/attestation_cotisations_conges_payes_chomage_intemperies'

# API Particulier v2

- name: 'CAF Quotient familial'
  path: '/api/v2/composition-familiale'
  api: 'particulier'
  encrypted_query_params:
    codePostal: ping_cnaf_postal_code
    numeroAllocataire: ping_cnaf_numero_allocataire

- name: 'France Travail identité'
  path: '/api/v2/situations-pole-emploi'
  api: 'particulier'
  query_params:
    identifiant: 'azerty3'

- name: 'France Travail paiements'
  path: '/api/v2/paiements-pole-emploi'
  api: 'particulier'
  query_params:
    identifiant: 'azerty3'
