- name: Bilans Entreprises Banque de France
  http_path: '/v2/bilans_entreprises_bdf/784778250'

- name: Liasses fiscales (complete)
  http_path: '/v2/liasses_fiscales_dgfip/2016/complete/301028346'

- name: Liasses fiscales (déclaration)
  http_path: '/v2/liasses_fiscales_dgfip/2016/declarations/301028346'

- name: Liasses fiscales (dictionnaire)
  http_path: '/v2/liasses_fiscales_dgfip/2016/dictionnaire'

- name: Cotisations MSA
  http_path: '/v2/cotisations_msa/81104725700019'

- name: Eligibilité cotisation retraite ProBTP
  http_path: '/v2/eligibilites_cotisation_retraite_probtp/45309127400036'

- name: Attestations cotisations retraite ProBTP
  http_path: '/v2/attestations_cotisation_retraite_probtp/45309127400036'

- name: Entreprise
  http_path: '/v2/entreprises/418166096'

- name: Extraits RCS (Infogreffe)
  http_path: '/v2/extraits_rcs_infogreffe/418166096'

- name: Etablissements
  http_path: '/v2/etablissements/41816609600069'

- name: Exercices
  http_path: '/v2/exercices/53930425300013'

- name: Attestations agefiph
  http_path: '/v2/attestations_agefiph/48146131700036'

- name: Attestations fiscales
  http_path: '/v2/attestations_fiscales_dgfip/532010576'

- name: Attestations sociales
  http_path: '/v2/attestations_sociales_acoss/418166096'

- name: Effectifs annuels
  http_path: '/v2/effectifs_annuels_acoss_covid/829423052'

- name: Effectifs mensuels (entreprise)
  http_path: '/v2/effectifs_mensuels_acoss_covid/2020/02/entreprise/552032534'

- name: Effectifs mensuels (établissement)
  http_path: '/v2/effectifs_mensuels_acoss_covid/2020/02/etablissement/55203253400646'

- name: Conventions Collectives
  http_path: '/v2/conventions_collectives/82161143100015'

- name: Certificats Qualibat
  http_path: '/v2/certificats_qualibat/78824266700020'

- name: Entreprises artisanales CMA France
  http_path: '/v2/entreprises_artisanales_cma/301123626'

- name: Certificats CNETP
  http_path: '/v2/certificats_cnetp/542036207'

- name: Certificats OPQIBI
  http_path: '/v2/certificats_opqibi/309103877'

- name: Associations
  http_path: '/v2/associations/W604004799'

- name: Documents associations
  http_path: '/v2/documents_associations/77571979202585'

- name: Extraits courts INPI
  http_path: '/v2/extraits_courts_inpi/542065479'

- name: Cartes professionnelles FNTP
  http_path: '/v2/cartes_professionnelles_fntp/562077503'

- name: Certificats RGE ADEME
  http_path: '/v2/certificats_rge_ademe/50044188600016'

- name: Certificats Agence BIO
  http_path: '/v2/certificats_agence_bio/48311105000025'

- name: Actes INPI
  http_path: '/v2/actes_inpi/788242667'

- name: Bilans INPI
  http_path: '/v2/bilans_inpi/788242667'

- name: Etablissements (INSEE v3)
  http_path: '/v2/etablissements/41816609600069'
  extra_http_query:
    with_insee_v3: true

- name: Entreprise (INSEE v3)
  http_path: '/v2/entreprises/418166096'
  extra_http_query:
    with_insee_v3: true

- name: EORI DGDDI (Douane)
  http_path: '/v2/eori_douanes/FR16002307300010'

- name: '[V3] URSSAF Attestations de vigilance'
  http_path: '/v3/urssaf/unites_legales/418166096/attestation_vigilance'

- name: '[V4] URSSAF Attestations de vigilance'
  http_path: '/v4/urssaf/unites_legales/418166096/attestation_vigilance'

- name: "[V3] DGFIP Attestation fiscale"
  http_path: '/v3/dgfip/unites_legales/532010576/attestation_fiscale'

- name: "[V4] DGFIP Attestation fiscale"
  http_path: '/v4/dgfip/unites_legales/532010576/attestation_fiscale'

- name: '[V3] DGFIP Liasses fiscales'
  http_path: '/v3//dgfip/unites_legales/301028346/liasses_fiscales/2016'

- name: "[V3] DGFIP Chiffre d'affaires"
  http_path: '/v3/dgfip/etablissements/78951073200017/chiffres_affaires'

- name: '[V3] ADEME Certification RGE'
  http_path: '/v3/ademe/etablissements/50530961700023/certification_rge'

- name: '[V3] Douanes Immatriculations EORI'
  http_path: '/v3/douanes/etablissements/FR16002307300010/immatriculations_eori'

- name: '[V3] Infogreffe Mandataires Sociaux'
  http_path: '/v3/infogreffe/rcs/unites_legales/418166096/mandataires_sociaux'

- name: '[V3] Infogreffe Extrait KBIS'
  http_path: '/v3/infogreffe/rcs/unites_legales/831386297/extrait_kbis'

- name: '[V3] INPI Actes'
  http_path: '/v3/inpi/unites_legales/542065479/actes'

- name: '[V3] INPI Brevets'
  http_path: '/v3/inpi/unites_legales/542065479/brevets'

- name: '[V3] INPI Marques'
  http_path: '/v3/inpi/unites_legales/542065479/marques'

- name: '[V3] INPI Modeles'
  http_path: '/v3/inpi/unites_legales/542065479/modeles'

- name: '[V3] INSEE Etablissements'
  http_path: '/v3/insee/sirene/etablissements/30613890002979'

- name: '[V3] INSEE Etablissements Adresse'
  http_path: '/v3/insee/sirene/etablissements/30613890002979/adresse'

- name: '[V3] INSEE Unites Legales'
  http_path: '/v3/insee/sirene/unites_legales/306138900'

- name: '[V3] INSEE Unites Legales diffusibles'
  http_path: '/v3/insee/sirene/unites_legales/diffusibles/306138900'

- name: '[V3] INSEE Unites Legales Siege social'
  http_path: '/v3/insee/sirene/unites_legales/306138900/siege_social'

- name: '[V3] INSEE Unites Legales Siege social diffusibles'
  http_path: '/v3/insee/sirene/unites_legales/diffusibles/306138900/siege_social'

- name: "[V3] Ministère de l'Intérieur associations"
  http_path: '/v3/ministere_interieur/rna/associations/77571979202650'

- name: "[V3] Ministère de l'Intérieur documents associations"
  http_path: '/v3/ministere_interieur/rna/associations/77571979202650/documents'

- name: '[V3] OPQIBI Certifications Ingénierie'
  http_path: '/v3/opqibi/unites_legales/309103877/certification_ingenierie'

- name: '[V3] ProBTP Attestations cotisations retraite'
  http_path: '/v3/probtp/etablissements/45309127400036/attestation_cotisations_retraite'

- name: '[V3] ProBTP Conformité cotisations retraite'
  http_path: '/v3/probtp/etablissements/45309127400036/conformite_cotisations_retraite'

- name: '[V3] FNMS Conventions collectives'
  http_path: '/v3/fabrique_numerique_ministeres_sociaux/etablissements/82161143100015/conventions_collectives'

- name: '[V3] RNM Entreprises'
  http_path: '/v3/cma_france/rnm/unites_legales/301123626'

- name: '[V3] QUALIBAT Certifications batiment'
  http_path: '/v3/qualibat/etablissements/78824266700020/certification_batiment'

- name: '[V3] Commission Européenne numéro de TVA'
  http_path: '/v3/european_commission/unites_legales/552032534/numero_tva'

- name: '[V3] Banque de France Bilans'
  http_path: '/v3/banque_de_france/unites_legales/418166096/bilans'

- name: '[V3] CNETP Attestations cotisations conges payes chomages intemperies'
  http_path: '/v3/cnetp/unites_legales/418166096/attestation_cotisations_conges_payes_chomage_intemperies'

- name: '[V3] Douanes Immatriculations EORI'
  http_path: '/v3/douanes/etablissements/41816609600069/immatriculations_eori'

- name: '[V3] DGFIP liasses_fiscales'
  http_path: '/v3/dgfip/unites_legales/418166096/liasses_fiscales/2016'

- name: '[V3] FNTP Carte professionnelle travaux publics'
  http_path: '/v3/fntp/unites_legales/418166096/carte_professionnelle_travaux_publics'

- name: '[V3] INSEE Etablissements diffusibles Adresse'
  http_path: '/v3/insee/sirene/etablissements/diffusibles/41816609600069/adresse'

- name: '[V3] MSA Conformité cotisations'
  http_path: '/v3/msa/etablissements/41816609600069/conformite_cotisations'

- name: "[V4] DJEPVA associations"
  http_path: '/v4/djepva/api-association/associations/775719792'

- name: "[V4] DJEPVA associations open data"
  http_path: '/v4/djepva/api-association/associations/open_data/775719792'

- name: "[V3] GIP-MDS effectifs annuel unité légale"
  http_path: '/v3/gip_mds/unites_legales/552032534/effectifs_annuels/2020'

- name: "[V3] GIP-MDS effectifs mensuels établissement"
  http_path: '/v3/gip_mds/etablissements/84503885000010/effectifs_mensuels/12/annee/2022'
  
- name: "[V3] Qualifelec certificats"
  http_path: '/v3/qualifelec/etablissements/78824266700020/certificats'
