---
## Erreurs communes
- subcode: '999'
  title: 'Erreur inconnue du fournisseur de données'
  detail: "La réponse retournée par le fournisseur de données est invalide et inconnue de notre service. L'équipe technique a été notifiée de cette erreur pour investigation."

- subcode: '000'
  title: 'Erreur interne du fournisseur de données'
  detail: 'La réponse retournée par le fournisseur de données est invalide et a été identifié comme étant une erreur interne. Si le problème persiste, consultez la page de status ou contactez nous sur le support.'

- subcode: '001'
  title: 'Service non disponible'
  detail: 'Service du fournisseur de données temporairement indisponible ou en maintenance.'

- subcode: '002'
  title: 'Intermédiaire hors-délai'
  detail: 'Temps d’attente d’une réponse du fournisseur de données écoulé.'

- subcode: '003'
  title: 'Ressource non trouvée'

- subcode: '004'
  title: 'Erreur de résolution DNS'
  detail: "Problème de résolution DNS de l'adresse du serveur"

- subcode: '005'
  title: 'Indisponible pour des raisons légales'
  detail: "Cette entité n'est accessible par aucun organisme."

- subcode: '006'
  title: "Erreur d'authentification auprès du fournisseur de données"

- subcode: '007'
  title: "Entité disparue"

- subcode: '008'
  title: 'Erreur auprès du fournisseur de données : trop de requêtes'

- subcode: '009'
  title: "Erreur de certificat SSL du fournisseur de données"
  detail: "Le certificat SSL du fournisseur de données est invalide ou expiré."

- subcode: '010'
  title: 'Contenu partiel'
  detail: "Des données n'ont pas pu être récupérées auprès d'un ou plusieurs fournisseurs."

- subcode: '011'
  title: 'Erreur temporaire du fournisseur de données'
  detail: 'Merci de réessayer dans quelques instants'

- code: '00015'
  title: 'Conflit'

- subcode: '015'
  title: 'Conflit'
  detail: 'Plusieurs ressources correspondent aux critères'

- subcode: '020'
  title: 'Maintenance du fournisseur de données'


- code: '00100'
  title: 'Privilèges insuffisants'
  detail:
    api_entreprise: 'Votre token est valide mais vos privilèges sont insuffisants. Listez vos privilèges sur /v2/privileges'
    api_particulier: 'Votre token est valide mais vos privilèges sont insuffisants. Listez vos privilèges sur /api/introspect'
  source: &source_token
    parameter: 'token'

- code: '00101'
  title: 'Interdit'
  detail: "Votre token n'est pas valide ou n'est pas renseigné"
  source: *source_token

- code: '00103'
  title: 'Jeton expiré'
  detail:
    default: "Votre token est expiré. Vous devez refaire une demande"
    api_entreprise: "Votre token est expiré. Vous devez refaire une demande à API Entreprise, un guide est disponible sur https://entreprise.api.gouv.fr/faq#comment-renouveler-mon-jeton-arrivant-a-expiration"
    api_particulier: "Votre token est expiré. Vous devez refaire une demande à API Particulier, un guide est disponible sur https://particulier.api.gouv.fr/faq#comment-renouveler-mon-jeton-arrivant-a-expiration"
  source: *source_token

- code: '00104'
  title: "Mauvaise configuration de l'environnement de staging"
  detail: "Une erreur dans la configuration de notre environnement de staging ne permet pas la génération de l'exemple de test. Une alerte a été remontée."

- code: '00105'
  title: 'Jeton sur liste noire'
  detail: "Votre jeton est sur liste noire, celui-ci a certainement été divulgué sur un canal non-sécurisé. Vous pouvez trouver un jeton valide sur votre espace personnel: %{dashboard_url}"
  source: *source_token

- code: '00106'
  title: 'Jeton non trouvé'
  detail: "Votre jeton n'a pas été trouvé dans la base de données. Il s'agit probablement d'un jeton sans habilitation. Vous devez effectuer une demande à API Entreprise, un guide est disponible sur https://entreprise.api.gouv.fr/demander_un_acces/"
  source: *source_token

- code: '00107'
  title: 'Adresse IP non autorisée'
  detail: "Votre adresse IP n'est pas autorisée à utiliser ce jeton."
  source:
    header: 'X-Forwarded-For'

- code: '00201'
  title: 'Entité non traitable'
  detail: "Le paramètre context est obligatoire"
  source:
    parameter: 'context'

- code: '00202'
  title: 'Entité non traitable'
  detail: "Le paramètre object est obligatoire"
  source:
    parameter: 'object'

- code: '00203'
  title: 'Entité non traitable'
  detail: "Le paramètre recipient est obligatoire"
  source:
    parameter: 'recipient'

- code: '00210'
  title: 'Entité non traitable'
  detail: "Le paramètre recipient n'est pas un siret valide"
  source:
    parameter: 'recipient'

- code: '00211'
  title: "Le paramètre recipient est identique au SIRET/SIREN appelé."
  detail: "Le paramètre recipient est identique au SIRET/SIREN appelé, or ce paramètre de traçabilité doit correspondre au SIRET de l'organisation publique habilitée à utiliser la donnée. Si vous êtes une collectivité ou une administration, ce paramètre doit donc être votre numéro de SIRET ; si vous êtes un éditeur, il s'agit du SIRET de l'organisation publique cliente demandant la donnée."
  source:
    parameter: 'recipient'

- code: '00301'
  title: 'Entité non traitable'
  detail: "Le numéro de siren n'est pas correctement formatté"
  source:
    parameter: 'siren'

- code: '00302'
  title: 'Entité non traitable'
  detail: "Le numéro de siret n'est pas correctement formatté"
  source:
    parameter: 'siret'

- code: '00303'
  title: 'Entité non traitable'
  detail: "Le numéro de siret ou le numéro d'association indiqué n'est pas correctement formatté"
  source:
    parameter: 'id'

- code: '00330'
  title: 'Entité non traitable'
  detail: "Le numéro de siren ou le numéro de siret ou le numéro d'association indiqué n'est pas correctement formatté"
  source:
    parameter: 'id'

- code: '00333'
  title: 'Entité non traitable'
  detail: "Le numéro de siren ou le numéro d'association indiqué n'est pas correctement formatté"
  source:
    parameter: 'id'

- code: '00304'
  title: 'Entité non traitable'
  detail: "Le numéro de siret ou le numéro EORI n'est pas correctement formatté"
  source:
    parameter: 'id'

- code: '00305'
  title: 'Entité non traitable'
  detail: "Le format du mois n'est pas valide"
  source:
    parameter: 'month'

- code: '00306'
  title: 'Entité non traitable'
  detail: "Le code INSEE commune n'est pas correctement formaté"

- code: '00307'
  title: 'Entité non traitable'
  detail: "L'année n'est pas correctement formatée"

- code: '00315'
  title: 'Entité non traitable'
  detail: "L'année n'est pas valide : elle doit être comprise entre 2006 et l'année précédente"

- code: '00308'
  title: 'Entité non traitable'
  detail: "Le user_id n'est pas correctement formaté"

- code: '00309'
  title: 'Entité non traitable'
  detail: 'Invalide request_name'

- code: '00310'
  title: 'Entité non traitable'
  detail: "Le type d'attestation indiqué n'est pas correctement formatté (uniquement: AVG_UR)"

- code: '00311'
  title: 'Entité non traitable'
  detail: "Le siren_is n'est pas correctement formatté"
  source:
    parameter: 'siren_is'

- code: '00312'
  title: 'Entité non traitable'
  detail: "Le siren_tva n'est pas correctement formatté"
  source:
    parameter: 'siren_tva'

- code: '00313'
  title: 'Entité non traitable'
  detail: "Le paramètre limit n'est pas correctement formatté"
  source:
    parameter: 'limit'

- code: '00314'
  title: 'Entité non traitable'
  detail: "Le paramètre uuid n'est pas correctement formatté"
  source:
    parameter: 'uuid'

- code: '00351'
  title: 'Entité non traitable'
  detail: "Le code postal n'est pas correctement formatté"

- code: '00352'
  title: 'Entité non traitable'
  detail: "Le numéro d'allocataire n'est pas correctement formatté"

- code: '00360'
  title: 'Entité non traitable'
  detail: "Le numéro d'INE n'est pas correctement formatté"

- code: '00361'
  title: 'Entité non traitable'
  detail: "Le nom de famille est manquant"

- code: '00362'
  title: 'Entité non traitable'
  detail: "Le prénom est manquant"

- code: '00363'
  title: 'Entité non traitable'
  detail: "La date de naissance n'est pas correctement formatté"

- code: '00364'
  title: 'Entité non traitable'
  detail: "Le sexe n'est pas correctement formaté (m ou f)"

- code: '00365'
  title: 'Entité non traitable'
  detail: "Le lieu de naissance n'est pas correctement formaté"

- code: '00366'
  title: 'Entité non traitable'
  detail: "Un ou plusieurs paramètres de civilité ne sont pas correctement formatés"

- code: '00367'
  title: 'Entité non traitable'
  detail: "Le ou les prénoms sont manquants."

- code: '00368'
  title: 'Entité non traitable'
  detail: "L'année de campagne (campaignYear) n'est pas correctement formatée: doit être comprise entre 2021 et l'année courante - 1"

- code: '00370'
  title: 'Entité non traitable'
  detail: "Le numéro fiscal n'est pas correctement formaté"

- code: '00371'
  title: 'Entité non traitable'
  detail: "La référence de l'avis n'est pas correctement formatée"

- code: '00380'
  title: 'Entité non traitable'
  detail: "L'identifiant est manquant"

- code: '00390'
  title: 'Entité non traitable'
  detail: "La valeur de la profondeur n'est pas valide: celle-ci doit être comprise entre 1 et 13"

- code: '00391'
  title: 'Entité non traitable'
  detail: "Les paramètres d'identité correspondent à plusieurs personnes. Nous ne pouvons pas fournir les informations de service civique pour cet individu."

- code: '00400'
  title: 'Entité non traitable'
  detail: "Le code pays INSEE n'est pas correctement formaté"

- code: '00401'
  title: 'Entité non traitable'
  detail: "Le request_id n'est pas correctement formaté"

- code: '00410'
  title: 'Entité non traitable'
  detail: "Le code établissement n'est pas correctement formaté: celui doit être composé de 7 chiffres et 1 lettre"

- code: '00411'
  title: 'Entité non traitable'
  detail: "L'année scolaire n'est pas correctement formatée: doit être sur le format YYYY ou YYYY-YYYY)"

- code: '00412'
  title: 'Entité non traitable'
  detail: "Le degré d'établissement n'est pas correctement formaté: doit être 1D ou 2D"

- code: '00413'
  title: 'Entité non traitable'
  detail: "Le périmètre géographique est invalide: exactement un type de périmètre doit être fourni"

- code: '00419'
  title: 'Entité non traitable'
  detail: "Les paramètres codeEtablissement et périmètre (codesBcnRegions/codesBcnDepartements) sont mutuellement exclusifs"

- code: '00414'
  title: 'Entité non traitable'
  detail: "Les valeurs du périmètre sont invalides: doit être un tableau non vide"

- code: '00416'
  title: 'Entité non traitable'
  detail: "Le code département BCN MEN est invalide: valeur non reconnue"

- code: '00417'
  title: 'Entité non traitable'
  detail: "Le code région BCN MEN est invalide: valeur non reconnue"

- code: '00420'
  title: 'Entité non traitable'
  detail: "Le nom de naissance est manquant"

- code: '00421'
  title: 'Entité non traitable'
  detail: "Le(s) prenom(s) est manquant"

- code: '00422'
  title: 'Entité non traitable'
  detail: "L'annee de naissance est manquante"

- code: '00423'
  title: 'Entité non traitable'
  detail: "Le mois de naissance est manquant"

- code: '00424'
  title: 'Entité non traitable'
  detail: "Le jour de naissance est manquant"

- code: '00425'
  title: 'Entité non traitable'
  detail: "La date de naissance n'est pas valide"

- code: '00426'
  title: 'Entité non traitable'
  detail: "Le code cog de la commune de naissance est manquant"

- code: '00427'
  title: 'Entité non traitable'
  detail: "Le sexe de l'état civil est manquant"

- code: '00428'
  title: 'Entité non traitable'
  detail: "Le code cog du département de naissance est manquant ou invalide"

- code: '00430'
  title: 'Entité non traitable'
  detail: "L'immatriculation du véhicule est manquante"

- code: '00402'
  title: Version d'API non prise en charge

- code: '00403'
  title: 'Lien expiré'
  detail: 'Le lien de téléchargement est expiré.'

- code: '00500'
  title: "Erreur interne"
  detail: "Une erreur interne a été détectée, l'équipe d'API Entreprise a été notifié de l'erreur."

- code: '00501'
  title: 'Erreur réseau'
  detail: "Problème de connexion au serveur distant. L'erreur peut venir soit du fournisseur, soit de API Entreprise. Il s'agit souvent d'une erreur temporaire."

- code: '00502'
  title: "Erreur réseau du service d'hébergement de données"
  detail: "Problème de connexion au serveur d'hébergement de données. L'erreur peut venir soit du fournisseur, soit de API Entreprise"

- code: '00503'
  title: 'Fonctionnalité non implémentée'
  detail: 'Fonctionnalité non implémentée pour le moment'

## Proxy file errors (006xx)
- code: '00601'
  title: 'Accès au fichier refusé'
  detail: "L'accès au fichier distant a été refusé par le fournisseur."

- code: '00602'
  title: 'Trop de requêtes'
  detail: "Le fournisseur du fichier a rejeté la requête car le quota est dépassé. Veuillez réessayer ultérieurement."

- code: '00603'
  title: 'Erreur interne du fournisseur de fichier'
  detail: "Le fournisseur du fichier a rencontré une erreur interne."

- code: '00604'
  title: 'Passerelle invalide'
  detail: "Une erreur de passerelle s'est produite lors de la récupération du fichier."

- code: '00605'
  title: 'Service de fichier indisponible'
  detail: "Le service de fichier est temporairement indisponible. Veuillez réessayer ultérieurement."

- code: '00606'
  title: 'Délai de récupération dépassé'
  detail: "Le fournisseur du fichier n'a pas répondu dans le délai imparti."

## Providers
### INSEE

- code: '01501'
  title: 'Mauvaise réponse du fournisseur de données'
  detail: "L'INSEE a répondu avec une réponse comportant plusieurs établissements"

### RNA

- code: '07501'
  title: 'Mauvaise réponse du fournisseur de données'
  detail: "Echec lors du parcours du fichier XML rna association."

## INPI

- code: '05501'
  title: 'Mauvaise réponse du fournisseur de données'
  detail: "Les IDs fichiers renvoyés par l'INPI sont incorrects"

- code: '05502'
  title: 'Mauvaise réponse du fournisseur de données'
  detail: 'Echec lors du parsing de la réponse JSON des brevets INPI'

- code: '05503'
  title: 'Mauvaise réponse du fournisseur de données'
  detail: 'Echec lors du parsing de la réponse JSON des modèles INPI'

- code: '05504'
  title: 'Mauvaise réponse du fournisseur de données'
  detail: 'Echec lors du parsing de la réponse JSON des marques INPI'

## DGFIP

- code: '03501'
  title: 'Potentielle ressource non trouvée'
  detail: "Le serveur a renvoyé une erreur interne, mais cela peut aussi indiquer que le siret ou siren renseigné n'existe pas, n'est pas connu, n'est pas en règle de ses obligations fiscales ou ne comporte aucune information pour cet appel."

- code: '03510'
  title: 'Limitation de débit'
  detail: "Le fournisseur de données a rejeté la demande en raison d'un trop grand nombre d'échecs antérieurs."

## CNAV

- code: '00353'
  title: 'Entité non traitable'
  detail: "L'année demandée n'est pas correctement formatée ou est dans le futur."

- code: '00356'
  title: 'Entité non traitable'
  detail: "L'année demandée doit être l'année en cours (N), N-1 ou N-2."

- code: '00354'
  title: 'Entité non traitable'
  detail: "Le mois demandé est incorrect ou est dans le futur."

- code: '00355'
  title: Impossible d'identifier l'allocataire
  detail: "Les paramètres fournis ne permettent pas d'identifier un allocataire."

## BDF

- code: '17501'
  title: 'Erreur de base de données de la Banque de France'
  detail: "Les serveurs de la Banque de France rencontrent une erreur de base de données"

- code: '17502'
  title: 'Erreur interne de la Banque de France'
  detail: "Les serveurs de la Banque de France rencontrent une erreur interne"

## ACOSS

- code: '04101'
  title: 'Réponse invalide'

- code: '04102'
  title: 'Code erreur non supporté'

- code: '04501'
  title: 'Analyse manuelle de la situation du compte en cours'
  detail: "Une analyse humaine par un agent des URSSAF est requise. Le temps de traitement est très variable selon de la complexité de situation, la demande de pièces justificatives complémentaires ou la charge de travail des agents."

- code: '04502'
  title: "Demande de traitement logiciel en cours"
  detail: "Une erreur informatique a eu lieu, une demande de traitement par le logiciel est en cours."

- code: '04503'
  title: "La situation du compte ne permet pas de délivrer l'attestation demandée"
  detail: "Il n'est pas possible de renvoyer l'attestation. Cela peut être dû au fait qu'un des établissements d'une entreprise n'a pas retourné les informations."

- code: '31501'
  title: 'Erreur interne du GIP-MDS'
  detail: "Les serveurs du GIP-MDS rencontrent une erreur interne impliquant une indisponibilité momentanée"

- code: '31502'
  title: "Erreur temporaire d'authentification au GIP-MDS"
  detail: "Les serveurs du GIP-MDS rencontrent une erreur interne impliquant une erreur momentanée d'authentification, veuillez réessayer votre appel dans quelques secondes."

- code: '31503'
  title: "Erreur de quota du GIP-MDS"
  detail: "Les serveurs du GIP-MDS nous renvoi une erreur 429 indiquant que nous avons dépassé les quotas d'appel alloués à notre application, veuillez réessayer votre appel plus tard."

## Infogreffe
- code: '02501'
  title: "Erreur temporaire d'identification d'Infogreffe"
  detail: "Une erreur d'identification a été relevée par le système, il s'agit généralement d'une erreur temporaire, veuillez réessayer dans quelques secondes."

- code: '02502'
  title: "Erreur de génération de commande d'Infogreffe"
  detail: "Une erreur du fournisseur de données empêche la délivrance des informations, il s'agit certainement d'un numéro de siren hors périmètre."

## CNAF

- code: '23502'
  title: 'Quotient familial manquant'
  detail: 'Le bénéficiaire a bien été trouvé mais la réponse du fournisseur de données ne retourne pas de quotient familial.'

## DSNJ

- code: '39400'
  title: "Age non pertinent pour le Service National"
  detail: "L'age renseigné n'est pas compris entre 16 et 25 ans incluts, et n'est donc pas concerné par le Service National."

## FranceConnect

- code: '50001'
  detail: "Le jeton d'accès est mal formaté."

- code: '50002'
  detail: "Le jeton d'accès n'a pas été trouvé ou est expiré."

- code: '50003'
  detail: "Le jeton d'accès ne possède pas les données pivot requises pour effectuer cet appel."
