---
production: &shared
  'DGFIP':
    from_hour: '01:00'
    to_hour: '02:00'
    dates:
      - day: '2022-03-25'
        from_hour: '18:30'
        to_hour:  '23:59'
      - day: '2022-03-26'
        from_hour: '00:01'
        to_hour:  '23:59'
      - day: '2022-03-27'
        from_hour: '00:01'
        to_hour:  '23:59'
      - day: '2022-03-28'
        from_hour: '00:01'
        to_hour:  '07:30'
  'Banque de France':
    from_hour: '23:00'
    to_hour:  '08:00'
  'INSEE':
    dates:
      - day: '2022-03-24'
        from_hour: '08:00'
        to_hour:  '14:00'
sandbox: *shared
staging: *shared
development: *shared
test:
  'provider_which_has_a_window_within_same_day':
    from_hour: '01:00'
    to_hour: '02:00'
  'provider_which_has_a_window_across_two_day':
    from_hour: '23:00'
    to_hour:  '08:00'
  'provider_which_has_specific_dates':
    dates:
      - day: '2021-01-14'
        from_hour: '08:00'
        to_hour:  '19:00'
      - day: '2021-01-15'
        from_hour: '13:00'
        to_hour:  '16:00'
  'INSEE':
    from_hour: '03:00'
    to_hour: '04:00'
