---
production: &shared
  'DGFIP':
    from_hour: '01:00'
    to_hour: '02:00'
  'Banque de France':
    from_hour: '23:00'
    to_hour:  '08:00'
development: *shared
test:
  <<: *shared
  'window_within_same_day':
    from_hour: '01:00'
    to_hour: '02:00'
  'window_across_two_day':
    from_hour: '23:00'
    to_hour:  '08:00'
  'INSEE':
    from_hour: '02:00'
    to_hour: '05:00'
