---
production: &shared
  'CNETP':
    from_hour: '06:00'
    to_hour: '06:30'
  'DGFIP - Adélie':
    from_hour: '01:00'
    to_hour: '02:00'
  'MEN':
    from_hour: '01:10'
    to_hour: '02:30'
  'MSA':
    from_hour: '03:00'
    to_hour: '03:30'
  'Banque de France':
    from_hour: '22:04'
    to_hour: '22:08'
  'CNAF & MSA':
    from_hour: '23:00'
    to_hour: '23h45'
    day: 'sunday'
  'GIP-MDS':
    dates:
      - day: '2025-03-20'
        from_hour: '13:00'
        to_hour: '17:00'

sandbox: *shared
staging: *shared
development: *shared
test:
  'provider_which_has_a_window_within_same_day':
    from_hour: '01:00'
    to_hour: '02:00'
  'provider_which_has_a_window_every_week':
    from_hour: '01:00'
    to_hour: '04:00'
    day: 'monday'
  'provider_which_has_a_window_across_two_day':
    from_hour: '23:00'
    to_hour:  '08:00'
  'provider_which_has_specific_dates':
    dates:
      - day: '2021-01-14'
        from_hour: '08:00'
        to_hour:  '19:00'
      - day: '2021-01-15'
        from_hour: '13:00'
        to_hour:  '16:00'
  'dummy_maintenance':
    from_hour: '01:00'
    to_hour: '01:02'
  'INSEE':
    from_hour: '03:00'
    to_hour: '04:00'
