---
test:
  api_kind:
    with_retriever:
      kind: 'retriever'
      driver_params:
        retriever: 'CNAF::QuotientFamilial'
        params:
          beneficiary_number: '<%= Siade.credentials[:ping_cnaf_numero_allocataire] %>'
          postal_code: '<%= Siade.credentials[:ping_cnaf_postal_code] %>'
    with_retriever_and_cache:
      kind: 'retriever'
      cache: <%= 5.minutes %>
      driver_params:
        retriever: 'CNAF::QuotientFamilial'
        params:
          beneficiary_number: '<%= Siade.credentials[:ping_cnaf_numero_allocataire] %>'
          postal_code: '<%= Siade.credentials[:ping_cnaf_postal_code] %>'
    with_access_logs:
      kind: 'access_logs'
      driver_params:
        period: <%= 5.minutes %>
        routes:
          - 'api_kind/api1/source1#show'
          - 'api_kind/api2/source2#show'
    with_make_request:
      kind: 'make_request'
      driver_params:
        make_request: 'CNAF::QuotientFamilial'
        status_to_check: 404
        params:
          postal_code: '75001'
          beneficiary_number: '1234567'
    with_make_request_and_token:
      kind: 'make_request'
      driver_params:
        make_request: 'PoleEmploi::Statut::MakeRequest'
        status_to_check: 404
        params:
          identifiant_pole_emploi: 'identifiant'
          user_id: '22222222-2222-2222-2222-222222222222'
        token_interactor: 'PoleEmploi::Authenticate'

shared:
  api_particulier:
    caf:
      kind: 'retriever'
      cache: <%= 2.minutes %>
      driver_params:
        retriever: 'CNAF::QuotientFamilial'
        params:
          beneficiary_number: '<%= Siade.credentials[:ping_cnaf_numero_allocataire] %>'
          postal_code: '<%= Siade.credentials[:ping_cnaf_postal_code] %>'
    impots:
      kind: 'retriever'
      cache: <%= 2.minutes %>
      driver_params:
        retriever: 'DGFIP::SituationIR'
        params:
          tax_number: '<%= Siade.credentials[:ping_dgfip_svair_numero_fiscal] %>'
          tax_notice_number: '<%= Siade.credentials[:ping_dgfip_svair_reference_avis] %>'
    pole_emploi_status:
      kind: 'retriever'
      cache: <%= 2.minutes %>
      driver_params:
        retriever: 'PoleEmploi::Statut'
        params: &pole_emploi_params
          identifiant_pole_emploi: 'azerty'
          user_id: '22222222-2222-2222-2222-222222222222'
    pole_emploi_indemnites:
      kind: 'make_request'
      cache: <%= 2.minutes %>
      driver_params:
        make_request: 'PoleEmploi::Indemnites'
        params: *pole_emploi_params
        status_to_check: 404
        token_interactor: 'PoleEmploi::Authenticate'
    men_scolarite:
      kind: 'make_request'
      cache: <%= 2.minutes %>
      driver_params:
        make_request: 'MEN::Scolarites::MakeRequest'
        params:
          family_name: 'Dupont'
          first_name: 'Jean'
          gender: 'f'
          birth_date: '2000-01-01'
          code_etablissement: '0511474A'
          annee_scolaire: '<%= Date.today.year - 1 %>-<%= Date.today.year - 2 %>'
        status_to_check: 404
        token_interactor: 'MEN::Scolarites::Authenticate'

    cnous_etudiant_boursier_ine:
      kind: 'make_request'
      cache: <%= 2.minutes %>
      driver_params:
        make_request: 'CNOUS::StudentScholarshipWithINE::MakeRequest'
        params:
          ine: '1234567890G'
        status_to_check: 404
        token_interactor: 'CNOUS::Authenticate'

    cnous_etudiant_boursier_identite:
      kind: 'make_request'
      cache: <%= 2.minutes %>
      driver_params:
        make_request: 'CNOUS::StudentScholarshipWithCivility::MakeRequest'
        params:
          family_name: 'DUPONT'
          first_names:
            - 'Jean'
            - 'Jacques'
          birth_date: '2000-01-01'
          birth_place: 'Paris'
          gender: 'M'
        status_to_check: 404
        token_interactor: 'CNOUS::Authenticate'

    cnous_etudiant_boursier_france_connect:
      kind: 'make_request'
      cache: <%= 2.minutes %>
      driver_params:
        make_request: 'CNOUS::StudentScholarshipWithFranceConnect::MakeRequest'
        params:
          given_name: 'Jean Martin'
          family_name: 'DUPONT'
          birthdate: '2000-01-01'
          gender: 'male'
          birthplace: '75101'
          birthcountry: '99100'
          preferred_username: 'jdupont'
        status_to_check: 404
        token_interactor: 'CNOUS::Authenticate'

    franceconnect:
      kind: 'make_request'
      cache: <%= 2.minutes %>
      driver_params:
        make_request: 'FranceConnect::DataFetcherThroughAccessToken::MakeRequest'
        params:
          token: 'token'
        status_to_check: 400

  api_entreprise:
    insee/sirene:
      kind: 'retriever'
      cache: <%= 2.minutes %>
      driver_params:
        retriever: 'INSEE::Etablissement'
        params:
          siret: '30613890002979'
    urssaf/attestation_sociale:
      kind: 'access_logs'
      cache: <%= 5.minutes %>
      driver_params:
        period: <%= 10.minutes %>
        routes:
          - 'api_entreprise/v3_and_more/acoss/attestations_sociales#show'
    infogreffe/rcs:
      kind: 'retriever'
      cache: <%= 2.minutes %>
      driver_params:
        retriever: 'Infogreffe::ExtraitsRCS'
        params:
          siren: '831386297'
    inpi/rne:
      kind: 'retriever'
      cache: <%= 10.minutes %>
      driver_params:
        retriever: 'INPI::RNE::BeneficiairesEffectifs'
        params:
          siren: '900225095'

    djepva/api-association:
      kind: 'retriever'
      cache: <%= 5.minutes %>
      driver_params:
        retriever: 'DJEPVA::UniteLegale'
        params:
          id: 'W131015526'

    banque_de_france/bilans:
      kind: 'retriever'
      cache: <%= 10.minutes %>
      driver_params:
        retriever: 'BanqueDeFrance::BilansEntreprise'
        params:
          siren: '418166096'

    cnetp/attestation_cotisations_conges_payes_chomage_intemperies:
      kind: 'retriever'
      cache: <%= 5.minutes %>
      driver_params:
        retriever: 'CNETP::AttestationCotisationsCongesPayesChomageIntemperies'
        params:
          siren: '811214428'
    msa/conformite_cotisations:
      kind: 'retriever'
      cache: <%= 5.minutes %>
      driver_params:
        retriever: 'MSA::ConformitesCotisations'
        params:
          siret: '95086311800010'
    opqibi/certification_ingenierie:
      kind: 'retriever'
      cache: <%= 5.minutes %>
      driver_params:
        retriever: 'OPQIBI::CertificationsIngenierie'
        params:
          siren: '309103877'
    fntp/carte_professionnelle_travaux_publics:
      kind: 'retriever'
      cache: <%= 10.minutes %>
      driver_params:
        retriever: 'FNTP::CarteProfessionnelleTravauxPublics'
        params:
          siren: '385407184'
    ademe/certification_rge:
      kind: 'retriever'
      cache: <%= 2.minutes %>
      driver_params:
        retriever: 'ADEME::CertificatsRGE'
        params:
          siret: '50530961700023'
    european_commission/numero_tva:
      kind: 'retriever'
      cache: <%= 10.minutes %>
      driver_params:
        retriever: 'EuropeanCommission::VIES'
        params:
          siren: '552032534'
    gip_mds/effectifs:
      kind: 'retriever'
      cache: <%= 10.minutes %>
      driver_params:
        retriever: 'GIPMDS::EffectifsAnnuelsEntreprise'
        params:
          siren: '552032534'
          year: '2020'
    fabrique_numerique_ministeres_sociaux/conventions_collectives:
      kind: 'retriever'
      cache: <%= 1.minute %>
      driver_params:
        retriever: 'FabriqueNumeriqueMinisteresSociaux::ConventionsCollectives'
        params:
          siret: '89337342300019'
    douanes/immatriculations_eori:
      kind: 'retriever'
      cache: <%= 5.minutes %>
      driver_params:
        retriever: 'DGDDI::EORI'
        params:
          siret_or_eori: 'FR16002307300010'
    qualifelec/certificats:
      kind: 'retriever'
      cache: <%= 1.minute %>
      driver_params:
        retriever: 'Qualifelec::Certificats'
        params:
          siret: '42054064300376'
