shared:
  - name: ANCT
    siret: '13002603200016'
  - name: REGION AUVERGNE-RHONE-ALPES
    siret: '20005376700014'
  - name: REGION BOURGOGNE-FRANCHE-COMTE
    siret: '20005372600028'
  - name: REGION CENTRE-VAL DE LOIRE
    siret: '23450002300028'
  - name: REGION DES PAYS DE LA LOIRE
    siret: '23440003400026'
  - name: REGION OCCITANIE
    siret: '20005379100014'
  - name: REGION NORMANDIE
    siret: '20005340300057'
  - name: REGION ILE DE FRANCE
    siret: '23750007900312'
  - name: REGION HAUTS-DE-FRANCE
    siret: '20005374200017'
  - name: COLLECTIVITE DE CORSE
    siret: '20007695800012'
  - name: REGION GRAND EST
    siret: '20005226400013'
  - name: REGION NOUVELLE-AQUITAINE
    siret: '20005375900011'
  - name: REGION PROVENCE-ALPES-COTE D'AZUR
    siret: '23130002100012'
  - name: REGION BRETAGNE
    siret: '23350001600040'
