---
insee:
  entreprise:
    attributes:
      siret_siege_social:
        type: 'string'
        example: '13002526500013'
        description: "Numéro de SIRET du siège social"
      type:
        type: 'string'
        enum:
        - 'personne_physique'
        - 'personne_morale'
        example: 'personne_morale'
        description: "Détermine si l'entreprise est une personne morale ou une personne physique.
          Cette valeur est déterminée à l'aide du code juridique : 1000 correspond à une personne physique."
      personne_morale_attributs:
        type: 'object'
        description: "Attributs associé à la personne morale. L'ensemble des valeurs sont à
          null pour les personnes physiques."
        properties:
          raison_sociale:
            type: 'string'
            example: 'DINUM'
            nullable: true
            description: "Raison sociale de l'entreprise"
      personne_physique_attributs:
        type: 'object'
        description: "Attributs associé à la personne physique. L'ensemble des
          valeurs sont à null pour les personnes morales."
        properties:
          pseudonyme:
            type: 'string'
            example: "DJ Falcon"
            nullable: true
            description: "Le pseudonyme correspond au nom qu'une
              personne utilise pour se désigner dans l'exercice
              de son activité, généralement littéraire ou artistique."
          prenom_usuel:
            type: 'string'
            example: 'Jean'
            nullable: true
            description: "Le prénom usuel est le prénom par lequel
              une personne choisit de se faire appeler dans la
              vie courante, parmi l'ensemble de ceux qui lui ont
              été donnés à sa naissance et qui sont inscrits à
              l'état civil."
          prenom_1:
            type: 'string'
            example: 'Jean'
            nullable: true
            description: 'Prénom numéro 1 déclaré'
          prenom_2:
            type: 'string'
            example: 'Jacques'
            nullable: true
            description: 'Prénom numéro 2 déclaré'
          prenom_3:
            type: "string"
            example: "Pierre"
            nullable: true
            description: "Prénom numéro 3 déclaré"
          prenom_4:
            type: "string"
            example: "Paul"
            nullable: true
            description: "Prénom numéro 4 déclaré"
          nom_usage:
            type: "string"
            example: "Dupont"
            nullable: true
            description: "Nom que la personne physique a choisi d'utiliser"
          nom_naissance:
            type: "string"
            example: "Dubois"
            nullable: true
            description: "Nom de naissance"
          sexe:
            type: 'string'
            example: 'M'
            enum:
              - 'M'
              - 'F'
              - null
            nullable: true
            description: "Caractère féminin ou masculin de la personne
              physique. Cette valeur peut ne pas être renseignée
              pour une personne physique."
      categorie_entreprise:
        type: 'string'
        example: 'GE'
        enum:
        - 'GE'
        - 'ETI'
        - 'PME'
        - null
        description: "Catégorie de l'entreprise. Il s'agit d'une
          variable statistique calculée par l'INSEE. Elle ne peut
          prendre que 3 valeurs:
          \n
          \n
          - GE: Grande Entreprise\n
          - ETI: Entreprise de Taille Intermédiaire\n
          - PME: Petite ou Moyenne Entreprise\n
          \n
          \n
          Celle-ci peut-être nulle dans
          certains cas : il s’agit soit d’une unité légale nouvellement
          créée, soit d’une unité légale cessée, soit d’une unité
          légale hors champ du calcul de la catégorie (unité légale
          agricole ou ne faisant pas partie du système productif)
          \n
          \n
          La définition peut-être trouvée sur le lien suivant : https://www.insee.fr/fr/metadonnees/definition/c1057"
      numero_tva_intracommunautaire:
        type: 'string'
        example: 'FR07130025265'
        description: "Numéro de TVA intracommunautaire. Cette
          valeur est calculée à l'aide du numéro de siren, cette
          donnée est donc théorique: une entreprise dont le siège
          social se trouve à l'étranger n'a probablement pas
          de numéro de TVA français."
      diffusable_commercialement:
        type: 'boolean'
        example: true
        description: "Détermine si l'entreprise est une entreprise
          non-diffusible. Si celle-ci est non-diffusible, ses
          informations ne doivent en aucun cas être accessibles
          au grand public."
      forme_juridique:
        type: 'object'
        properties:
          code:
            type: "string"
            example: '7120'
            description: "Code de la forme juridique de l'entreprise.
              Cette variable est à 1000 pour les personnes physiques.
              \n
              \n
              La liste complète se trouve ici: https://www.insee.fr/fr/information/2028129"
          libelle:
            type: 'string'
            example: "Service central d'un ministère
            description: Libellé associé au code de la forme juridique
              de l'entreprise. Si le code ne correspond à aucun
              libellé la valeur 'non référencé' est utilisée."
      activite_principale:
        type: 'object'
        properties:
          code:
            type: 'string'
            example: '8411Z'
            description: "Code de l'activité principale (APE) de
              l'entreprise. Ce code est extrait de la nomenclature
              NAF. A noter qu'une entreprise n'ayant pas encore
              de code APE peut se voir affecter la valeur 00.00Z
              de manière provisoire."
          libelle:
            type: 'string'
            nullable: true
            example: "Administration publique générale"
            description: "Libellé associé au code APE. Si le code
              n'est pas renseigné dans la nomenclature 'Naf Rév2'
              (nomenclature en vigueur), le libellé n'est pas
              renseigné ici. Si le code ne correspond à aucun
              libellé au sein de la nomenclature 'Naf Rév2', la
              valeur 'non référencé' est utilisée.
              \n
              \n
              Le lien vers la nomenclature 'Naf Rév2' : https://www.insee.fr/fr/information/2406147"
          nomenclature:
            type: 'string'
            example: 'NAFRev2'
            description: 'Nomenclature associée au code'
      tranche_effectif_salarie:
        type: 'object'
        properties:
          code:
            type: 'string'
            nullable: true
            example: '51'
          intitule:
            type: 'string'
            nullable: true
            example: "2 000 à 4 999 salariés"
          date_reference:
            type: 'string'
            nullable: true
            example: '2016'
          de:
            type: 'integer'
            example: 2000
            nullable: true
          a:
            type: "integer"
            example: 4999
            nullable: true
      etat_administratif:
        type: 'string'
        enum:
          - 'A'
          - 'C'
        example: 'A'
      date_cessation:
        type: 'integer'
        nullable: true
        example: 1634133818
      date_creation:
        type: 'integer'
        example: 1634103818
    links:
      siege_social:
        type: 'string'
        example: 'https://entreprises.api.gouv.fr/api/v3/insee/etablissements/30613890001294'
        description: "Lien vers la ressource établissement correspondant au siège social"
      siege_social_adresse:
        type: 'string'
        example: "https://entreprises.api.gouv.fr/api/v3/insee/etablissements/30613890001294/adresse"
        description: "Lien vers la ressource adresse de l'établissement correspondant au siège social"
    meta:
      date_derniere_mise_a_jour:
        type: 'integer'
        example: 1618396818
        description: "Date de la dernière mise à jour à l'INSEE"
