---
mandatory_params:
  context: "**Cadre de la requête**
    \n
    \n
    Par exemple : aides publiques, marchés publics ou gestion d’un référentiel tiers utilisé pour tel type d’application."
  recipient: "**Bénéficiaire de l’appel**
    \n
    \n
    SIRET de l’administration destinatrice des données."
  object: "**La raison de l’appel ou l’identifiant de la procédure.**
    \n
    \n
    L’identifiant peut être interne à votre organisation ou bien un numéro de marché publique, un nom de procédure ; l’essentiel est que celui-ci vous permette de tracer et de retrouver les informations relatives à l’appel. En effet, vous devez pouvoir justifier de la raison d’un appel auprès du fournisseur de données. Description courte ( < 50 caractères )."
insee:
  entreprise:
    attributes: &insee_entreprise_attributes
      siret_siege_social:
        type: 'string'
        example: '13002526500013'
        description: "Numéro de SIRET du siège social"
      type:
        type: 'string'
        enum:
        - 'personne_physique'
        - 'personne_morale'
        example: 'personne_morale'
        description: "Détermine si l'entreprise est une personne morale ou une personne physique.
          Cette valeur est déterminée à l'aide du code juridique : 1000 correspond à une personne physique."
      personne_morale_attributs:
        type: 'object'
        description: "Attributs associé à la personne morale. L'ensemble des valeurs sont à
          null pour les personnes physiques."
        properties:
          raison_sociale:
            type: 'string'
            example: 'DINUM'
            nullable: true
            description: "Raison sociale de l'entreprise"
      personne_physique_attributs:
        type: 'object'
        description: "Attributs associé à la personne physique. L'ensemble des
          valeurs sont à null pour les personnes morales."
        properties:
          pseudonyme:
            type: 'string'
            example: "DJ Falcon"
            nullable: true
            description: "Le pseudonyme correspond au nom qu'une
              personne utilise pour se désigner dans l'exercice
              de son activité, généralement littéraire ou artistique."
          prenom_usuel:
            type: 'string'
            example: 'Jean'
            nullable: true
            description: "Le prénom usuel est le prénom par lequel
              une personne choisit de se faire appeler dans la
              vie courante, parmi l'ensemble de ceux qui lui ont
              été donnés à sa naissance et qui sont inscrits à
              l'état civil."
          prenom_1:
            type: 'string'
            example: 'Jean'
            nullable: true
            description: 'Prénom numéro 1 déclaré'
          prenom_2:
            type: 'string'
            example: 'Jacques'
            nullable: true
            description: 'Prénom numéro 2 déclaré'
          prenom_3:
            type: "string"
            example: "Pierre"
            nullable: true
            description: "Prénom numéro 3 déclaré"
          prenom_4:
            type: "string"
            example: "Paul"
            nullable: true
            description: "Prénom numéro 4 déclaré"
          nom_usage:
            type: "string"
            example: "Dupont"
            nullable: true
            description: "Nom que la personne physique a choisi d'utiliser"
          nom_naissance:
            type: "string"
            example: "Dubois"
            nullable: true
            description: "Nom de naissance"
          sexe:
            type: 'string'
            example: 'M'
            enum:
              - 'M'
              - 'F'
              - null
            nullable: true
            description: "Caractère féminin ou masculin de la personne
              physique. Cette valeur peut ne pas être renseignée
              pour une personne physique."
      categorie_entreprise:
        type: 'string'
        example: 'GE'
        enum:
        - 'GE'
        - 'ETI'
        - 'PME'
        - null
        description: "Catégorie de l'entreprise. Il s'agit d'une
          variable statistique calculée par l'INSEE. Elle ne peut
          prendre que 3 valeurs:
          \n
          \n
          - GE: Grande Entreprise\n
          - ETI: Entreprise de Taille Intermédiaire\n
          - PME: Petite ou Moyenne Entreprise\n
          \n
          \n
          Celle-ci peut-être nulle dans
          certains cas : il s’agit soit d’une unité légale nouvellement
          créée, soit d’une unité légale cessée, soit d’une unité
          légale hors champ du calcul de la catégorie (unité légale
          agricole ou ne faisant pas partie du système productif)
          \n
          \n
          La définition peut-être trouvée sur le lien suivant : https://www.insee.fr/fr/metadonnees/definition/c1057"
      numero_tva_intracommunautaire:
        type: 'string'
        example: 'FR07130025265'
        description: "Numéro de TVA intracommunautaire. Cette
          valeur est calculée à l'aide du numéro de siren, cette
          donnée est donc théorique: une entreprise dont le siège
          social se trouve à l'étranger n'a probablement pas
          de numéro de TVA français."
      diffusable_commercialement:
        type: 'boolean'
        example: true
        description: "Détermine si l'entreprise est une entreprise
          non-diffusible. Si celle-ci est non-diffusible, ses
          informations ne doivent en aucun cas être accessibles
          au grand public."
      forme_juridique:
        type: 'object'
        properties:
          code:
            type: "string"
            example: '7120'
            description: "Code de la forme juridique de l'entreprise.
              Cette variable est à 1000 pour les personnes physiques.
              \n
              \n
              La liste complète se trouve ici: https://www.insee.fr/fr/information/2028129"
          libelle:
            type: 'string'
            example: "Service central d'un ministère
            description: Libellé associé au code de la forme juridique
              de l'entreprise. Si le code ne correspond à aucun
              libellé la valeur 'non référencé' est utilisée."
      activite_principale:
        type: 'object'
        properties:
          code:
            type: 'string'
            example: '8411Z'
            description: "Code de l'activité principale (APE) de
              l'entreprise. Ce code est extrait de la nomenclature
              NAF. A noter qu'une entreprise n'ayant pas encore
              de code APE peut se voir affecter la valeur 00.00Z
              de manière provisoire."
          libelle:
            type: 'string'
            nullable: true
            example: "Administration publique générale"
            description: "Libellé associé au code APE. Si le code
              n'est pas renseigné dans la nomenclature 'Naf Rév2'
              (nomenclature en vigueur), le libellé n'est pas
              renseigné ici. Si le code ne correspond à aucun
              libellé au sein de la nomenclature 'Naf Rév2', la
              valeur 'non référencé' est utilisée.
              \n
              \n
              Le lien vers la nomenclature 'Naf Rév2' : https://www.insee.fr/fr/information/2406147"
          nomenclature:
            type: 'string'
            example: 'NAFRev2'
            description: 'Nomenclature associée au code'
      tranche_effectif_salarie:
        type: 'object'
        properties:
          code:
            type: 'string'
            nullable: true
            example: '51'
          intitule:
            type: 'string'
            nullable: true
            example: "2 000 à 4 999 salariés"
          date_reference:
            type: 'string'
            nullable: true
            example: '2016'
          de:
            type: 'integer'
            example: 2000
            nullable: true
          a:
            type: "integer"
            example: 4999
            nullable: true
      etat_administratif:
        type: 'string'
        enum:
          - 'A'
          - 'C'
        example: 'A'
      date_cessation:
        type: 'integer'
        nullable: true
        example: 1634133818
      date_creation:
        type: 'integer'
        example: 1634103818
    links:
      siege_social:
        type: 'string'
        example: 'https://entreprises.api.gouv.fr/api/v3/insee/etablissements/30613890001294'
        description: "Lien vers la ressource établissement correspondant au siège social"
      siege_social_adresse:
        type: 'string'
        example: "https://entreprises.api.gouv.fr/api/v3/insee/etablissements/30613890001294/adresse"
        description: "Lien vers la ressource adresse de l'établissement correspondant au siège social"
    meta:
      date_derniere_mise_a_jour:
        type: 'integer'
        example: 1618396818
        description: "Date de la dernière mise à jour à l'INSEE"

  entreprise_diffusable:
    attributes:
      <<: *insee_entreprise_attributes
      diffusable_commercialement:
        type: 'boolean'
        example: true
        enum:
          - true
        description: "Détermine si l'entreprise est une entreprise
          non-diffusible. Cette valeur est toujours à true. Si vous voulez pouvoir récupérer des entreprises
          non-diffusible, référez-vous à la documentation du endpoint /insee/entreprise/:siren"

rnm:
  entreprise_artisanale:
    attributes:
      modalite_exercice:
        type: 'string'
        example: 'P'
        description: "Détermine si l'entreprise a une activité permanente ou saisonnière.
        \n
        L'activité est dite saisonnière si chaque année, l'entreprise cesse totalement ses activités pendant plus de 3 mois consécutifs.
        \n
        \n
        Les valeurs possibles sont:
        \n
        - P => Permanent
        \n
        - S => Saisonnière
        \n
        - NR => Non renseignée"
        enum:
          - 'P'
          - 'S'
          - 'NR'
      non_sedentaire:
        type: 'string'
        example: '0'
        description: "Indique si l'entreprise a une activité ambulante.
        \n
        \n
        Les valeurs possibles sont:
        \n
        - 0 => sédentaire
        \n
        - 1 => non-sédentaire"
        enum:
          - '0'
          - '1'

mi:
  association:
    attributes:
      titre:
        type: 'string'
        example: 'LA PRÉVENTION ROUTIERE'
      objet:
        type: 'string'
        example: "Accroitre la sécurité des usagers en encourageant toutes mesures ou initiatives propres à réduire les accidents"
        description: "Il s'agit d'une description courte mais exhaustive des activités de l'organisme."
      siret:
        type: 'string'
        nullable: true
        example:
      siret_siege_social:
        type: 'string'
        example: '77571979202650'
      date_creation:
        type: 'string'
        example: '1955-01-01'
        description: "Il s'agit du jour de dépôt du dossier de
          création de l'association à la Préfecture."
      date_declaration:
        type: 'string'
        example: '1955-01-01'
        description: "Jour de la dernière déclaration faîte par
          l'association."
      date_publication:
        type: "string"
        nullable: true
        example:
        description: "Jour de la publication au journal officiel
          de l'avis de création de l'association. Toutes les assoiations
          ne sont pas forcément 'déclarées'. La publication au
          Journal Officiel permet à l'association de devenir une
          personne morale, a contrario des 'associations de fait',
          non déclarées au JO."
      date_dissolution:
        type: 'string'
        nullable: true
        example:
        description: "Si l'association est dissolue, ce champ indique
          la date de dissolution, autrement, il est indiqué 'null'."
      adresse_siege:
        type: 'object'
        properties:
          complement:
            type: 'string'
            example: "  "
          numero_voie:
            type: 'string'
            example: '33'
          type_voie:
            type: 'string'
            example: "rue"
          libelle_voie:
            type: 'string'
            example: "de Modagor"
          distribution:
            type: 'string'
            nullable: true
            example:
          code_insee:
            type: 'string'
            example: '75108'
          code_postal:
            type: 'string'
            example: '75009'
          commune:
            type: 'string'
            example: 'Paris'
      etat:
        type: 'string'
        example: 'true'
      groupement:
        type: 'string'
        nullable: true
        example:
        description: "Trois modalités possibles : si l'association
          n'est pas un groupement, il est indiqué 'Simple'
          ; si l'association est un groupement, la valeur est
          'Union' ou 'Fédération'. La valeur peut aussi être
          manquante (null)"
      mise_a_jour:
        type: 'string'
        example: '1955-01-01'


acoss:
  attestation_sociale:
    document_url_properties:
      description: "Lien vers l'attestation de vigilance ACOSS. Ce document est automatiquement supprimé au bout de 3 mois."
      example: 'https://storage.entreprise.api.gouv.fr/siade/1569139162-b99824d9c764aae19a862a0af-attestation_vigilance_acoss.pdf'

probtp:
  attestation_cotisation_retraite:
    document_url_properties:
      description: "Lien vers l'attestation ProBtp. Ce document est automatiquement supprimé au bout de 3 mois."
      example: 'https://storage.entreprise.api.gouv.fr/siade/1569139162-b99824d9c764aae19a862a0af-attestation_cotisation_retraite_probtp.pdf'

