shared:
  low_latency_documents:
    throttle_type: 'by_group_of_endpoints'
    endpoints:
      - { controller: 'api_entreprise/v3_and_more/probtp/attestations_cotisation_retraite', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/fntp/carte_professionnelle_travaux_publics', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/cnetp/attestation_cotisations_conges_payes_chomage_intemperies', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/qualibat/certifications_batiment', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/mi/documents_associations', action: 'show' }
      - { controller: 'api_entreprise/inpi_proxy', action: 'show' }
    limit: 50
    period: 60
  high_latency_documents:
    throttle_type: 'by_single_endpoint'
    endpoints:
      - { controller: 'api_entreprise/v3_and_more/dgfip/attestations_fiscales', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/cibtp/attestation_cotisations_conges_payes_chomage_intemperies', action: 'show' }
    limit: 5
    period: 60
  json_resources_entreprise:
    throttle_type: 'by_group_of_endpoints'
    endpoints:
      - { controller: 'api_entreprise/v3_and_more/ademe/certificats_rge', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/carif_oref/certifications_qualiopi_france_competences', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/rnm/entreprises_artisanales', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/mi/associations', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/mi/unites_legales', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/mi/unites_legales_open_data', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/dgddi/eori', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/infogreffe/mandataires_sociaux', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/infogreffe/extraits_rcs', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/insee/unites_legales', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/insee/unites_legales_diffusables', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/insee/etablissements', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/insee/etablissements_diffusables', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/insee/adresses_etablissements', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/insee/adresses_etablissements_diffusables', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/insee/sieges_unites_legales', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/insee/sieges_diffusables_unites_legales', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/insee/successions', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/opqibi/certifications_ingenierie', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/probtp/conformites_cotisations_retraite', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/dgfip/liasses_fiscales', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/dgfip/liens_capitalistiques', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/dgfip/chiffres_affaires', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/msa/conformites_cotisations', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/fabrique_numerique_ministeres_sociaux/conventions_collectives', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/european_commission/vies', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/banque_de_france/bilans_entreprise', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/qualifelec/certificats', action: 'show' }
    limit: 250
    period: 60
  json_resources_particulier:
    throttle_type: 'by_group_of_endpoints'
    endpoints:
      - { controller: 'api_particulier/v3_and_more/cnav/allocation_adulte_handicape_with_civility', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnav/allocation_adulte_handicape_with_france_connect', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnav/allocation_soutien_familial_with_civility', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnav/allocation_soutien_familial_with_france_connect', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnav/complementaire_sante_solidaire_with_civility', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnav/complementaire_sante_solidaire_with_france_connect', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnav/participation_familiale_aeje_with_civility', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnav/participation_familiale_aeje_with_france_connect', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnav/prime_activite_with_civility', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnav/prime_activite_with_france_connect', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnav/quotient_familial_with_civility', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnav/quotient_familial_with_france_connect', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnav/revenu_solidarite_active_with_civility', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnav/revenu_solidarite_active_with_france_connect', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnous/etudiant_boursier_with_civility', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnous/etudiant_boursier_with_france_connect', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/cnous/etudiant_boursier_with_ine', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/dsnj/service_national_with_civility', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/dsnj/service_national_with_france_connect', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/france_travail/indemnites_with_identifiant', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/france_travail/statut_with_identifiant', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/men/scolarites_with_civility', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/mesri/statut_etudiant_with_civility', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/mesri/statut_etudiant_with_france_connect', action: 'show' }
      - { controller: 'api_particulier/v3_and_more/mesri/statut_etudiant_with_ine', action: 'show' }
    limit: 20
    period: 1

  inpi_rne:
    throttle_type: 'by_single_endpoint'
    limit: 30
    period: 60
    endpoints:
      - { controller: 'api_entreprise/v3_and_more/inpi/rne/beneficiaires_effectifs', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/inpi/rne/beneficiaires_effectifs_open_data', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/inpi/rne/actes_bilans', action: 'show' }
  urssaf_attestation_sociales:
    throttle_type: 'by_single_endpoint'
    limit: 100
    period: 60
    endpoints:
      - { controller: 'api_entreprise/v3_and_more/acoss/attestations_sociales', action: 'show' }
  proxied_files:
    throttle_type: 'by_single_endpoint'
    endpoints:
      - { controller: 'api_entreprise/proxied_files', action: 'show' }
    limit: 50
    period: 60
  gip_mds:
    throttle_type: 'by_group_of_endpoints'
    limit: 100
    period: 60
    endpoints:
      - { controller: 'api_entreprise/v3_and_more/gip_mds/effectifs_annuels_entreprise', action: 'show' }
      - { controller: 'api_entreprise/v3_and_more/gip_mds/effectifs_mensuels_etablissement', action: 'show' }

test:
  low_latency_documents:
    limit: 2
  high_latency_documents:
    limit: 2
  json_resources_entreprise:
    limit: 2
  json_resources_particulier:
    limit: 2
  proxied_files:
    limit: 2
