---
variables:
  BUNDLER_VERSION: "2.2.4"
  CI: "true"
  CODE_COVERAGE: "true"
  MOCK_CALL_SYSTEM_FOR_MEMORY_ERROR: "true"

stages:
  - lint
  - test
  - push_to_master

lint:
  stage: lint
  image: ruby:3.0.3
  cache:
    key: "siade"
    paths:
      - vendor/ruby
    policy: pull
  before_script:
    - apt-get update -qq && apt-get install -y -qq qpdf libmagic-dev
    - gem update --system
    - gem install bundler -v $BUNDLER_VERSION --no-document
    - bundle install --full-index --path=vendor
  script:
    - bundle exec rubocop

test:
  stage: test
  image: ruby:3.0.3
  timeout: 10 minutes
  cache:
    key: "siade"
    paths:
      - vendor/ruby
    policy: pull
  before_script:
    - apt-get update -qq && apt-get install -y -qq qpdf libmagic-dev
    - gem update --system
    - gem install bundler -v $BUNDLER_VERSION --no-document
    - bundle install --full-index --path=vendor
  script:
    - ./bin/test_swagger.sh
    - bundle exec rspec spec/
    - bundle exec rails runner "print 'Test that production is loading for Zeitwerk'" -e production
  artifacts:
    reports:
      cobertura: coverage/coverage.xml

push_to_master:
  stage: push_to_master
  before_script:
    - "which ssh-agent || ( apt-get update -qy && apt-get install openssh-client -qqy )"
    - eval `ssh-agent -s`
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PUBLIC_KEY" >> ~/.ssh/id_rsa.pub
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - git config --global user.email "${CI_EMAIL}"
    - git config --global user.name "${CI_USERNAME}"
    - git fetch origin
    - git checkout -b develop origin/develop
    - git remote rm origin && git remote add origin git@gitlab.com:$CI_PROJECT_PATH.git
    - git push --force origin develop:master
  only:
    - develop

include:
  - template: Security/SAST.gitlab-ci.yml
