inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rspec_rails

require:
  - ./spec/support/custom_cops/open_payload_file.rb

RSpec:
  Language:
    Expectations:
      - assert_response

AllCops:
  NewCops: enable
  Exclude:
    - "Gemfile"
    - "Guardfile"
    - "Rakefile"
    - "bin/**/*"
    - "db/**/*"
    - "config/**/*"
    - "vendor/**/*"
    - "sandbox/**/*"
    - "spec/requests/ping_routes_spec.rb"

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

# Forcing 'super' is verbose
Lint/MissingSuper:
  Enabled: false

# No line between definitions is OK for oneliners
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

# Necessary to use NotImplementedError
Lint/InheritException:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - "spec/**/*_spec.rb"

Lint/UnreachableCode:
  Exclude:
    - "app/concepts/**/*"

# Sometimes useful in specs
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Exclude:
    - "lib/generators/**/*"
  AllowedMethods:
    - resource_attributes

Metrics/BlockLength:
  Exclude:
    - "spec/spec_helper.rb"
    - "spec/support/shared_examples/*"
    - "spec/factories/**/*"
  AllowedMethods:
    - "describe"
    - "context"
    - "namespace"
    - "shared_examples"
    - "let"
    - "path"
    - "get"
    - "response"

Metrics/ClassLength:
  Max: 200
  Exclude:
    - "app/interactors/**/build_resource.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/generators/**/*"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "app/interactors/**/build_resource.rb"
    - "spec/support/rswag_resources_payloads.rb"
    - "spec/support/rswag_commons_responses.rb"
    - "lib/generators/**/*"
  AllowedMethods:
    - resource_attributes

Metrics/ModuleLength:
  Exclude:
    - "spec/support/rswag_resources_payloads.rb"
    - "spec/support/rswag_commons_responses.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "lib/generators/**/*"

Naming/AccessorMethodName:
  Exclude:
    - "lib/generators/make_request/make_request_generator.rb"
    - "app/services/monitoring_service.rb"
    - "lib/generators/scaffold_resource/scaffold_resource_generator.rb"

# Allowing uppercase in some method names
Naming/MethodName:
  AllowedPatterns:
    - starts_with_FR?

Naming/MethodParameterName:
  AllowedNames:
    - "_"
    - "nb"
    - "id"

Naming/PredicateMethod:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/Inquiry:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/NestedGroups:
  Enabled: false

RSpec/ScatteredSetup:
  Exclude:
    - "spec/requests/api/v3_and_more/**/*_spec.rb"

RSpec/VariableName:
  Exclude:
  - "spec/requests/api_particulier/**/*_spec.rb"

Naming/VariableNumber:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"

# Authorizing expect{}.to
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/SafeNavigationChainLength:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - "app/channels/**/*"
    - "app/concepts/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

# Can't agree on this rule so we disable
Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    # Ignore mostly timestamp
    - "spec/requests/api/**/*_spec.rb"
    - "spec/support/rswag_*.rb"

Style/OpenStructUse:
  Exclude:
    - "spec/**/*_spec.rb"

# Do not force use of fail or raise only both have their use
Style/SignalException:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    # More convenient to write RSwag documentation in french
    - "spec/requests/api/**/*_spec.rb"

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - sandbox
    - development
    - test

# This is okay when use_transactional_fixtures is disabled
RSpec/BeforeAfterAll:
  Enabled: false

# Not relevant for RSwag
RSpec/DescribeClass:
  Exclude:
    - "spec/requests/**/*"
    - "spec/acceptances/**/*"

RSpec/DescribeMethod:
  Enabled: false

# Necessary to avoid 'Include described_class' which bugs
RSpec/DescribedClass:
  SkipBlocks: true

# False positive with RSwag
RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/requests/**/*"

# This is not relevant for huge payloads, just ignored it
RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  Exclude:
    - 'spec/lib/seeds_spec.rb'

Rails/FilePath: &rails_file_path
  Exclude:
    - "spec/policies/certificat_rge_ademe_policy_spec.rb"
    - "spec/requests/rack_attack_spec.rb"
    - "spec/interactors/get_oauth2_token_spec.rb"
    - "spec/errors/dgfip_svair_access_denied_error_spec.rb"
    - "spec/errors/gip_mds_error_spec.rb"

RSpec/SpecFilePathFormat:
  CustomTransform:
    GIPMDS: gip_mds
    OAuth2: oauth2
  <<: *rails_file_path

# Sometimes useful in tests
RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

# We like multiple expectations
RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

# We also like unnamed subject
RSpec/NamedSubject:
  Enabled: false

# Bug with 'its'
RSpec/RepeatedDescription:
  Enabled: false
