inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "Gemfile"
    - "Guardfile"
    - "Rakefile"
    - "bin/**/*"
    - "db/**/*"
    - "config/**/*"
    - "vendor/**/*"
    - "app/controllers/api/v2/**/*"
    - "spec/controllers/api/v2/**/*"
    - "lib/siade/v2/**/*"
    - "spec/lib/siade/v2/**/*"

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

# No line between definitions is OK for oneliners
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

# Necessary to use NotImplementedError
Lint/InheritException:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - "spec/**/*_spec.rb"

Lint/UnreachableCode:
  Exclude:
    - "app/concepts/**/*"

Metrics/AbcSize:
  IgnoredMethods:
    - resource_attributes

Metrics/BlockLength:
  Exclude:
    - "spec/spec_helper.rb"
    - "spec/support/shared_examples/*"
    - "spec/factories/**/*"
  IgnoredMethods:
    - "describe"
    - "context"
    - "namespace"
    - "shared_examples"
    - "let"
    - "path"
    - "get"
    - "response"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "spec/support/rswag_resources_payloads.rb"
    - "spec/support/rswag_commons_responses.rb"
  IgnoredMethods:
    - resource_attributes

Metrics/ModuleLength:
  Exclude:
    - "spec/support/rswag_resources_payloads.rb"
    - "spec/support/rswag_commons_responses.rb"

Naming/AccessorMethodName:
  Exclude:
    - "app/interactors/**/**/make_request.rb"
    - "app/interactors/make_request.rb"
    - "lib/generators/make_request/make_request_generator.rb"
    - "app/services/monitoring_service.rb"
    - "lib/generators/scaffold_resource/scaffold_resource_generator.rb"

# Allowing uppercase in some method names
Naming/MethodName:
  IgnoredPatterns:
    - starts_with_FR?

Naming/MethodParameterName:
  AllowedNames:
    - "_"
    - "nb"

RSpec/NestedGroups:
  Max: 5

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"

# Authorizing expect{}.to
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - "app/channels/**/*"
    - "app/concepts/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

# Can't agree on this rule so we disable
Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    # Ignore mostly timestamp
    - "spec/requests/api/**/*_spec.rb"
    - "spec/support/rswag_*.rb"

# Do not force use of fail or raise only both have their use
Style/SignalException:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    # More convenient to write RSwag documentation in french
    - "spec/requests/api/**/*_spec.rb"

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - sandbox
    - development
    - test

# Not relevant for RSwag
RSpec/DescribeClass:
  Exclude:
    - "spec/requests/**/*"
    - "spec/acceptances/**/*"

# Necessary to avoid 'Include described_class' which bugs
RSpec/DescribedClass:
  SkipBlocks: true

# False positive with RSwag
RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/requests/**/*"

# This is not relevant for huge payloads, just ignored it
RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - "spec/policies/certificat_rge_ademe_policy_spec.rb"
    - "spec/requests/rack_attack_spec.rb"
    - "spec/interactors/get_oauth2_token_spec.rb"
